Explicitly releasing non-heap memory leads to undefined behavior.

== Why is this an issue?

The `free` function and `delete` operator are used exclusively to release dynamically allocated memory.
Attempting to release any other type of memory is _undefined behavior_.

This rule raises an issue when trying to release pointers to non-heap memory, such as:

* Stack allocated memory - local variables or memory allocated with the `alloca`, `_alloca`, `_malloca` and `__builtin_alloca` functions.
* Program executable code - function pointers.
* Program data - global and static variables.
* Read-only program data - constants and strings.


== How to fix it

Remove any calls to `free` or `delete` that release non-heap memory.

As a best practice, do not use the same pointer variable to point to heap memory and any other type of memory at different points in the program.

=== Code examples

Stack allocated memory:

==== Noncompliant code example

[source,cpp,diff-type=noncompliant,diff-id=1]
----
void fun(int size) {
  int number = 0;
  char* name = (char*)alloca(size);
  // ...
  delete &number; // Noncompliant, memory allocated on the stack.
  free(name); // Noncompliant, memory allocated on the stack.
}
----

==== Compliant solution

[source,cpp,diff-type=compliant,diff-id=1]
----
void fun(int size) {
  int number = 0;
  char* name = (char*)alloca(size);
  // ...
}
----

Program executable code:

==== Noncompliant code example

[source,cpp,diff-type=noncompliant,diff-id=2]
----
int get10() {
  return 10;
}

void fun() {
  // ...
  free((void*) &get10); // Noncompliant, memory part of program executable code.
}
----

==== Compliant solution

[source,cpp,diff-type=compliant,diff-id=2]
----
int get10() {
  return 10;
}

void fun() {
  // ...
}
----

Program data:

==== Noncompliant code example

[source,cpp,diff-type=noncompliant,diff-id=3]
----
struct S {
  static inline int data = 64;
};

void fun() {
  static int x = 8;
  // ...
  free(&x); // Noncompliant, memory part of program data.
  free(&S::data); // Noncompliant, memory part of program data.
}
----

==== Compliant solution

[source,cpp,diff-type=compliant,diff-id=3]
----
struct S {
  static inline int data = 64;
};

void fun() {
  static int x = 8;
  // ...
}
----

Read-only program data:

==== Noncompliant code example

[source,cpp,diff-type=noncompliant,diff-id=4]
----
int const limit = 128;

void fun() {
  char* name = "string";
  // ...
  free((void*)&limit); // Noncompliant, memory part of read-only program data.
  free(name); // Noncompliant, memory part of read-only program data.
}
----

==== Compliant solution

[source,cpp,diff-type=compliant,diff-id=4]
----
int const limit = 128;

void fun() {
  char const* name = "string";
  // ...
}
----


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Remove this "free" call; the memory will be released automatically.


=== Highlighting

* primary: ``++free(xxx)++``
* secondary: allocation


'''
== Comments And Links
(visible only on this page)

=== on 31 Mar 2016, 14:02:56 Ann Campbell wrote:
\[~massimo.paladin] what happens if you ``++free++`` this memory anyway? Crash? Memory corruption? Leak? The description should include at least a hint & I need to know to set the SQALE characteristic.

=== on 31 Mar 2016, 14:31:56 Massimo PALADIN wrote:
\[~ann.campbell.2] it is an undefined behavior, i.e. on my setup I am getting a crash.

=== on 31 Mar 2016, 16:23:09 Ann Campbell wrote:
Thanks [~massimo.paladin]. I've made some small updates. 

=== on 27 Mar 2019, 16:51:29 Ann Campbell wrote:
FYI, [~massimo.paladin] the "raises an issue when" clause usually comes at the end of the descriptive text.

endif::env-github,rspecator-view[]
