== Ask Yourself Whether

* the private key might not be random, strong enough or the same key is reused for a long long time.
* the private key might be compromised. It can happen when it is stored in an unsafe place or when it was transferred in an unsafe manner.
* the key exchange is made without properly authenticating the receiver.
* the encryption algorithm is not strong enough for the level of protection required. Note that encryption algorithms strength decreases as time passes.
* the chosen encryption library is deemed unsafe.
* a nonce is used, and the same value is reused multiple times, or the nonce is not random.
* the RSA algorithm is used, and it does not incorporate an Optimal Asymmetric Encryption Padding (OAEP), which might weaken the encryption.
* the CBC (Cypher Block Chaining) algorithm is used for encryption, and it's IV (Initialization Vector) is not generated using a secure random algorithm, or it is reused.
* the Advanced Encryption Standard (AES) encryption algorithm is used with an unsecure mode. See the recommended practices for more information.

You are at risk if you answered yes to any of those questions.
