=== On 2015-05-11T14:49:23Z Dinesh Bolkensteyn Wrote:
The description sounds like chinese and the compliant solution still includes a ``++// Noncompliant++`` flag

=== On 2015-05-11T15:31:30Z Dinesh Bolkensteyn Wrote:
In fact this is quite complex, I've managed to understand the issue only after carefully reading the following article in full:

http://blogs.msdn.com/b/samng/archive/2007/11/26/virtual-events-in-c.aspx

=== On 2015-05-12T12:23:49Z Ann Campbell Wrote:
\[~dinesh.bolkensteyn] can you be more specific about what in the description you find unhelpful and/or suggest or make some edits, please?

=== On 2015-05-12T14:35:46Z Dinesh Bolkensteyn Wrote:
What is the initial source for this rule [~ann.campbell.2]?

=== On 2015-05-12T15:45:18Z Dinesh Bolkensteyn Wrote:
I've tried to give a bit more context and a full example.

=== On 2015-05-14T12:47:13Z Ann Campbell Wrote:
I've made some edits [~dinesh.bolkensteyn]. See what you think. 

In particular, I'm not sure about the correct order of the words ``++private++`` and ``++delegate++``. You had ``++delegate++`` ``++private++``, which sounds odd to me in English, so I swapped them. But please swap back if that's the particular order they should appear in.

=== On 2015-05-18T06:05:30Z Dinesh Bolkensteyn Wrote:
LGTM!

