=== on 20 Aug 2013, 08:39:47 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-299

=== on 24 Aug 2013, 18:55:53 Ann Campbell wrote:
2 comments here:


First, I changed the meaning 

from: if you have more than X dependencies, you're breaking SRP 

to: if you have more than X dependencies, you're probably breaking SRP.


because the description clearly states that "there is no way to automatically check whether a class complies with the SRP..." (If there's no way to check, then we can't automatically say you're in violation based on the dependency count.)


Second, I changed "a class should have only one reason to change" to "a class should have only one responsibility." I couldn't make heads or tails of the former and finally guessed that it must have been a case of "distracted typing." Apologies if I was wrong.

=== on 25 Aug 2013, 18:42:21 Freddy Mallet wrote:
The two changes make sense, thanks [~ann.campbell.2]

=== on 9 Oct 2013, 12:58:37 Dinesh Bolkensteyn wrote:
IMO it's bad to use the acronym "SRP" which is not a well-known one, especially in a sentence where "Single Reponsibility Principle" already appears as is.

There must be a way to reformulate to avoid the repeatition.


Using acronyms increases what's known as the "cognitive load", see \http://en.wikipedia.org/wiki/Cognitive_load and makes the whole description more complex to understand.

=== on 23 Feb 2014, 23:23:04 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3514 for PHP

