== Why is this an issue?

Using explicit loops for filtering, selecting, or aggregating elements can make code more verbose and harder to read. LINQ expressions provide a more concise and expressive way to perform these operations, improving code clarity and maintainability.

=== Performance Considerations

If the affected code is part of a performance-critical hot path and that the fix would negatively impact performance, you can self-declare the `PerformanceSensitiveAttribute` in your codebase, or use the one provided by Roslyn.Utilities:

[source,csharp]
----
[AttributeUsage(AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = true, Inherited = false)]
public sealed class PerformanceSensitiveAttribute() : Attribute;

[PerformanceSensitiveAttribute]
List<string> Method(IEnumerable<string> collection, Predicate<string> condition)
{
  var result = new List<string>();
  foreach (var element in collection)  // Without the attribute, this would raise an issue
  {
    if (condition(element))
    {
      result.Add(element);
    }
  }
  return result;
}
----

== How to fix it

Replace explicit loops and conditional blocks with equivalent LINQ expressions.

Use the https://www.nuget.org/packages/System.Linq.Async[System.Linq.Async] package to enable LINQ operations on https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerable-1[IAsyncEnumerable] prior to .NET 10.

=== Code examples

==== Noncompliant code example

[source,csharp,diff-id=1,diff-type=noncompliant]
----
List<string> Method(IEnumerable<string> collection, Predicate<string> condition)
{
  var result = new List<string>();
  foreach (var element in collection)  // Noncompliant
  {
    if (condition(element))
    {
      result.Add(element);
    }
  }
  return result;
}
----

[source,csharp,diff-id=2,diff-type=noncompliant]
----
List<string> Method(IEnumerable<MyDto> collection)
{
  var result = new List<string>();
  foreach (var element in collection) // Noncompliant
  {
    var someValue = element.Property;
    if (someValue != null)
    {
      result.Add(someValue);
    }
  }
  return result;
}
----

[source,csharp,diff-id=3,diff-type=noncompliant]
----
async Task<List<string>> Method(IAsyncEnumerable<string> collection)
{
  var result = new List<string>();
  await foreach (var element in collection) // Noncompliant
  {
    if (element != null)
    {
      result.Add(element);
    }
  }
  return result;
}
----

==== Compliant solution

[source,csharp,diff-id=1,diff-type=compliant]
----
List<string> Method(IEnumerable<string> collection, Predicate<string> condition) =>
  collection.Where(x => condition(x)).ToList();
----

[source,csharp,diff-id=2,diff-type=compliant]
----
List<string> Method(IEnumerable<MyDto> collection) =>
  collection.Select(x => x.Property).Where(y => y != null).ToList();
----

[source,csharp,diff-id=3,diff-type=compliant]
----
List<string> Method(IAsyncEnumerable<string> collection) =>
  collection.Where(x => x != null).ToList();
----

== Resources

=== Documentation

* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/csharp/linq[Language Integrated Query (LINQ)]
* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerable-
1[IAsyncEnumerable<T> Interface]
* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/10.0/asyncenumerable[System.Linq.AsyncEnumerable in .NET 10]
* NuGet - https://www.nuget.org/packages/System.Linq.Async[System.Linq.Async]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

* Use a LINQ expression in the loop declaration instead of this "xxx".


'''
== Comments And Links
(visible only on this page)

=== on 10 Jul 2015, 12:30:19 Ann Campbell wrote:
\[~tamas.vajk] I tried to break the code samples into individual issues. Please help if I muffed it.

=== on 20 Jul 2015, 11:38:39 Tamas Vajk wrote:
\[~ann.campbell.2] I removed a "probably" from the description.

=== on 20 Jul 2015, 14:36:13 Ann Campbell wrote:
thanks [~tamas.vajk]

endif::env-github,rspecator-view[]
