== Why is this an issue?

When used as a type specifier in a declaration, `auto` allows the compiler to deduce the type of a variable based on the type of the initialization expression.

When the spelling of the initialization expression already contains the type of the declared variable, it leaves no ambiguity and `auto` should be used as it makes the code easier to read and reduces duplication. This includes:

* Initializations using `new`

[source,cpp]
----
void f() {
  LongAndBoringClassName *avoid = new LongAndBoringClassName(); // Noncompliant

  auto prefer = new LongAndBoringClassName(); // Compliant
}
----

* Template factory functions for smart pointers

[source,cpp]
----
void f() {
  std::unique_ptr<LongAndBoringClassName> avoid = std::make_unique<LongAndBoringClassName>(); // Noncompliant
  auto prefer = std::make_unique<LongAndBoringClassName>(); // Compliant
}
----

* Cast expressions

[source,cpp]
----
void f() {
  C *c = new LongAndBoringClassName(); // Compliant

  LongAndBoringClassName *avoid = static_cast<LongAndBoringClassName*>(c); // Noncompliant

  auto prefer = static_cast<LongAndBoringClassName*>(c); // Compliant
}
----

The rule S6234 detects other situations where `auto` can improve readability.


== Resources

=== External coding guidelines

* {ccg_ES_11}

=== Related rules

* S6234 - "auto" should be used to store a result of functions that conventionally return an iterator or a range

ifdef::env-github,rspecator-view[]
'''
== Comments And Links
(visible only on this page)

=== is related to: S6234

endif::env-github,rspecator-view[]
