include::../description.adoc[]

include::../ask-yourself.adoc[]

include::../recommended.adoc[]

== Sensitive Code Example
In the examples below, an install script is downloaded using `curl` or `wget` and then executed.

While connections made using HTTPS are generally considered secure, `\https://might-redirect.example.com/install.sh`
might redirect to a location that uses HTTP. Downloads made using HTTP are not secure and can be intercepted and
modified. An attacker could modify the install script to run malicious code inside the container.

`curl` will not follow redirects unless either `-L` or `--location` option is used.

[source,docker,diff-id=1,diff-type=noncompliant]
----
FROM ubuntu:22.04

# Sensitive
RUN curl --tlsv1.2 -sSf -L https://might-redirect.example.com/install.sh | sh
----

`wget` will follow redirects by default.

[source,docker,diff-id=2,diff-type=noncompliant]
----
FROM ubuntu:22.04

# Sensitive
RUN wget --secure-protocol=TLSv1_2 -q -O - https://might-redirect.example.com/install.sh | sh
----

== Compliant Solution

If you expect the server to redirect the download to a new location, `curl` can use the option `--proto "=https"`
to ensure requests are only made using HTTPS. Any attempt to redirect to a location using HTTP will result in an error.

[source,docker,diff-id=1,diff-type=compliant]
----
FROM ubuntu:22.04

RUN curl --proto "=https" --tlsv1.2 -sSf -L https://might-redirect.example.com/install.sh | sh
----

`wget` does not support this functionality so `curl` should be used instead.

If you expect the server to return the file without redirects, `curl` should not be instructed to follow redirects.
Remove any `-L` or `--location` options from the command.

[source,docker,diff-id=1,diff-type=compliant]
----
FROM ubuntu:22.04

RUN curl --tlsv1.2 -sSf https://might-redirect.example.com/install.sh | sh
----

`wget` uses the option `--max-redirect=0` to disable redirects.

[source,docker,diff-id=2,diff-type=compliant]
----
FROM ubuntu:22.04

RUN wget --secure-protocol=TLSv1_2 --max-redirect=0 -q -O - https://might-redirect.example.com/install.sh | sh
----

include::../see.adoc[]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

include::highlighting.adoc[]
