=== On 2019-08-28T21:26:35Z Loïc Joly Wrote:
\[~abbas.sabra]: I think this rule might miss it's target a little bit: For me, the important point is that hash function should not throw. As a consequence, it might be interesting to declare it noexcept, but this looks to me like an indirect consequence. If you agree, I can reword the rule that way, otherwise, let me know :)



=== On 2019-08-29T09:54:26Z Abbas Sabra Wrote:
\[~loic.joly] My bad, I agree with you.

=== On 2019-08-29T18:49:45Z Loïc Joly Wrote:
I updated the rule, but I think we might still miss to opportunity to have a better rule: "Hash function should be written correctly". It would check for exceptions, but also for other things. The problem is I'm not sure what these other things might be (I know some constraints, but I don't know how to realistically check them... If anybody has an idea?)



=== On 2019-09-09T17:44:24Z Ann Campbell Wrote:
\[~abbas.sabra] and [~loic.joly] does this rule raise issues only on ``++throw++`` or also on a missing ``++noexcept++``? I think the latter is implicit in the code samples, but it should be either obvious in the description or made explicit with a "This rule raises an issue when" sentence.

=== On 2019-09-10T09:21:45Z Loïc Joly Wrote:
This is a good and difficult question:

* The rule has some value for legacy code, dating from a time where noexcept did not yet exist. Raising on missing noexcept in those cases might look like a false positive
* Raising on missing noexcept would have the value of enforcing good practices, in addition to prevent throwing
\[~abbas.sabra]: What do you think?

=== On 2019-09-10T09:56:47Z Abbas Sabra Wrote:
I think we should detect the standard. If it is >= {cpp}11 we should raise an issue on missing noexecpt.

=== On 2019-09-10T10:17:40Z Loïc Joly Wrote:
\[~abbas.sabra]: In many cases, old code gets compiled with new compilers, maybe even new flags... 

=== On 2019-09-10T11:04:15Z Abbas Sabra Wrote:
\[~loic.joly] Yes, but in that case, it is not really a false positive. 


Do you think it is a good idea to divide it into two?

* The first flags throwing hash functions.
* The second is part of [|RSPEC-5018|https://jira.sonarsource.com/browse/RSPEC-5018] => Hash, Move, and swap operations should be "noexcept"

=== On 2019-10-07T16:34:22Z Amélie Renard Wrote:
In my opinion, I would divide it into 2 RSPECS as [~abbas.sabra] suggests:

* one about hash functions that should not throw (as described in current RSPEC)
* one about hash functions that should be declared no except (not sure if it should be merged with the one dealing with `move` or destructors though...)
I find the current message "Declare this hash 'noexcept'." not really consistent with the description of the rule: if a hash function does not throw, there will be no warning but the message still applies...


In addition, it would be consistent with the rules about destructors:

* https://jira.sonarsource.com/browse/RSPEC-3654[RSPEC-3654]: Destructors should be "noexcept"
* https://jira.sonarsource.com/browse/RSPEC-1048[RSPEC-1048]: Destructors should not throw exceptions

=== On 2019-10-10T13:31:48Z Ann Campbell Wrote:
\[~amelie.renard] issue messages should be imperative, with a fall back to statement-of-fact only as a last resort.

