This rule raises an issue when a Groovy file imports classes from packages that are automatically imported by Groovy.

== Why is this an issue?

Groovy automatically imports classes from several common packages to reduce boilerplate code. These packages include:

* `java.lang` (String, Object, Integer, etc.)
* `java.util` (List, Map, Set, etc.)
* `java.io` (File, InputStream, OutputStream, etc.)
* `java.net` (URL, URI, etc.)
* `groovy.lang` (Closure, GroovyObject, etc.)
* `groovy.util` (ConfigSlurper, etc.)
* `java.math.BigDecimal` and `java.math.BigInteger`

When you explicitly import classes from these packages, you create unnecessary code that:

* Adds visual clutter to your files
* Makes it harder to identify which dependencies are actually required
* Can confuse developers who might think these imports are needed for the code to work
* Increases the maintenance burden when refactoring code

Removing these redundant imports keeps your code clean and focused on the actual external dependencies your code requires.

=== What is the potential impact?

This issue affects code maintainability and readability. While it doesn't cause runtime problems, unnecessary imports create visual noise that makes it harder for developers to understand the actual dependencies of the code. Clean import sections help developers quickly identify external libraries and focus on the code's real requirements.

== How to fix it

Remove import statements for classes that are automatically imported by Groovy. These classes are available without explicit imports.

=== Code examples

==== Noncompliant code example

[source,groovy,diff-id=1,diff-type=noncompliant]
----
import java.lang.String // Noncompliant
import java.util.List // Noncompliant
import java.io.File // Noncompliant
import groovy.lang.Closure // Noncompliant
import java.math.BigDecimal // Noncompliant

class MyClass {
    List<String> items
    File configFile
    Closure processor
    BigDecimal amount
}
----

==== Compliant solution

[source,groovy,diff-id=1,diff-type=compliant]
----
class MyClass {
    List<String> items
    File configFile
    Closure processor
    BigDecimal amount
}
----

== Resources

=== Documentation

 * Groovy Language Documentation - Default Imports - https://groovy-lang.org/structure.html#_default_imports[Official Groovy documentation explaining which packages are automatically imported]

 * CodeNarc UnnecessaryGroovyImport Rule - https://codenarc.org/codenarc-rules-imports.html#unnecessarygroovyimport-rule[CodeNarc rule documentation for detecting unnecessary Groovy imports]

=== Related rules

 * RSPEC-1128 - https://rules.sonarsource.com/java/RSPEC-1128/[Unused imports should be removed (Java)]
