=== on 8 Oct 2014, 18:10:47 Ann Campbell wrote:
\[~nicolas.peru] to what degree do we see/pay attention to "run once" annotations during analysis, e.g. @PostConstruct?

=== on 22 Oct 2014, 19:14:36 Nicolas Peru wrote:
At the moment : none. 

So this rule won't detect that your random object is initialized in an init method.


It might makes more sense to actually detect Random local variables. 

=== on 22 Oct 2014, 19:40:32 Ann Campbell wrote:
\[~nicolas.peru] you mean local ``++Random++`` variables, right? :-)

(I did actually have to read that twice & note the capital letter to understand your meaning :-) )


I'd say that as written, this rule is about local ``++Random++``s (did you assign it back to me because you don't agree?), but I was hoping to be able to make it smarter. Oh well.

=== on 15 Aug 2018, 18:28:35 Nicolas Harraudeau wrote:
This RSPEC is for now limited to detecting local variables of type ``++java.util.Random++``.

It could later cover cases where the Random object is not even assigned:

----
(new Random()).nextInt()
----

