== Why is this an issue?

The creation of a ``++JAXBContext.newInstance++`` is a costly operation, and should only be performed once per context and stored - preferably in a ``++static++`` member - for reuse.


In fact, according to the JAXB 2.2 Specification:

____
To avoid the overhead involved in creating a JAXBContext instance, a JAXB application is encouraged to reuse a JAXBContext instance. An implementation of abstract class JAXBContext is required to be thread-safe, thus, multiple threads in an application can share the same JAXBContext instance.
____


This rule raises an issue when multiple instances are created for the same context path.


=== Noncompliant code example

[source,java]
----
public void doSomething(List<MyObj> inputs) {
  for (String input : inputs) {
    Marshaller m = JAXBContext.newInstance(MyObj.class).createMarshaller();  // Noncompliant; context created in loop
    // ... 
  }
}

public List<JAXBContext> getContexts(List<Class> inputs) {
  List<JAXBContext> result = new ArrayList<>();
  for (Class input : inputs) {
    result.add(JAXBContext.newInstance(input);  // Compliant; context path varies
  }
  return result;
}

public void doSomething2(List<MyObj> inputs) {
  Marshaller m = JAXBContext.newInstance(MyObj.class).createMarshaller();  // Noncompliant; context created each time method invoked
  for (String input : inputs) {
    // ...
  }
}
----


=== Compliant solution

[source,java]
----

private static JAXBContext context;
static {
  try {
    context = JAXBContext.newInstance(MyObj.class);
  } catch (JAXBException e) {
    // handle exception...
  }
}

public void doSomething(List<MyObj> inputs) {
  Marshaller m = context.createMarshaller();
  for (String input : inputs) {
    // ... 
  }
}

public List<JAXBContext> getContexts(List<Class> inputs) {
  List<JAXBContext> result = new ArrayList<>();
  for (Class input : inputs) {
    result.add(JAXBContext.newInstance(input);
  }
  return result;
}
----

=== Benchmarks

[options="header"]
|===
| Method| Runtime| Average time| Error margin
| instantiateInsideLoop| Temurin 21| 267.63 ms/op| ±119.19 ms/op
| instantiateBeforeLoop| Temurin 21| 6.36 ms/op| ±2.33 ms/op
|===

*Benchmarking code*

The results were generated by running the following snippet with https://github.com/openjdk/jmh[JMH].

[source,java]
----
  @XmlRootElement
  public static class MyObj {
    int field1;
    int field2;

    @XmlElement(name = "field1")
    public int getField1() {
      return field1;
    }

    @XmlElement(name = "field2")
    public int getField2() {
      return field2;
    }

    public static MyObj make(int field1, int field2) {
      MyObj obj = new MyObj();
      obj.field1 = field1;
      obj.field2 = field2;
      return obj;
    }
  }

  List<MyObj> inputs;

  @Setup(Level.Trial)
  public void setup() {
    inputs = new ArrayList<>();
    Random random = new Random();
    for (int i = 0; i < 10_000; i++) {
      inputs.add(MyObj.make(random.nextInt(100), random.nextInt(100)));
    }
  }

  /**
   * Used for testing to make sure benchmarking code perform a correct operation.
   */
  @VisibleForTesting
  static String documentToString(Document doc) {
    try {
      javax.xml.transform.TransformerFactory transformerFactory = javax.xml.transform.TransformerFactory.newInstance();
      javax.xml.transform.Transformer transformer = transformerFactory.newTransformer();
      transformer.setOutputProperty(javax.xml.transform.OutputKeys.INDENT, "yes");
      transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2");

      javax.xml.transform.dom.DOMSource source = new javax.xml.transform.dom.DOMSource(doc);
      StringWriter stringWriter = new StringWriter();
      javax.xml.transform.stream.StreamResult result = new javax.xml.transform.stream.StreamResult(stringWriter);
      transformer.transform(source, result);
      return stringWriter.toString();
    } catch (TransformerException e) {
      return null;
    }
  }

  @Benchmark
  public Document instantiateBeforeLoop() throws JAXBException, ParserConfigurationException {
    DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
    dbf.setNamespaceAware(true);
    DocumentBuilder db = dbf.newDocumentBuilder();
    Document doc = db.newDocument();

    Element rootElement = doc.createElement("myObjectsWrapper");
    doc.appendChild(rootElement);

    Marshaller m = JAXBContext.newInstance(MyObj.class).createMarshaller();

    for (MyObj input : inputs) {
      m.marshal(input, rootElement);
    }
    return doc;
  }

  @Benchmark
  public Document instantiateInsideLoop() throws JAXBException, ParserConfigurationException {
    DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
    dbf.setNamespaceAware(true);
    DocumentBuilder db = dbf.newDocumentBuilder();
    Document doc = db.newDocument();

    Element rootElement = doc.createElement("myObjectsWrapper");
    doc.appendChild(rootElement);

    for (MyObj input : inputs) {
      Marshaller m = JAXBContext.newInstance(MyObj.class).createMarshaller();  // Noncompliant; context created in loop
      m.marshal(input, rootElement);
    }
    return doc;
  }
----

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Store this "JAXBContext" in a "static" member and reuse it.


'''
== Comments And Links
(visible only on this page)

=== on 17 Sep 2015, 09:27:10 Ann Campbell wrote:
source: \https://twitter.com/CyrilP_tweet/status/644432004340150272?cn=cmVwbHk%3D&refsrc=email

=== on 14 Sep 2016, 08:12:35 Ann Campbell wrote:
From \https://groups.google.com/forum/#!topic/sonarqube/YGMsyzSkeQk:

In the past we've used a PMD XPath rule that looks like this "//MethodDeclaration//PrimaryExpression/PrimaryPrefix/Name[@Image='JAXBContext.newInstance'][ancestor::ClassOrInterfaceBodyDeclaration/Annotation/descendant::Name[contains(@Image,'SCOPE_PROTOTYPE')] or not(ancestor::ClassOrInterfaceBodyDeclaration/Annotation/descendant::Name[@Image='Bean'])]"

endif::env-github,rspecator-view[]
