include::../../summary.adoc[]

== Why is this an issue?

include::../../rationale.adoc[]

include::../../impact.adoc[]

include::../../threats.adoc[]

== How to fix it?

The following code is vulnerable to cross-site scripting because it returns an HTML response that contains user input.

User input embedded in HTML code should be HTML-encoded to prevent the injection of additional code.
PHP provides the built-in function `htmlspecialchars` to do this.

[cols="a,a"]
|===
|
[source,php]
----
echo '<h1>' . $input . '</h1>'; // Noncompliant
----
|
[source,php]
----
echo '<h1>' . htmlspecialchars($input) . '</h1>';
----
|===

If you do not intend to send HTML code to the clients, the vulnerability can be resolved by telling them what data they are receiving using the content-type header.

For example, setting the content-type to `text/plain` using the built-in `header` function allows to safely reflect user input since browsers will not try to parse and execute the response.


[cols="a,a"]
|===
|
[source,php]
----
echo $input; // Noncompliant
----
|
[source,php]
----
header('Content-Type: text/plain');
echo $input;
----
|===

=== How does this work?

include::../../common/fix/data_encoding.adoc[]

=== Pitfalls

include::../../common/pitfalls/content-types.adoc[]

==== Single quoted variables in attributes

By default, `htmlspecialchars` does not encode single quotes, so if ``++$input++`` is untrusted, JavaScript code can be injected.

Make sure to set the option `ENT_QUOTES` to encode single quotes.

[cols="a,a"]
|===
|
[source,php]
----
echo "<img src='" . htmlspecialchars($input) . "'>";
----
|
[source,php]
----
echo "<img src='" . htmlspecialchars($input, ENT_QUOTES) . "'>";
----
|===

==== Headers and output

If the HTTP body is sent before `header` is called, no headers will be send to the client.

To resolve the issue send the headers before any output.

[cols="a,a"]
|===
|
[source,php]
----
echo 'No more headers at this point';
header('Content-Type: text/plain');
echo $input;
----
|
[source,php]
----
header('Content-Type: text/plain');
echo $input;
----
|===

=== Going the extra mile

== Resources

=== Documentation

include::../../common/resources/articles.adoc[]

include::../../common/resources/presentations.adoc[]

include::../../common/resources/standards.adoc[]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../../message.adoc[]

include::../../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
