include::../../summary.adoc[]

== Why is this an issue?

include::../../rationale.adoc[]

include::../../impact.adoc[]

include::../../threats.adoc[]

== How to fix it?

User input embedded in HTML code should be HTML-encoded to prevent the injection of additional code.
PHP provides the built-in function `htmlspecialchars` to do this.

[source,php]
----
echo '<h1>' . htmlspecialchars($input) . '</h1>';
----

If you do not intend to send HTML code to the clients, the vulnerability can be resolved by telling them what data they are receiving using the content-type header.
For example, setting the content-type to `text/plain` using the built-in `header` function allows to safely reflect user input since browsers will not try to parse and execute the response.

[source,php]
----
header('Content-Type: text/plain');
echo $input;
----

=== How does this work?

=== Pitfalls

By default, `htmlspecialchars` does not encode single quotes. Make sure to set the option `ENT_QUOTES` to encode single quotes if required by the context.

[source,php]
----
echo "<img src='" . htmlspecialchars($input, ENT_QUOTES) . "'>";
----


The content-type header has to be sent before any output is generated.
Otherwise, the header will not be sent to the client at all.


Be aware that there are more content-types than `text/html` that allow to execute JavaScript code in a browser and thus are prone to Cross-Site Scripting vulnerabilities.
The following content-types are known to be affected:

 * application/mathml+xml
 * application/rdf+xml
 * application/vnd.wap.xhtml+xml
 * application/xhtml+xml
 * application/xml
 * image/svg+xml
 * text/html
 * text/rdf
 * text/xml
 * text/xsl

=== Going the extra mile

include::../../resources.adoc[]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../../message.adoc[]

include::../../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
