== Why is this an issue?

IBM API keys are used to authenticate applications that consume IBM Cloud APIs.

If your application interacts with IBM then it requires credentials to access all the resources it needs to function properly. Resources that can be accessed depend on the permissions granted to the account. These credentials may authenticate a user who has unrestricted access to all resources in your account, including billing information.


== Recommended Secure Coding Practices

Only administrators should have access to the IBM API keys used by your application.

As a consequence, IBM API keys should not be stored along with the application code as they could be disclosed to a large audience or could be made public.

IBM API keys should be stored outside of the code in a file that is never committed to your application code repository.

If possible, a better alternative is to use your cloud provider's service for managing secrets. On IBM Cloud this service is called https://www.ibm.com/cloud/secrets-manager[Secrets Manager].

When credentials are disclosed in the application code, consider them as compromised and revoke them immediately.

In addition to secure storage, it's important to apply https://www.ibm.com/docs/it/db2oc?topic=management-identity-access-iam-cloud[restrictions] to API keys in order to mitigate the impacts when they are discovered by malicious actors.


== Resources

* https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/[OWASP Top 10 2021 Category A7] - Identification and Authentication Failures
* https://www.owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure[OWASP Top 10 2017 Category A3] - Sensitive Data Exposure
* https://cwe.mitre.org/data/definitions/798[MITRE, CWE-798] - Use of Hard-coded Credentials
* https://cwe.mitre.org/data/definitions/259[MITRE, CWE-259] - Use of Hard-coded Password
* https://www.sans.org/top25-software-errors/#cat3[SANS Top 25] - Porous Defenses

