=== How to fix it in Node.js

:canonicalization_function: `fs.realPath`
include::../../common/fix/code-rationale.adoc[]

==== Non-compliant code example

[source,javascript,diff-id=1,diff-type=noncompliant]
----
const fs = require('fs');
const path = require('path');

function (req, res) {
  const resourcesDir = "/data/app/resources/"
  const userFilename = path.join(resourcesDir, req.query.filename);

  let data = fs.readFileSync(userFilename, { encoding: 'utf8', flag: 'r' }); // Noncompliant
}
----

==== Compliant solution

[source,javascript,diff-id=1,diff-type=compliant]
----
const fs = require('fs');
const path = require('path');

function (req, res) {
  const resourcesDir = "/data/app/resources/"
  const userFilename = path.join(resourcesDir, req.query.filename));
  const userFilename = fs.realPath(userFilename);

  if (!userFilename.startsWith(resourcesDir)) {
    res.status(401).send();
  }

  let data = fs.readFileSync(userFilename, { encoding: 'utf8', flag: 'r' });
}
----

=== How does this work?

include::../../common/fix/self-validation.adoc[]

*Important Note*: The order of this process pattern is important. The code must follow this order exactly to be secure by design:

1. `data = transform(user_input);`
2. `data = normalize(data);`
3. `data = sanitize(data);`
4. `use(data);`

:tnsu_talk: https://www.youtube.com/watch?v=V-DdcKADnFk
As pointed out in {tnsu_talk}[this SonarSource talk], failure to follow this exact order leads to security vulnerabilities.

=== Pitfalls

include::../../common/pitfalls/partial-path-traversal.adoc[]

For example, the following code is vulnerable to partial path injection. Note
that the string `targetDirectory` does not end with a path separator:


[source, javascript]
----
const fs = require('fs');
const path = require('path');

function (req, res) {
  const resourcesDir = "/data/app/resources/"
  const userFilename = path.join(resourcesDir, req.query.filename));
  const userFilename = fs.realPath(userFilename);

  if (!userFilename.startsWith(resourcesDir)) {
    res.status(401).send();
  }

  let data = fs.readFileSync(userFilename);
}
----

This check can be bypassed because `"/Users/Johnny".startsWith("/Users/John")`
returns `true`. Thus, for validation, `"/Users/John"` should actually be
`"/Users/John/"`.

**Warning**: Some functions remove the terminating path separator in their
return value. +
The validation code should be tested to ensure that it cannot be impacted by
this issue.

