=== on 24 Nov 2015, 17:40:24 Ann Campbell wrote:
\[~michael.gumowski] do you think this should be a rule template?

Also, the inheritance of properties set in parent poms will be recognized, right?

=== on 25 Nov 2015, 09:03:03 Freddy Mallet wrote:
Just my own feedback: I'm not a big fan of such highly configurable rule. Do we really want it ? :)

=== on 30 Nov 2015, 15:45:20 Michael Gumowski wrote:
\[~ann.campbell.2] Users may indeed want to use this rule with multiple configurations... So it seems that a rule template would be a better approach.

Now, to me it's a bit too soon to consider that inheritance will be handled in analysis of pom in the java plugin. At least for a first iteration on handling java-related files. It will however be of course a long-term objective regarding how we handle pom files. I would then go for a first implementation without inheritance, or postpone the rule. WDYT?


\[~freddy.mallet], The rule was suggested by an user from the mailing list, when speaking about potential rules targeting pom.xml files. Their rules would target company-specific required attributes of the pom. This seems to be a fair need.

=== on 30 Nov 2015, 15:55:18 Ann Campbell wrote:
Thanks [~michael.gumowski], template update made.

