Android Keystore is a secure container to store key materials. It's possible to restrict access to the keys in the Keystore to only authenticated user (when the secure lock screen is unlocked with defined credentials (pattern/PIN/password, biometric)). 


== Ask Yourself Whether

* The key material is used in the context of a highly sensitive application like a e-banking mobile app.

There is a risk if you answered yes to this question.


== Recommended Secure Coding Practices

It's recommended to enable user authentication (by setting ``++setUserAuthenticationRequired++`` to ``++true++`` during key generation) and authorize authenticated user to use of the key materials during a limited duration after what the user should authenticate again (by setting appropriate values to ``++setUserAuthenticationValidityDurationSeconds++``).


== See

* https://developer.android.com/training/articles/keystore[developer.android.com] - Android keystore system
* https://developer.android.com/training/articles/keystore#UserAuthentication[developer.android.com] - Require user authentication for key use
* https://www.owasp.org/index.php/Top_10-2017_A6-Security_Misconfiguration[OWASP Top 10 2017 Category A6] - Security Misconfiguration
* https://cwe.mitre.org/data/definitions/522.html[MITRE, CWE-522] - Insufficiently Protected Credentials

