<code>private</code> or <code>internal</code> types or <code>private</code> members that are never executed or referenced are dead code: unnecessary, inoperative code that should be removed. Cleaning out dead code decreases the size of the maintained codebase, making it easier to understand the program and preventing bugs from being introduced.

== Noncompliant Code Example

----
public class Foo
{
    private void UnusedPrivateMethod() {...} // Noncompliant

    private class UnusedClass {...} // Noncompliant
}
----

== Compliant Solution

----
public class Foo
{
    public Foo()
    {
        UsedPrivateMethod();
    }

    private void UsedPrivateMethod() 
    {
        var c = new UsedClass();
    } 

    private class UsedClass {...}
}
----

== Exceptions

This rule doesn't raise issues on:
* Empty constructors
* Attributed members
* <code>Main</code> method
* Methods with event handler signature <code>void Foo(object, EventArgs)</code> that are declared in partial class
* Empty serialization constructor on type with <code>System.SerializableAttribute</code> attribute.
* Internals in assemblies that have a <code>System.Runtime.CompilerServices.InternalsVisibleToAttribute</code> attribute.
