== Why is this an issue?

Comparison operator implementations like ``++==++`` or ``++<=>++``, despite not being hard to write, remain a source of bugs as they must be updated with every change in the class's member list. For instance, if the operation does not consider a newly introduced member in the class, the issue will only manifest if two instances are identical, except for the freshly introduced member. As a consequence, this type of bug is usually hard to spot.


{cpp}20 introduced the ability to define both ``++operator<=>++`` and ``++operator==++`` as defaulted (``++= default++``) to indicate that they should consider all members in the order of their declaration. This makes code concise and makes all the comparison operators resilient to the changes to the list of members. Thanks to operator rewriting, all other comparison operations (``++!=++``, ``++<++``, ``++>++``, ``++<=++``, ``++=>++``) can also rely on these robust operators.

Furthermore, when ``++operator<=>++`` is defined as defaulted, the compiler will generate a defaulted version of ``++operator==++`` if no other version is declared.


== How to fix it

This rule raises an issue when the implementation of ``++operator<=>++`` or ``++operator==++`` has an equivalent semantic to the defaulted implementation. Defining these operators as defaulted is more concise and robust in these cases.

=== Code examples

==== Noncompliant code example

[source,cpp,diff-id=1,diff-type=noncompliant]
----
struct Comparable {
    int x;
    int y;
};

bool operator==(const Comparable& lhs, const Comparable& rhs) { // Noncompliant
    return lhs.x == rhs.x && lhs.y == rhs.y;
}
----

==== Compliant solution

[source,cpp,diff-id=1,diff-type=compliant]
----
struct Comparable {
    int x;
    int y;

    friend bool operator==(const Comparable&, const Comparable&) = default;
};
----

==== Noncompliant code example

[source,cpp,diff-id=2,diff-type=noncompliant]
----
struct Ordered {
    int x;
    int y;
};

bool operator==(const Ordered& lhs, const Ordered& rhs) { // Noncompliant
    return lhs.x == rhs.x && lhs.y == rhs.y;
}

auto operator<=>(const Ordered& lhs, const Ordered& rhs) { // Noncompliant
    if (res = lhs.x <=> rhs.x; res != 0)
        return x;
    return lhs.y <=> rhs.y;
}
----

==== Compliant solution

[source,cpp,diff-id=2,diff-type=compliant]
----
struct Ordered {
    int x;
    int y;

    friend auto operator<=>(const Ordered&, const Ordered&) = default;
};
----


== Resources

=== Documentation

* {cpp} reference - https://en.cppreference.com/w/cpp/language/default_comparisons[Default comparisons]

=== Related rules

* S6186 - removing redundant comparison operators
* S6187 - replacing multiple comparison operators with ``++operator<=>++``


ifdef::env-github,rspecator-view[]
'''
== Comments And Links
(visible only on this page)

=== relates to: S6186

=== relates to: S6187

endif::env-github,rspecator-view[]
