== Why is this an issue?

In C#, the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#is-operator[`is` type testing operator] can be used to check if the run-time type of an object is compatible with a given type. If the object is not null, then the `is` operator performs a cast, and so performing another cast following the check result is redundant.

This can impact:

* Performance: Performing the type check and cast separately can lead to minor performance issues. While this might not be noticeable in small applications, it can add up in larger, more complex systems.
* Readability: The code is less readable and less clean because it requires two lines (and two operations) to achieve something that could be done in one.

== How to fix it

Use https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/pattern-matching[pattern macthing] to perform the check and retrieve the cast result.

=== Code examples

==== Noncompliant code example

[source,csharp,diff-id=1,diff-type=noncompliant]
----
if (x is Fruit)  // Noncompliant
{
  var f = (Fruit)x; // or x as Fruit
  // ...
}
----


==== Compliant solution

[source,csharp,diff-id=1,diff-type=compliant]
----
if (x is Fruit fruit)
{
  // ...
}
----

== Resources

=== Documentation

* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast[Type-testing operators and cast expressions - `is`, `as`, `typeof` and casts]
* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/is[is operator (C# reference)]
* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/pattern-matching[Pattern matching overview]

=== Benchmarks

[options="header"]
|===
| Method               | Runtime              | Mean      | Standard Deviation   | Ratio 
| IsPattern_Class      | .NET 9.0             | 123.82 ns | 9.110 ns |  1.00
| IsWithCast_Class     | .NET 9.0             | 118.42 ns | 1.550 ns |  0.96
|                      |                      |           |          |      
| IsPattern_Class      | .NET Framework 4.8.1 | 144.71 ns | 9.638 ns |  1.00
| IsWithCast_Class     | .NET Framework 4.8.1 | 110.23 ns | 1.452 ns |  0.77
|                      |                      |           |          |      
| IsPattern_Interface  | .NET 9.0             |  34.05 ns | 3.520 ns |  1.00
| IsWithCast_Interface | .NET 9.0             |  35.10 ns | 1.308 ns |  1.04
|                      |                      |           |          |      
| IsPattern_Interface  | .NET Framework 4.8.1 |  83.81 ns | 5.175 ns |  1.00
| IsWithCast_Interface | .NET Framework 4.8.1 |  82.00 ns | 3.097 ns |  0.98
|                      |                      |           |          |      
| IsPattern_ValueType  | .NET 9.0             |  29.90 ns | 1.031 ns |  1.00
| IsWithCast_ValueType | .NET 9.0             |  29.20 ns | 1.722 ns |  0.98
|                      |                      |           |          |      
| IsPattern_ValueType  | .NET Framework 4.8.1 |  34.76 ns | 0.477 ns |  1.00
| IsWithCast_ValueType | .NET Framework 4.8.1 |  34.74 ns | 0.776 ns |  1.00
|===

==== Glossary

* https://en.wikipedia.org/wiki/Arithmetic_mean[Mean]
* https://en.wikipedia.org/wiki/Standard_deviation[Standard Deviation]

The results were generated by running the following snippet with https://github.com/dotnet/BenchmarkDotNet[BenchmarkDotNet]:

[source,csharp]
----
private Random random = new Random(1);

private object ReturnSometimes<T>() where T : new() =>
    random.Next(5) switch
    {
        0 => new T(),
        1 => new object(),
        2 => new A(),
        3 => new B(),
        4 => new C(),
    };

[BenchmarkCategory("ValueType"), Benchmark(Baseline = true)]
public int IsPattern_ValueType()
{
    var i = ReturnSometimes<int>();
    return i is int d
        ? d
        : default;
}

[BenchmarkCategory("ValueType"), Benchmark]
public int IsWithCast_ValueType()
{
    var i = ReturnSometimes<int>();
    return i is int
        ? (int)i
        : default;
}

[BenchmarkCategory("Class"), Benchmark(Baseline = true)]
public DuplicateCasts IsPattern_Class()
{
    var i = ReturnSometimes<DuplicateCasts>();
    return i is DuplicateCasts d
        ? d
        : default;
}

[BenchmarkCategory("Class"), Benchmark]
public DuplicateCasts IsWithCast_Class()
{
    var i = ReturnSometimes<DuplicateCasts>();
    return i is DuplicateCasts
        ? (DuplicateCasts)i
        : default;
}

[BenchmarkCategory("Interface"), Benchmark(Baseline = true)]
public IReadOnlyList<int> IsPattern_Interface()
{
    var i = ReturnSometimes<List<int>>();
    return i is IReadOnlyList<int> d
        ? d
        : default;
}

[BenchmarkCategory("Interface"), Benchmark]
public IReadOnlyList<int> IsWithCast_Interface()
{
    var i = ReturnSometimes<List<int>>();
    return i is IReadOnlyList<int>
        ? (IReadOnlyList<int>)i
        : default;
}
----

Hardware configuration:

[source]
----
BenchmarkDotNet v0.14.0, Windows 10 (10.0.19045.5247/22H2/2022Update)
Intel Core Ultra 7 165H, 1 CPU, 22 logical and 16 physical cores
  [Host]               : .NET Framework 4.8.1 (4.8.9282.0), X64 RyuJIT VectorSize=256
  .NET 9.0             : .NET 9.0.0 (9.0.24.52809), X64 RyuJIT AVX2
  .NET Framework 4.8.1 : .NET Framework 4.8.1 (4.8.9282.0), X64 RyuJIT VectorSize=256
----

include::../rspecator.adoc[]
