include::../../summary.adoc[]

== Why is this an issue?

include::../../rationale.adoc[]

include::../../impact.adoc[]

include::../../threats.adoc[]

== How to fix it?

The following code is vulnerable to cross-site scripting because auto-escaping of special HTML characters has been disabled. The recommended way to fix this code is to move the HTML content to the template and to only inject the dynamic value. Therefore, it is not necessary to disable auto-escaping. 

[cols="a,a"]
|===
|
[source,python]
----
from flask import render_template

@app.route('/hello/<name>')
def hello(name=None):
    hello = f"<h1>Hello { name }</h1>"
    return render_template('hello.html', hello=hello)
----
|
[source,python]
----
from flask import render_template

@app.route('/hello/<name>')
def hello(name=None):
    return render_template('hello.html', name=name)
----
|
[source,html]
----
<!doctype html>
{% autoescape false %}
{{ hello }} <!-- Noncompliant -->
{% endautoescape %}
----
|
[source,html]
----
<!doctype html>
<h1>Hello {{ name }}</h1>
----
|===

=== How does this work?

Template engines are used by web applications to build HTML content. Template files contain static HTML as well as template language instructions. These instructions allow, for example, to insert dynamic values (variables) in the document as the template is rendered. Template engines can auto escape HTML special characters of variables in order to prevent XSS vulnerabilities.

In Flask applications, the Jinja auto-escaping feature is enabled by default. XSS vulnerabilities arise when an untrusted value is injected in the template and that auto-escaping is disabled using ``++{% autoescape false %}++`` or ``++|safe++`` filter. This is often the case when a piece of dynamic HTML is generated from the Python code and used in a template variable.

=== Pitfalls

Although auto-escaping drastically decreases the chance of introducing cross-site scripting vulnerabilities, there are still specific cases where vulnerabilities can occur.

==== Unquoted variables in attributes

If ``++color++`` is untrusted, JavaScript code can be injected by adding event-handler attributes like ``++onmouseover++``.

Surround the attribute with double or single quotes to prevent arbitrary attributes from being added.

[cols="a,a"]
|===
|
[source,html]
----
<!doctype html>
<span style={{color}}>...</span>
----
|
[source,html]
----
<!doctype html>
<span style="{{color}}">...</span>
----
|===

==== Variables in ``++href++`` attributes

If ``++url++`` is untrusted, JavaScript code can be injected by using an attributes value that starts with ``++javascript:++``.

Use function like ``++flask.url_for++`` to generate URLs used in ``++href++`` attributes

[cols="a,a"]
|===
|
[source,html]
----
<!doctype html>
<a href="{{url}}">...</a>
----
|
[source,html]
----
<!doctype html>
<a href="{{ url_for('index') }}">...</a>
----
|===

==== Variables in script blocks

If ``++name++`` is untrusted, JavaScript code can be injected.

Use ``++tojson++`` filter to insert a data structure in the JavaScript code at render time.

[cols="a,a"]
|===
|
[source,html]
----
<!doctype html>
<script> var name = '{{ name }}';</script>

----
|
[source,html]
----
<!doctype html>
<script> var name = {{ name \| tojson }}</script>
----
|===


Alternatively, you can insert the value in a data attribute.

[cols="a,a"]
|===
|
[source,html]
----
<!doctype html>
<script> var name = '{{ name }}'</script>
----
|
[source,html]
----
<!doctype html>
<script data-name="{{ name }}">...</script>.
----
|===

=== Going the extra mile

== Resources

=== Documentation

* https://jinja.palletsprojects.com/en/3.0.x/templates/[The Pallets Projects, Jinja, Template Designer Documentation]

include::../../common/resources/articles.adoc[]

include::../../common/resources/presentations.adoc[]

include::../../common/resources/standards.adoc[]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../../message.adoc[]

include::../../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
