gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]
 
env:
  CIRRUS_CLONE_DEPTH: 1
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash

container_definition: &CONTAINER_DEFINITION
  builder_image_project: language-team
  builder_image_name: docker-builder-lt-v1
  cluster_name: cirrus-ci-lt-cluster
  zone: us-central1-a
  namespace: default
  use_in_memory_disk: true

validate_asciidoc_task:
  gke_container:
    dockerfile: Dockerfile
    <<: *CONTAINER_DEFINITION   
    dockerfile: Dockerfile
    cpu: 1
    memory: 1G
  tests_script:
    - ./validate_asciidoc_and_metadata.sh

validate_links_task:
  timeout_in: 90m
  gke_container:
    dockerfile: Dockerfile
    <<: *CONTAINER_DEFINITION   
    dockerfile: Dockerfile
    cpu: 1
    memory: 1G
  tests_script:
    - validate_links.sh

