gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]
 
env:
  CIRRUS_CLONE_DEPTH: 1
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash

container_definition: &CONTAINER_DEFINITION
  builder_image_project: language-team
  builder_image_name: docker-builder-lt-v1
  cluster_name: cirrus-ci-lt-cluster
  zone: us-central1-a
  namespace: default
  use_in_memory_disk: true

tooling_tests_task:
  gke_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: Dockerfile
    cpu: 1
    memory: 1G
  env:
    PYTHONPATH: .
  tests_script:
    - cd rspec-tools
    - pipenv install -e .
    - pipenv run pip install pytest
    - pipenv run pytest 

frontend_tests_task:
  gke_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: ci/frontend-tests-dockerfile
    cpu: 1
    memory: 2G
  node_modules_cache:
    folder: frontend/node_modules
    reupload_on_changes: false # since there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS
      - node --version
      - cat frontend/package-lock.json
    populate_script:
      - cd frontend
      - npm install
  tests_script:
    - cd frontend
    - npm run build
    - npm test

validate_asciidoc_task:
  gke_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: Dockerfile
    cpu: 1
    memory: 1G
  metadata_tests_script:
    - ./validate_metadata.sh
  asciidoc_tests_script:
    - ./validate_asciidoc.sh

validate_links_task:
  timeout_in: 120m
  gke_container:
    <<: *CONTAINER_DEFINITION
    dockerfile: Dockerfile
    cpu: 1
    memory: 2G
  env:
    LINK_CACHE_NAME: link-probing-status
    LINK_CACHE_PATH: /root/link-probing-history.cache
  tests_script:
    - bash ci/cirrus-cache.sh download ${LINK_CACHE_NAME} ${LINK_CACHE_PATH}
    - ./validate_links.sh ${LINK_CACHE_PATH}
    - bash ci/cirrus-cache.sh upload ${LINK_CACHE_NAME} ${LINK_CACHE_PATH}

