gcp_credentials: ENCRYPTED[!17c59813193e86cc337bce848b358412b90f50bc5fe1b8b39d363cdf14a41ebe76cfba0482e7f81d076994b9f6dbfb4c!]
env:
  #github
  GITHUB_TOKEN: ENCRYPTED[!f458126aa9ed2ac526f220c5acb51dd9cc255726b34761a56fc78d4294c11089502a882888cef0ca7dd4085e72e611a5!]
 
env:
  CIRRUS_CLONE_DEPTH: 1
  # Use bash (instead of sh on linux or cmd.exe on windows)
  CIRRUS_SHELL: bash

container_definition: &CONTAINER_DEFINITION
  builder_image_project: language-team
  builder_image_name: docker-builder-lt-v1
  cluster_name: cirrus-ci-lt-cluster
  zone: us-central1-a
  namespace: default
  use_in_memory_disk: true

update_rule_coverage_task:
  gke_container:
    <<: *CONTAINER_DEFINITION   
    dockerfile: Dockerfile
    cpu: 1
    memory: 2G
  env:
    PYTHONPATH: .
  set_up_script:
    - source cirrus-env BUILD-PRIVATE
    - git config --global user.email "sonartech@sonarsource.com"
    - git config --global user.name "sonartech"
  install_script:
    - git clone --branch master --depth 1 https://${GITHUB_TOKEN}@github.com/SonarSource/rspec
    - cd rspec/rule_coverage
    - pipenv install
    - cd ../..
  update_coverage_script:
    - cd rspec/rule_coverage
    - pipenv run python coverage.py batchall
    - mv covered_rules.json ../frontend/public/covered_rules.json
    - cd ../..
  push_script:
    - cd rspec
    - git add frontend/public/covered_rules.json
    - git diff-index --quiet HEAD || git commit -m "Nightly coverage update"
    - git push
    - cd ..

