== Why is this an issue?

A cast is an https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/casting-and-type-conversions#explicit-conversions[explicit conversion], in other words, this is a way to tell the compiler the intent to convert from a type to another.

[source,csharp]
----
float x = 0.5f;
int i = (int)x;                   // Casting (explicit conversion) from float to int
----

In most cases, the compiler will be able to catch inappropriate casts between incompatible value types or reference types.

However, the compiler will not be able to detect inappropriate casts to interfaces.

This rule applies also to the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#is-operator[`is` operator] when used for type-testing.

[source,csharp]
----
object b = new Base();
Console.WriteLine(b is Base);     // Type-testing using the is operator
----

=== What is the potential impact?

Inappropriate casts will lead to unexpected behaviors or runtime errors such as https://learn.microsoft.com/en-us/dotnet/api/system.invalidcastexception[`InvalidCastException`].

=== Exceptions

No issue is reported if the interface has no implementing class in the assembly.

== How to fix it

To prevent an https://learn.microsoft.com/en-us/dotnet/api/system.invalidcastexception[`InvalidCastException`] from raising during an explicit conversion, it is recommended to use the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#as-operator[`as` operator].
When the conversion is not possible, the `as` operator returns `null` and will never raise an exception.

=== Code examples

==== Noncompliant code example

[source,csharp,diff-id=1,diff-type=noncompliant]
----
public interface IMyInterface
{ /* ... */ }

public class Implementer : IMyInterface
{ /* ... */ }

public class OrphanClass
{ /* ... */ }

public static class Program
{
  public static void Main()
  {
    var orphan = new OrphanClass();
    var x = (IMyInterface) orphan;     // Noncompliant: InvalidCastException is being thrown
  }
}
----

==== Compliant solution

[source,csharp,diff-id=1,diff-type=compliant]
----
public interface IMyInterface
{ /* ... */ }

public class Implementer : IMyInterface
{ /* ... */ }

public class OrphanClass
{ /* ... */ }

public static class Program
{
  public static void Main()
  {
    var orphan = new OrphanClass();
    var x = orphan as IMyInterface;    // Compliant: but will always be null
    var b = false;
  }
}
----

== Resources

=== Documentation

* https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/types/casting-and-type-conversions#explicit-conversions[Casting and type conversions - Explicit conversion]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast[Type-testing operators and cast expressions]
** https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#is-operator[`is` operator]
** https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#as-operator[`as` operator]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#103-explicit-conversions[Conversions - Explicit conversions in C#]
** https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#1035-explicit-reference-conversions[Conversions - Explicit reference conversions in C#]
* https://cwe.mitre.org/data/definitions/588[MITRE, CWE-588 - Attempt to Access Child of a Non-structure Pointer]
* https://cwe.mitre.org/data/definitions/704[MITRE, CWE-704 - Incorrect Type Conversion or Cast]

include::../rspecator-dotnet.adoc[]
