=== On 2015-06-19T13:59:23Z Elena Vilchik Wrote:
\[~ann.campbell.2] What about less strict raising issue?

 "This rule raises an issue when the function that defines the operation of a custom operator consists of something other than a single *return statement*." 

(we don't care about return value expression)

=== On 2015-06-19T15:42:20Z Ann Campbell Wrote:
That's up to you [~elena.vilchik], but if the point of the rule is to off-load the logic into another function for flexibility, then people can get around the rule if they can cram all the functionality into a single line without actually fulfilling the purpose. E.G. 

----
  return (( (left % 1) * 100) + ((left - ( (left % 1) * 100)) / 100)) * (((right % 1) * 100) + ((right - ((right % 1) * 100)) / 100))
----



=== On 2015-06-19T15:46:16Z Elena Vilchik Wrote:
\[~ann.campbell.2] do you have nothing else to do?))

Ok, let's keep it as it is :)

=== On 2015-06-24T09:26:05Z Elena Vilchik Wrote:
\[~ann.campbell.2] I've added exception and removed all mentioning of "custom" as this rule is about all operator functions. Could you verify?

=== On 2015-06-24T13:49:29Z Ann Campbell Wrote:
I've made some minor edits [~elena.vilchik]. Double-check me, please.

