=== Deprecate: RSPEC-1538

=== Duplicate: RSPEC-894

=== Duplicate: RSPEC-901

=== Related: RSPEC-902

=== Related: RSPEC-897

=== Related: RSPEC-905

=== Related: RSPEC-1029

=== Related: RSPEC-1116

=== Related: RSPEC-1172

=== Related: RSPEC-1751

=== Related: RSPEC-1854

=== Related: RSPEC-1862

=== Related: RSPEC-1879

=== Related: RSPEC-5918

=== Relates: RSPEC-1475

=== On 2014-06-25T10:10:31Z Evgeny Mandrikov Wrote:
Not applicable for Java - JLS7 14.21. Unreachable Statements:

____
It is a compile-time error if a statement cannot be executed because it is unreachable.

____

=== On 2015-02-02T14:28:04Z Freddy Mallet Wrote:
@Ann, I  would link this rule to CWE-561: \http://cwe.mitre.org/data/definitions/561.html and would slightly update the issue message : 


"Remove the unreachable code after this "XXX" statement."

=== On 2015-02-02T14:55:13Z Ann Campbell Wrote:
I added the reference, but I didn't update the message. The addition of the modifier "unreachable" implies that there is reachable code after the jump statement & there's not; it's all unreachable.

=== On 2020-11-03T14:55:21.851Z Nicolas Harraudeau Wrote:
Note that this rule has different implementations and ways to highlight code.


New analyzers should have their primary location on the first line of dead code so that the location doesn't change if/when a CFG is added later on.


=== SLANG [go/kotlin/scala/ruby/apex] and swift

The rule detects simple cases where a single return/throw/... is followed by dead code.


Primary location on the return/throw/... statement exiting the flow.


=== Python/PHP

This is the preferred way as it detects more issues, but it requires a CFG.


The rule is able to detect complex cases where multiple branches exit before the dead code is reached. Example: dead code after an ``++if-else++`` block which has a ``++return++`` in each branch.


Primary location on the first line of dead code.

Secondaries on every statement exiting the code block.


=== TSQL

The rule detects simple cases where a single return/throw/... is followed by dead code.

Primary location on the first line of dead code.


=== CFamily

it is based on CLANG and detects far more use cases of dead code.



