== Why is this an issue?

This rule reports the methods of React component classes that are neither used nor React lifecycle methods. 

This rule checks only usages of the method inside the scope of a component class. It will also raise an issue if the method is only used outside the class. React encourages data-driven components. To modify a child component, re-render it with new `props`, instead of calling internal methods from outside the component.

[source,javascript,diff-id=1,diff-type=noncompliant]
----
class Profile extends React.Component {
  render(props) {
    return <h1>{ props.name }</h1>;
  }

  getDefaultName() { // Noncompliant, this method is never used and is a dead code
    return 'John Smith';
  }
}
----

Methods that are never executed are dead code and should be removed. Cleaning out dead code decreases the size of the maintained codebase, making it easier to understand the program and preventing bugs from being introduced.

[source,javascript,diff-id=1,diff-type=compliant]
----
class Profile extends React.Component {
  render(props) {
    return <h1>{ props.name || getDefaultName() }</h1>;
  }

  getDefaultName() {
    return 'John Smith';
  }
}
----

== Resources

* https://reactjs.org/docs/components-and-props.html[React Documentation - Components and Props]
* https://legacy.reactjs.org/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class[React Documentation - ]