=== On 2013-12-20T13:57:02Z Dinesh Bolkensteyn Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-417

=== On 2014-01-04T17:22:21Z Ann Campbell Wrote:
Sorry for the delay on this one, [~dinesh.bolkensteyn]. Somehow I missed the assignment notification.

=== On 2014-01-07T10:26:02Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3359 in JavaScript

=== On 2014-02-12T20:54:41Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3459 for PHP

=== On 2014-03-03T11:50:44Z Dinesh Bolkensteyn Wrote:
\[~ann.campbell.2] IMO we should follow the commonly accepted standards of each language in our examples. So in .NET languages, curly braces start on a new line, and method names start with an upper case letter.

=== On 2014-03-03T12:56:24Z Ann Campbell Wrote:
I agree [~dinesh.bolkensteyn] & transgressed out of ignorance. But I think you'll find people to argue vehemently on either side of the curly brace question for any given language... 

=== On 2014-04-25T13:25:59Z Ann Campbell Wrote:
This rule is not appropriate for VB6. 

