The Security Assertion Markup Language (SAML) is a widely used standard in single sign-on systems. In a simplified version, the user authenticates to an Identity Provider which generates a signed SAML Response. This response is then forwarded to a Service Provider for validation and authentication.

== Why is this an issue?

By exploiting this vulnerability, an attacker can manipulate the SAML Response to impersonate a different user.

=== Unauthorized Access

Exploiting this vulnerability allows an attacker with authenticated access to impersonate other users within the SAML-based SSO system. This can lead to unauthorized access to sensitive information, resources, or functionalities that the attacker should not have. By masquerading as legitimate users, the attacker can bypass authentication mechanisms and gain unauthorized privileges, potentially compromising the entire system. By impersonating a user with higher privileges, the attacker can gain access to additional resources. Privilege escalation can lead to further compromise of other systems, and unauthorized access to critical infrastructure.

=== Data Breaches

With the ability to impersonate other users, an attacker can gain access to sensitive data stored within the SAML-based SSO system. This includes personally identifiable information (PII), financial data, intellectual property, or any other confidential information. Data breaches can result in reputational damage, legal consequences, financial losses, and harm to individuals whose data is exposed.


== How to fix it in Java EE

=== Code examples

In the following examples, an attacker is able to change the field identifying the authenticated user with XML comments. To prevent this vulnerability on application using Spring Security SAML relying on OpenSAML2, XML comments should not be ignored by setting the property ``++ignoreComments++`` to ``++false++``.

==== Noncompliant code example

[source,java,diff-id=1,diff-type=noncompliant]
----
import org.opensaml.xml.parse.BasicParserPool;
import org.opensaml.xml.parse.ParserPool;
import org.opensaml.xml.parse.StaticBasicParserPool;

public ParserPool parserPool() {
  StaticBasicParserPool staticBasicParserPool = new StaticBasicParserPool();
  staticBasicParserPool.setIgnoreComments(false); // Noncompliant
  return staticBasicParserPool;
}
----

[source,java,diff-id=2,diff-type=noncompliant]
----
public ParserPool parserPool() {
  BasicParserPool basicParserPool = new BasicParserPool();
  basicParserPool.setIgnoreComments(false); // Noncompliant
  return basicParserPool;
}
----

==== Compliant solution

[source,java,diff-id=1,diff-type=compliant]
----
public ParserPool parserPool() {
  return new StaticBasicParserPool();
}
----

[source,java,diff-id=2,diff-type=compliant]
----
public ParserPool parserPool() {
  return new BasicParserPool();
}
----

=== How does this work?

An attacker having access to an Identity Provider with his account ``admin@domain.com.evil.com``, specially crafted for this attack, will receive a signed response such as:

----
<SAMLResponse>
  [...]
  <Assertion ID="_id1234">
    <Subject>
      <NameID>admin@domain.com.evil.com</NameID>
    </Subject>
  </Assertion>
  <Signature>
    [...]
  </Signature>
  [...]
</SAMLResponse>
----

In most cases, when computing a signature, the XML data is transformed by a process called XML canonicalization. This process removes XML comments. As a consequence, the attacker can add comments to the response without invalidating the signature:

----
<SAMLResponse>
  [...]
  <Assertion ID="_id1234">
    <Subject>
      <NameID>admin@domain.com<!---->.evil.com</NameID>
    </Subject>
  </Assertion>
  <Signature>
    [...]
  </Signature>
  [...]
</SAMLResponse>
----

The Service Provider decodes the content of the ``NameID`` field using an XML parser. Depending on the parser used, the Service Provider may wrongly stop at the beginning of the comment and use only the substring ``admin@domain.com`` for the authentication. In such case, the attacker with account ``admin@domain.com.evil.com`` impersonates successfully another account ``admin@domain.com``. To prevent this vulnerability, XML comments should be ignored when parsing the content of the ``NameID`` field.


== Resources

=== Documentation

* OpenSAML API - https://javadoc.io/doc/org.opensaml/xmltooling/latest/org/opensaml/xml/parse/BasicParserPool.html[Class BasicParserPool]
* OpenSAML API - https://javadoc.io/doc/org.opensaml/xmltooling/latest/org/opensaml/xml/parse/StaticBasicParserPool.html[Class StaticBasicParserPool]
* https://www.w3.org/TR/xml-c14n11/[Canonical XML Version 1.1]
* https://www.w3.org/TR/xmldsig-core1/[XML Signature Syntax and Processing Version 1.1]

=== Articles & blog posts

* https://owasp.org/www-project-top-ten/2017/A9_2017-Using_Components_with_Known_Vulnerabilities[OWASP Top 10 2017 Category A9] - Using Components with Known Vulnerabilities
* https://duo.com/blog/duo-finds-saml-vulnerabilities-affecting-multiple-implementations[Duo Finds SAML Vulnerabilities Affecting Multiple Implementations]
* https://spring.io/blog/2018/03/01/spring-security-saml-and-this-week-s-saml-vulnerability[Spring Security SAML and this week's SAML Vulnerability]
* https://github.com/spring-projects/spring-security-saml/issues/228[Spring Security SAML: Issue #228]

* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-11427[CVE-2017-11427]
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-11428[CVE-2017-11428]
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-11429[CVE-2017-11429]
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-11430[CVE-2017-11430]
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-0489[CVE-2018-0489]
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-7340[CVE-2018-7340]

== Standards

* https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/[OWASP Top 10 2021 Category A6] - Vulnerable and Outdated Components
* https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/[OWASP Top 10 2021 Category A7] - Identification and Authentication Failures
* https://owasp.org/www-project-top-ten/2017/A2_2017-Broken_Authentication[OWASP Top 10 2017 Category A2] - Broken Authentication


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Change "setIgnoreComments" to "true" or remove the call to "setIgnoreComments" to prevent the authentication bypass.


=== Highlighting

setIgnoreComments(false)


endif::env-github,rspecator-view[]
