include::../../summary.adoc[]

== Why is this an issue?

include::../../rationale.adoc[]

include::../../impact.adoc[]

include::../../threats.adoc[]

== How to fix it?

include::../../common/fix/intro.adoc[]

include::../../common/fix/data_encoding.adoc[]

==== In an MVC or MVVM context

To prevent cross-site scripting directly from code, two concepts are worth mentioning:

First, that the compiler considers `IHtmlContent` to be a developer-defined HTML content. This means that:

* Razor does not HTML-encode it at runtime to avoid double-encoding.
* Any data that is not programmatically HTML encoded before being sent to Razor is unsafe.

Second, the HTML, JavaScript and URL encoders are available to the C# code in two ways:

* Via dependency injection
* Via the `System.Text.Encodings.Web` namespace

The return type of the encoders is a string.

[source,csharp]
----
public class ViewModel 
{
    public string ThirdPartyString     { get; private set; }
    public IHtmlContent ThirdPartyHtml { get; private set; }

    public ViewModel(string thirdPartyData)
    {
        this.ThirdPartyString = thirdPartyData;
        this.ThirdPartyHtml   = new HtmlString(thirdPartyData); // NonCompliant
    }
}
----

[source,csharp]
----
public class ViewModel 
{
    public string       CleanThirdPartyString { get; private set; }
    public IHtmlContent CleanThirdPartyHtml   { get; private set; }

    public ViewModel(string thirdPartyData, HtmlEncoder htmlEncoder)
    {
        thirdPartyData             = htmlEncoder(thirdPartyData);
        this.CleanThirdPartyString = thirdPartyData;
        this.CleanThirdPartyHtml   = new HtmlString(thirdPartyData);
    }
}
----

==== In the Razor View

To prevent cross-site scripting from a Razor view, it is especially important to identify what types of input are being sent from the underlying C# code:

* `IHtmlContent` is considered by the runtime environment to be a developer-defined HTML content. This means that:
** Razor does not HTML-encode it at runtime to avoid double-encoding.
** Any data that is not programmatically HTML encoded before being sent to Razor is unsafe.
* `string` variables are automatically encoded by Razor if they are included with the default `@variable` notation.


Two Razor functions are to be avoided:

* `@Html.Raw(any)`: This function returns `IHTMLString`, which is not encoded because it is an `IHtmlContent`.
* `@{ Output.Write(Model.ThirdPartyString); }`: This function uses `Razor` 's internal raw `TextWriter`, which does not perform any transformations, such as encoding.

Finally, if `IHtmlContent` actually needs to be used by the Razor view, the `@Html.Encode()` function will make the content harmless. 

*Note*: This section applies to all data passed to a Razor view, including global objects such as:

* `ViewData`
* `ViewBag`
* `TempData`
* `Context` (`HttpContext`)


[source,html]
----
@*
    // Code sent to the Razor View
  
    IHtmlContent   ThirdPartyHtml;
    string         ThirdPartyString;
*@

@Model.ThirdPartyHtml @* Noncompliant *@

@Html.Raw(Model.ThirdPartyString) @* Noncompliant *@

@{ Output.Write(Model.ThirdPartyString); } @* Noncompliant *@

@ViewData["ThirdPartyHtml"]   @* Noncompliant *@
@Html.Raw(ViewData["ThirdPartyString"]) @* Noncompliant *@
@Html.Raw(ViewBag.ThirdPartyString) @* Noncompliant *@

@{
    object thirdPartyObject = ViewBag.ThirdPartyString;
    string thirdPartyString = ViewBag.ThirdPartyString as string;
}
@Html.Raw(thirdPartyObject) @* Noncompliant *@
@thirdPartyObject @* Noncompliant
----

[source,html]
----
@*
    // Code sent to the Razor View
  
    IHtmlContent ThirdPartyHtml;
    string       ThirdPartyString;

    IHtmlContent CleanThirdPartyHtml   = new HtmlString(HTMLEncoder.Encode(ThirdPartyString));
    string       CleanThirdPartyString = HTMLEncoder.Encode(ThirdPartyString);
*@

@Html.Encode(Model.ThirdPartyHtml)

@Model.ThirdPartyString 

@Model.CleanThirdPartyHtml

@Html.Raw(Model.CleanThirdPartyString)   

@{ Output.Write(Model.CleanThirdPartyString); }

@ViewData["ThirdPartyString"] 
@Html.Raw(ViewBag.CleanThirdPartyString)

@{
    object thirdPartyObject = ViewBag.ThirdPartyString; // Value is read from ViewBagAll argument => can cause FP
    string thirdPartyString = ViewBag.ThirdPartyString as string;
}
@thirdPartyString 
----

==== Special Cases

Note: Including third-party data in special Razor form tags is considered safe
for some of them:

* The `asp-route-{value}` attribute is automatically encoded by the runtime, with the `BeginWriteTagHelperAttribute()` function.
* HTML Attributes are automatically encoded by the runtime, with the `AddHtmlAttributeValue()` function.


=== Pitfalls

include::../../common/pitfalls/deny-lists.adoc[]

If the application needs to handle rich content, the preferred option is to use
Markdown in conjunction with a parser that removes embedded HTML.

By removing embedded HTML and leaving the generation of HTML to internal
code, validation and sanitization help prevent third-party tampering.

=== Going the extra mile

include::../../common/extra-mile/csp.adoc[]

:blazor-csps: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/content-security-policy?view=aspnetcore-6.0
:aspdotnet-core-middleware: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0
:csp-nonces-owin: https://vcsjones.dev/content-security-policy-nonces-in-asp-net-and-owin/

Implementing content security policies differs from one architecture to another.

When client-side code is processed by Blazor::
* {blazor-csps}[the library supports it by default].
When CSP requirements are low::
* {aspdotnet-core-middleware}[the ASP.Net Core Middleware provides header control].
When code requirements enforce optimal CSP, including content security policies nonces::
* The Open Web Interface for . NET (OWIN) {csp-nonces-owin}[can be used for a simple implementation].


include::../../common/resources/docs.adoc[]
* https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-6.0[Microsoft, Prevent Cross-Site Scripting (XSS) in ASP.NET Core]

include::../../common/resources/articles.adoc[]
* https://vcsjones.dev/content-security-policy-nonces-in-asp-net-and-owin/[vcsjones.dev, Content-Security-Policy Nonces in ASP.NET and OWIN]
* http://owin.org/[owin.org, OWIN - Open Web Interface for .NET]

include::../../common/resources/presentations.adoc[]

include::../../common/resources/standards.adoc[]


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../../message.adoc[]

include::../../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
