== Why is this an issue?

If the names are ambiguous, the compiler should report the name clash and not generate arbitrary or unexpectedly resolved code. However, this ambiguity may not be obvious to a developer.


There is also a specific concern that if the member function is virtual, resolving the ambiguity by explicitly referencing the base class in effect removes the virtual behaviour from the function.


=== Noncompliant code example

[source,cpp]
----
class B1
{
public:
 int32_t count; // Noncompliant
 void foo ( ); // Noncompliant
};

class B2
{
public:
  int32_t count; // Noncompliant
  void foo ( ); // Noncompliant
};

class D : public B1, public B2
{
public:
  void Bar ( )
  {
    ++count; // Is that B1::count or B2::count?
    foo ( ); // Is that B1::foo() or B2::foo()?
  }
};
----


=== Exceptions

For the purposes of this rule, visible function identifiers that form an overload set shall be considered as the same entity.


== Resources

* MISRA {cpp}:2008, 10-2-1 - All accessible entity names within a multiple inheritance hierarchy should be unique.


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

"xxx" defined in "yyy" clashes with definition in "zzz" in "filename" on line "line" and should be renamed.


'''
== Comments And Links
(visible only on this page)

=== relates to: S1015

=== relates to: S808

=== on 21 Oct 2014, 19:05:20 Ann Campbell wrote:
\[~samuel.mercier] this message is written as thought it's not going to be sitting right under the duplicatively named entity...

=== on 24 Oct 2014, 08:07:28 Samuel Mercier wrote:
\[~ann.campbell.2] I sightly updated the message. Taking our example I think we want to flag the issue on the declarations in B2 with a reference on the declarations in B1 that are hidden.

So that would give :

"count" defined in "B2" clashes with definition in "B1" in file "file" on line 4

Ideally we probably want to drop the reference to the file/line and replace it with the ability to jump to that position from the issue.

=== on 7 Apr 2015, 22:47:10 Evgeny Mandrikov wrote:
\[~samuel.mercier] Given example violates rules of "Member name lookup" (CPP03-CPP11 10.2), exactly because it is ambiguous. So I'm wondering - is there a compiler, which will accept such code? or can this code be changed in a way that will be accepted by compiler, but still violate this rule?

=== on 13 Apr 2015, 12:03:11 Samuel Mercier wrote:
\[~evgeny.mandrikov] The example was taken from MISRA verbatim, and you are right, it does not compile... From there I cannot understand what is the rule about, especially since the title explicitly mention multiple inheritance.


We can take the given code without implementation of method Bar in D. In that case the code compiles and we can report issues on fields count and method foo, since they are ambiguous in the hierarchy, but IMO this has very little value.


I would vote to close it.

endif::env-github,rspecator-view[]
