== Why is this an issue?

This rule is a strict implementation of a MISRA (Motor Industry Software Reliability Association) rule. MISRA defines best practices for developing safety-critical software. You can learn more about this rule in the MISRA documents referenced below.


If you are not concerned with MISRA compliance or with safety-critical software, you might consider using rule S867 instead ; it targets the same kind of issue for general-purpose software.


== Resources

* MISRA {cpp} 2008, 5-0-14 - The first operand of a conditional-operator shall have type bool.


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Use a relational operator to convert the condition to type "bool".


'''
== Comments And Links
(visible only on this page)

=== is related to: S867

=== on 16 Oct 2014, 12:57:45 Ann Campbell wrote:
\[~samuel.mercier] please:

* fill in the appropriate reference field(s).
* provide a See section.
* use the standard section titles

=== on 22 Jan 2019, 11:41:03 Loïc Joly wrote:
See comment bellow RSPEC-883

endif::env-github,rspecator-view[]
