=== relates to: S1144

=== is related to: S3985

=== relates to: S895

=== on 15 Oct 2013, 08:45:25 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-358

=== on 16 Oct 2013, 23:52:16 Ann Campbell wrote:
I've added Compliant Solutions, but someone should double-check my guess at PL/SQL

=== on 22 Oct 2013, 14:45:38 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3195 in Flex

=== on 9 Dec 2013, 08:37:03 Dinesh Bolkensteyn wrote:
The PL/SQL case is not a field, but just a local variable (for which we have another rule, I'll remove it for now.

=== on 9 Dec 2013, 08:45:12 Dinesh Bolkensteyn wrote:
I guess that we need to allow any annotated private field? - in fact perhaps not, I can imagine that some private fields are injected, but read from outside?

=== on 23 Feb 2014, 22:51:34 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3505 for PHP

=== on 10 Mar 2017, 14:32:45 Ann Campbell wrote:
Irrelevant for C# because fields are covered in the language's implementation of RSPEC-1144

=== on 5 Nov 2019, 10:54:34 Nicolas Harraudeau wrote:
Python fields only exist once they are set. Thus RSPEC-4487 is more appropriate.

