=== What is the potential impact?

Using AES with CBC (Cipher Block Chaining) or ECB (Electronic Codebook) mode
instead of GCM (Galois/Counter Mode) can lead to a loss of authenticity: +
CBC and ECB modes do not provide data authenticity, meaning they do not protect
against tampering.

In addition, these two modes raise performance issues: CBC mode requires
sequential processing and is therefore less suitable for parallel execution,
while the GCM mode can take advantage of parallelization for improved
performance.

Using RSA with a padding scheme other than OAEP (Optimal Asymmetric Encryption
Padding) also weakens the protected data against attacks:. +
OAEP padding, which is specifically designed for RSA encryption, provides
improved security properties compared to other padding schemes. It includes
randomness and a secure hash function to increase the security of the
encryption and protect against chosen ciphertext attacks.

Below are some real-world scenarios that illustrate some impacts of an attacker
exploiting the vulnerability.

==== Theft of sensitive data

The encrypted message might contain data that is considered sensitive and
should not be known to third parties.

By using a weak algorithm the likelihood that an attacker might be able to
recover the cleartext drastically increases.

==== Additional attack surface

By modifying the cleartext of the encrypted message it might be possible for an
attacker to trigger other vulnerabilities in the code. Encrypted values are
often considered trusted, since under normal circumstances it would not be
possible for a third party to modify them.
