=== On 2016-02-04T14:22:16Z Ann Campbell Wrote:
\[~elena.vilchik], why set this to 20min? Since it will be assessed per function, not per class, the shorter time seems more appropriate to me.

=== On 2016-02-04T14:43:09Z Elena Vilchik Wrote:
\[~ann.campbell.2] Indeed, I've not thought about that

=== On 2016-02-04T18:02:27Z Ann Campbell Wrote:
BTW [~elena.vilchik], I will understand if you want me to tone down the language of this description.

=== On 2016-02-05T15:54:26Z Elena Vilchik Wrote:
\[~ann.campbell.2] No, I like it :)

=== On 2016-02-25T13:48:11Z Pierre-Yves Nicolas Wrote:
On my side, I don't agree with the description. First, JavaScript did not support classes at all before ES2015: prototypes are not classes. Secondly, the biggest argument in favor of applying this rule is that people are much more used to class-based languages rather than prototype-based languages: that does not make prototype-based OOP a nightmare.


Please see \https://en.wikipedia.org/wiki/Prototype-based_programming.

=== On 2016-02-25T14:00:04Z Elena Vilchik Wrote:
\[~ann.campbell.2], ok, looks like PY is not so happy with this description as I, could you remove couple of "bad"s from it?:)

=== On 2016-02-25T15:36:55Z Ann Campbell Wrote:
How about now [~pierre-yves.nicolas] and [~elena.vilchik]?

=== On 2016-02-25T15:43:57Z Pierre-Yves Nicolas Wrote:
It's OK for me, thanks [~ann.campbell.2].

