== Why is this an issue?

Unintentional expensive copy should be avoided when using ``++auto++`` as a placeholder type.


When using ``++const auto++`` as a placeholder type, you might unintentionally forget to add an ampersand(``++&++``) after the ``++auto++`` keyword. This can silently create a pointless copy and possibly have a bad impact on the performance of your code depending on the size of the created object and its context.

For example, if it happens in a range-based for loop context, it is going to lead to creating as many useless objects as the size of the range.

This rule will detect a declaration of an unmodified local variable with expensive to copy type and ``++auto++`` as a placeholder type that is initialized with a non-temporary object.


=== Noncompliant code example

[source,cpp]
----
void printVec(const std::vector<std::string>& namesOfTheEntirePopulation) {
  for (const auto name : namesOfTheEntirePopulation) { // Noncompliant 
    std::cout << name;
  }
}

void ignore(const std::vector<std::string>& vec);
void ignoreAgain(const std::vector<std::string>& vec);

void ignore(VecWrapper vec) {
  const auto namesOfCPPHaters = vec.getNamesOfCPPHaters(); // Noncompliant 
  ignore(namesOfCPPHaters);
  ignoreAgain(namesOfCPPHaters);
}
----


=== Compliant solution

[source,cpp]
----
void modifyName(std::string& a);
void printVec(std::vector<std::string>& namesOfTheEntirePopulation) {
  for (const auto& name : namesOfTheEntirePopulation) { // Compliant
    std::cout << name;
  }

  for (auto name : namesOfTheEntirePopulation) { // Compliant: a copy is needed to avoid modifying the original list of names
    modifyName(name);
    std::cout << name;
  }
}

void ignore(const std::vector<std::string>& vec);
void ignoreAgain(const std::vector<std::string>& vec);

void ignore(VecWrapper vec) {
  const auto& namesOfCPPHaters = vec.getNamesOfCPPHaters(); // Compliant
  ignore(namesOfCPPHaters);
  ignoreAgain(namesOfCPPHaters);
}
----


ifdef::env-github,rspecator-view[]
'''
== Comments And Links
(visible only on this page)

=== on 21 Oct 2020, 13:58:09 Ann Campbell wrote:
Title & description currently talk about "expensive copy"... as though there's a "cheap copy" option...?

=== on 21 Oct 2020, 16:29:22 Abbas Sabra wrote:
Hello [~ann.campbell.2],


Yes, a copy is expensive or cheap based on the size of the copied object. So if the user is needlessly copying an integer this rule shouldn't raise an issue as it is a "cheap copy". If the user is copying namesOfTheEntirePopulation(as in the example) that is an "expensive copy" and the rule should trigger.

endif::env-github,rspecator-view[]
