=== is duplicated by: S821

=== is related to: S5319

=== relates to: S822

=== relates to: S1017

=== is related to: S829

=== is related to: S833

=== is related to: S926

=== is related to: S1047

=== on 19 Sep 2014, 16:04:44 Freddy Mallet wrote:
@Ann:

* The reference to the relating MISRAC-{cpp} rule 8-4-2 and not 8-4-1 if my understanding is correct.
* In the "Compliant Solution", "//noncompliant..." comments should be removed
* I would not mention API08-C, as this rule refer to something almost at the opposite -> parameters should not be named



=== on 19 Sep 2014, 16:06:01 Freddy Mallet wrote:
This rule can almost be associated to the SQALE "Logic Related Reliability" sub-caracteristic

=== on 24 Sep 2014, 14:48:00 Ann Campbell wrote:
\[~freddy.mallet] See what you think about "Conflicting" instead of "See also" in the references section.

=== on 31 Oct 2014, 09:26:25 Evgeny Mandrikov wrote:
Description should be updated to fully cover RSPEC-821, which is about MISRA C:2012, 8.3 and now marked as duplicate of this one.

=== on 08 June 2023, 17:00:00 Sebastien Marichal wrote:

During a LaYC sprint, I removed dummy implementations for the following language:

* cfamily
* java
* javascript

It is not implemented in the corresponding analyzer and there currently are no tickets open in order to do so.