== Why is this an issue?

With the exception of volatile variables, variables declared and used only once do not contribute to program computations. A use is either an assignment (explicit initialization) or a reference. 


These variables are essentially noise but their presence may indicate that the wrong variable has been used elsewhere. Missing statements contribute to this problem.


=== Noncompliant code example

[source,cpp]
----
const int16_t x = 19; // Compliant, initialized and read
const int16_t y = 21; // Noncompliant, initialized but never read

void usedonlyonce ( void )
{
  int16_t once_1 = 42; // Noncompliant, initialized but never read
  int16_t once_2;
  once_2 = x ; // Noncompliant, assigned but never read
}
----


== Resources

* MISRA {cpp}:2008, 0-1-4


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Remove the unused variable "xxx".


'''
== Comments And Links
(visible only on this page)

=== duplicates: S1481

=== on 21 Oct 2014, 18:12:15 Ann Campbell wrote:
\[~samuel.mercier] you may want to take another look at the message. How is the user to interpret an issue flagged on a line like this:

``++int i = 0, j = 2, k=3;++``

endif::env-github,rspecator-view[]
