== Why is this an issue?

Method/constructor references are more readable than lambdas in many situations, and are therefore often preferred.

However, method references are sometimes less concise than lambdas.
In such cases, it might be preferrable to keep the lambda for better readability.
Therefore, this rule only raises issues on lambda expressions that could be replaced by shorter method references.

Some examples include `null` checks, which can be replaced with references to the `Objects::isNull` and `Objects::nonNull` methods.
Casts can be replaced with `SomeClass.class::cast` and `instanceof` can be replaced with `SomeClass.class::isInstance`.

*Note*: Lambda expressions were introduced in Java 8, so this rule is automatically disabled when the project's `sonar.java.source` is lower than `8`.

=== Noncompliant code example

[source,java,diff-id=1,diff-type=noncompliant]
----
class A {
  void process(List<A> list) {
    list.stream()
      .filter(myListValue -> myListValue instanceof B) // Noncompliant
      .map(listValueToMap -> (B) listValueToMap) // Noncompliant
      .map(bValueToMap -> bValueToMap.<String>getObject()) // Noncompliant
      .forEach(o -> System.out.println(o)); // Noncompliant
  }
}

class B extends A {
  <T> T getObject() {
    return null;
  }
}
----


=== Compliant solution

[source,java,diff-id=1,diff-type=compliant]
----
class A {
  void process(List<A> list) {
    list.stream()
      .filter(B.class::isInstance)
      .map(B.class::cast)            // Note: keeping the lambda would also be compliant here, since it is shorter
      .map(B::<String>getObject)
      .forEach(System.out::println);
  }
}

class B extends A {
  <T> T getObject() {
    return null;
  }
}
----


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Replace this lambda with a method reference. [(sonar.java.source not set. Assuming 8 or greater.)]


'''
== Comments And Links
(visible only on this page)

=== is duplicated by: S2212

=== on 26 Feb 2014, 12:19:41 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-465

endif::env-github,rspecator-view[]
