== Why is this an issue?

Using wrapped primitive values in a ternary operator does not simply return one operand or the other based on the condition.
Instead, the primitive values are unboxed and coerced to a common type, which can result in a loss of precision when converting one operand from `int` to `float` or from `long` to `double`.

While this behavior is expected for arithmetic operations, it may be unexpected for the ternary operator.
To avoid confusion or unexpected behavior, cast to a compatible type explicitly.

== How to fix it

Cast one of both operands to a common supertype (e.g., `Number`) to prevent auto-unboxing and, thus, type coercion.
If type coercion was your intention here, clarify this by casting the operand that would be implicitly converted to the corresponding type explicitly.

=== Code examples

==== Noncompliant code example

[source,java,diff-id=1,diff-type=noncompliant]
----
Integer i = 123456789;
Float f = 1.0f;
Number n1 = condition ? i : f;        // Noncompliant, implicit conversion to float, n1 = 1.23456792E8
Number n3 = condition ? (int) i : f;  // Noncompliant, implicit conversion to float, n3 = 1.23456792E8
----

==== Compliant solution

[source,java,diff-id=1,diff-type=noncompliant]
----
Integer i = 123456789;
Float f = 1.0f;
Number n1 = condition ? (Number) i : f;  // Compliant, prevents implicit conversion, n = 123456789
Number n2 = condition ? i : (Number) f;  // Compliant, prevents implicit conversion, n = 123456789
Number n3 = condition ? (float) i : f;   // Compliant, explicit conversion to float, n3 = 1.23456792E8
----

==== Compliant solution

[source,java]
----
int i = 123456789;
float f = 1.0f;
Number n = condition ? i : f; // Compliant, n1 = 1.23456792E8, but i and f are no wrapped types
----

==== Compliant solution

[source,java]
----
Integer i = 123456789;
Float f = 1.0f;
Number n = condition ? (int) i : f; // Compliant, n1 = 1.23456792E8, bit (int) i is no wrapped type
----

== Resources

=== Documentation

* https://www.geeksforgeeks.org/coercion-in-java/[Coercion in Java]
* Auto Boxing / Unboxing
* Coercion in official Java docu
* Behavior of ternary operator in Java docu

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Add an explicit cast to match types of operands.


'''
== Comments And Links
(visible only on this page)

=== on 16 Feb 2015, 18:02:37 Michael Gumowski wrote:
Message changed, as the type of the ternary operation can not be resolved at the moment. Indicating the required cast is not yet possible. 

Moreover, other expressions than variables can be used as operand.

endif::env-github,rspecator-view[]
