== Why is this an issue?

Deprecation is a warning that a method has been superseded, and will eventually be removed. The deprecation period allows you to make a smooth transition away from the aging, soon-to-be-retired technology.


This rule raises an issue when any of the following methods is used:

* ``++.andSelf()++``
* ``++.context++``
* ``++.die()++``
* ``++.error()++``
* ``++jQuery.boxModel++``
* ``++jQuery.browser++``
* ``++jQuery.sub()++``
* ``++jQuery.support++``
* ``++.live()++``
* ``++.load()++``
* ``++.selector++``
* ``++.size()++``
* ``++.toggle()++``
* ``++.unload()++``


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Remove this use of "XXX", which is deprecated.


'''
== Comments And Links
(visible only on this page)

=== on 26 Mar 2015, 17:34:33 Linda Martin wrote:
\[~ann.campbell.2] Assigned for review and completion.



=== on 1 Nov 2019, 17:30:21 Elena Vilchik wrote:
See \https://github.com/SonarSource/SonarJS/issues/1698

endif::env-github,rspecator-view[]
