== Why is this an issue?

Some signed to unsigned conversions may lead to implementation-defined behavior. This behavior may not be consistent with developer expectations.


If you need to mix signed and unsigned types, you should make your intent explicit by using explicit casts and avoiding implicit casts.


This rule will detect implicit conversions that change the signedness.


=== Noncompliant code example

[source,cpp]
----
void f(int a) {
  unsigned int b = a; // Noncompliant
  int c = (a > 0) ? a : b; // Noncompliant  

  if (a > b) { // Noncompliant
    // ...
  }
}
----


=== Compliant solution

[source,cpp]
----
void f(int a) {
  unsigned int b = static_cast<unsigned int>(a); // Compliant
}
----


== Resources

* MISRA {cpp} 2008, 5-0-4
* https://wiki.sei.cmu.edu/confluence/x/U9YxBQ[CERT, INT31-C.] - Ensure that integer conversions do not result in lost or misinterpreted data


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

This implicit type conversion changes the signedness of "xxx".


'''
== Comments And Links
(visible only on this page)

=== is related to: S6183

=== is related to: S6214

=== relates to: S849

=== is related to: S842

=== is related to: S850

=== on 20 Oct 2014, 14:14:09 Ann Campbell wrote:
cc [~freddy.mallet]

=== on 20 Oct 2014, 14:16:45 Ann Campbell wrote:
\[~samuel.mercier] this message is too general. It needs to speak to the line of code being marked.


E.G. This (implicit|explicit) type conversion changes the signedness of "xxx".


They can read about the undefined behavior in the description. :-)

=== on 21 Oct 2014, 15:50:09 Samuel Mercier wrote:
Updated, though it might be hard to track the original name "xxx".

=== on 21 Oct 2014, 20:25:03 Ann Campbell wrote:
FYI [~samuel.mercier] I've stripped this out of the message:  "and may lead to implementation-defined behaviour". Because we need to watch width, I try to keep all the "why" text out of the message and pare it down to just what's wrong or what the remediation is.

endif::env-github,rspecator-view[]
