Linux \"``++capabilities++``" allow you to assign narrow slices of ``++root++``'s permissions to files or processes. A thread with capabilities bypasses the normal kernel security checks to execute high-privilege actions such as mounting a device to a directory, without requiring (additional) root privileges.


Granting capabilities can lead to privilege escalations. 


== Ask Yourself Whether

Capabilities are granted:

* To a process that does not require all capabilities to do its job.
* To a not trusted process.

There is a risk if you answered yes to any of those questions.


== Recommended Secure Coding Practices

Capabilities are high privileges, traditionally associated with superuser (root), thus make sure that the most restrictive and necessary capabilities are assigned to files and processes.


== Sensitive Code Example

When setting capabilities:

----
cap_t caps = cap_init();
cap_value_t cap_list[2];
cap_list[0] = CAP_FOWNER;
cap_list[1] = CAP_CHOWN;
cap_set_flag(caps, CAP_PERMITTED, 2, cap_list, CAP_SET);

cap_set_file("file", caps); // Sensitive
cap_set_fd(fd, caps); // Sensitive
cap_set_proc(caps); // Sensitive
capsetp(pid, caps); // Sensitive
capset(hdrp, datap); // Sensitive: is discouraged to be used because it is a system call
----

When setting SUID/SGID attributes:

----
chmod("file", S_ISUID|S_ISGID); // Sensitive
fchmod(fd, S_ISUID|S_ISGID); // Sensitive
----


== See

* https://www.owasp.org/index.php/Top_10-2017_A5-Broken_Access_Control[OWASP Top 10 2017 Category A5] - Broken Access Control
* https://cwe.mitre.org/data/definitions/250.html[CWE-250] - Execution with Unnecessary Privileges
* https://cwe.mitre.org/data/definitions/266.html[CWE-266] -  Incorrect Privilege Assignment
* https://forums.grsecurity.net/viewtopic.php?f=7&t=2522[False Boundaries and Arbitrary Code Execution]


ifdef::rspecator-view[]
== Comments And Links
(visible only on this page)

include::comments-and-links.adoc[]
endif::rspecator-view[]
