== Why is this an issue?

Instead of repeating prototypes in each module that uses a procedure, you should declare them in a ``++/COPY++`` member and simply include that member as appropriate. This keeps you from having to repeat the prototype over and over, which reduces the chance of errors, and makes maintenance easier if you ever need to update the prototype.


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Move this prototype to a "/COPY" member


'''
== Comments And Links
(visible only on this page)

=== on 2 Apr 2015, 19:12:19 Ann Campbell wrote:
http://www.bmeyers.net/faqs/14-tips/32-rpg-iv-style?start=2

=== on 16 Apr 2015, 10:37:09 Pierre-Yves Nicolas wrote:
This rule is only valid for exported procedures. Non-exported procedures are private to the module.

=== on 20 Apr 2015, 11:31:17 Ann Campbell wrote:
\[~pierre-yves.nicolas] does the description need to be updated somehow to reflect that? Or was your comment only a note-to-self for implementation time?

=== on 20 Apr 2015, 11:40:02 Pierre-Yves Nicolas wrote:
\[~ann.campbell.2] We probably don't need to update the description.

endif::env-github,rspecator-view[]
