== Why is this an issue?

Throwing an exception from a destructor may result in a call to ``std::terminate`` and can introduce undefined behavior, meaning that your program could be terminated abruptly without being allowed to perform a clean shutdown.

Destructors are usually (implicitly) declared as ``noexcept`` by default such that ``std::terminate`` is called when they throw an exception.
Destructors may still propagate an exception if they are explicitly declared as ``noexcept(false)``.
However, even a destructor that is declared as ``noexcept(false)`` will call ``std::terminate`` if it throws during stack unwinding.

A commonly used example that highlights the severity of the underlying problem is presented in what follows:
The destructor of a container needs to call the destructors for all managed objects.
Suppose a call to an object's destructor throws an exception.
In that case, there are only two _conceptual_ ways to proceed:

1. Abort destruction. This will result in a partially destroyed object and possibly many more objects whose destructor has not been called. 
2. Ignore the exception and proceed with destroying the remaining objects. However, this potentially results in more partially destroyed objects, if further destructors throw an exception.

Both of these options are undesired and hence, whenever an object that is managed using a C++ standard container throws an exception, the behavior is undefined. 

Thus, destructors should never ``++throw++`` exceptions.
Instead, they should catch and handle those thrown by the functions they call, and be ``++noexcept++``.


This rule raises an issue when a destructor is not ``++noexcept++``. By default, destructors are ``++noexcept++``, therefore most of the time, nothing needs to be written in the source code. A destructor is not ``++noexcept++`` if:

* the base class or a data member has a non ``++noexcept++`` destructor,
* the destructor is decorated with the ``++noexcept++`` keyword followed by something that evaluates to false.


=== Noncompliant code example

[source,cpp]
----
struct A {
  ~A() noexcept(false) {} // Noncompliant
};

struct C {
  /* ... */
  A a; // This member data prevents automatic declaration of the destructor as noexcept
  ~C() { // Noncompliant
    /* ... */
  }
};
----


=== Compliant solution

[source,cpp]
----
struct A {
  ~A() noexcept(true) {}
};

struct C {
  /* ... */
  A a;
  ~C() { // Compliant, noexcept by default
    /* ... */
  }
};
----


== Resources

* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#c36-a-destructor-may-not-fail[{cpp} Core Guidelines C.36] - A destructor may not fail
* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#c37-make-destructors-noexcept[{cpp} Core Guidelines C.37] - Make destructors noexcept


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::message.adoc[]

include::highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::comments-and-links.adoc[]
endif::env-github,rspecator-view[]
