=== On 2013-11-01T18:52:19Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-373

=== On 2013-11-03T09:55:33Z Ann Campbell Wrote:
The title and message for this rule are phrased as though the rule will NOT be flagged on the file in question. E.G. "Add the missing header *in file XXX*" rather than "Add the missing header to *this file*" ...?

=== On 2013-11-22T11:06:37Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3278 for Flex

=== On 2014-01-07T10:50:16Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3363 for JavaScript

=== On 2014-02-19T07:35:07Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3486 for PHP

=== On 2014-10-08T14:05:31Z Ann Campbell Wrote:
Note that some languages marked obsolete purely because the 'convention' tag was removed from this rule. If that tag had not yet been applied in the language, then the language isn't actually out of date.

=== On 2015-04-06T10:28:27Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] and why this is not considered as convention anymore?

=== On 2015-04-06T12:24:56Z Ann Campbell Wrote:
This was a bit of a compromise [~evgeny.mandrikov], but it comes down to the fact that the default severity is Blocker and it's a bit difficult to justify rating a "convention" above Minor.

=== On 2016-07-26T19:43:43Z Ann Campbell Wrote:
FYI [~freddy.mallet], I've marked this as a Finding.

