The Android SDK has built-in support for SQLite databases that can be used to store data persistently. The data is stored in clear text and thus an attacker with physical access to the device, for example when it gets stolen, can access it.


== Ask Yourself Whether

* The database contains sensitive data that could cause harm when leaked.

There is a risk if you answered yes to any of those questions.


== Recommended Secure Coding Practices

It's recommended to password-encrypt SQLite databases that contain sensitive information, for example with https://www.zetetic.net/sqlcipher/sqlcipher-for-android/[SQLCipher].

The password should not be hard-coded in the application. It can be provided by the user of the application or it can be fetched from a remote server.


== See

* https://mobile-security.gitbook.io/masvs/security-requirements/0x07-v2-data_storage_and_privacy_requirements[Mobile AppSec Verification Standard] - Data Storage and Privacy Requirements
* https://owasp.org/www-project-mobile-top-10/2016-risks/m2-insecure-data-storage[OWASP Mobile Top 10 2016 Category M2] - Insecure Data Storage
* https://www.owasp.org/index.php/Top_10-2017_A6-Security_Misconfiguration[OWASP Top 10 2017 Category A6] - Security Misconfiguration
* https://cwe.mitre.org/data/definitions/311.html[MITRE, CWE-311] - Missing Encryption of Sensitive Data

