=== On 2017-03-01T16:15:46Z Valeri Hristov Wrote:
\[~jeanchristophe.collet] I would suggest underlining the exception class name because we cannot always underline the access modifier. Consider a scenario where the exception class has a public modifier, but is a inner class of a partial internal class:

----
partial class MyClass
{
    public class MyException : Exception
    {
    }
}
----

{empty}...in another file...

----
internal partial class MyClass
{
}
----


=== On 2017-03-01T16:16:31Z Valeri Hristov Wrote:
also if a class does not have access modifier it is considered internal...

=== On 2017-03-06T17:39:33Z Jean-Christophe Collet Wrote:
https://msdn.microsoft.com/en-us/library/bb264484.aspx If I read that correctly the rule should only be raised when an exception directly derived from System.Exception, System.SystemException, or System.ApplicationException is not public.

If it is indirectly derived, then issue is not raised.

As it is now, we're doing the opposite, aren't we?

=== On 2017-03-06T18:14:07Z Ann Campbell Wrote:
My initial update omitted the "not" [~jeanchristophe.collet]. That's fixed now.

