=== On 2015-06-08T08:36:45Z Tamas Vajk Wrote:
\[~ann.campbell.2] I've changed the description and the code samples of this RSPEC. Can you go through it? Thanks.

=== On 2015-06-08T11:58:09Z Ann Campbell Wrote:
\[~tamas.vajk] I've made some edits to the description in an attempt to tighten it up a little. Please double-check me.

=== On 2015-06-08T12:10:03Z Tamas Vajk Wrote:
\[~ann.campbell.2] Thanks, it looks good.

=== On 2015-06-09T14:09:32Z Ann Campbell Wrote:
see what you think [~tamas.vajk]

=== On 2015-06-19T09:15:08Z Tamas Vajk Wrote:
\[~ann.campbell.2] The description seems okay now.

But i have a problem with the R# keys. This rule covers quite a lot of R# rules, and I can't put all the code in the field, probably because I reach the max length. :-(



=== On 2015-06-19T13:07:16Z Ann Campbell Wrote:
\[~tamas.vajk] you are hitting a max length. Fortunately, patterns work here. :-)


See the FindBugs field in RSPEC-2275 for an example.

=== On 2015-07-08T09:04:08Z Tamas Vajk Wrote:
\[~ann.campbell.2] I've modified the last point as it is not specific to ``++Count++``.


But a now that I'm thinking about it, we will have exceptions to this rule.

In case of ``++seq.ToList().Count(e=> condition)++`` or ``++seq.ToList().Where(e=> condition)++``, it doesn't make sense to call the ``++ToList++``. But ``++seq.ToList().Count()++`` is faster then ``++seq.Count()++`` because internally it uses a single call to the ``++Count++`` property, which is present on a list. (However, in this case we shouldn't use ``++.Count()++``, but ``++.Count++``.)


So we might want to add an additional covered case: 

* using ``++.Count()++`` doesn't make sense on ``++IEnumerable++``s that are known to be of a derived type that has the more performant ``++.Count++`` property.

WDYT?

=== On 2015-07-08T14:27:32Z Ann Campbell Wrote:
I've added the ``++Count()++``/``++Count++`` case.


Do we need to add an exception? If so, I need some help on the wording: under what circumstances is ``++ToList().Count++`` faster? Always? If so, we can just add that "except when..." to the relevant case.

=== On 2015-07-20T12:02:09Z Tamas Vajk Wrote:
\[~ann.campbell.2] Looks good. We don't need the exception now that we have the additional ``++Count++`` case.

