== Why is this an issue?

A call to the ``++fopen()++``/``++open()++`` function must be matched with a call to ``++fclose()++``/``++close++``. Otherwise, you run the risk of using up all the OS's file handles, which could lock up not just your program but potentially everything on the box.

=== Noncompliant code example

[source,cpp]
----
int fun() {
  FILE *f = fopen("file", "r");
  if (f == NULL) {
    return -1;
  }
  // ...
  return 0; // Noncompliant, file f has not been closed
}
----

=== Compliant solution

[source,cpp]
----
int fun() {
  FILE *f = fopen("file", "r");
  if (f == NULL) {
    return -1;
  }
  // ...
  fclose(f);
  return 0;
}
----

== Resources

* https://cwe.mitre.org/data/definitions/459[MITRE, CWE-459] - Incomplete Cleanup
* https://cwe.mitre.org/data/definitions/772[MITRE, CWE-772] - Missing Release of Resource after Effective Lifetime
* https://wiki.sei.cmu.edu/confluence/x/vjdGBQ[CERT, FIO04-J.] - Release resources when they are no longer needed
* https://wiki.sei.cmu.edu/confluence/x/QtUxBQ[CERT, FIO42-C.] - Close files when they are no longer needed
* https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[Try With Resources]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Review the data-flow; this file might not have been closed when reaching exit point at line ``++line++``.


=== Highlighting

* Primary: the open call, ex: fopen
* Additional: statement exiting the function
** Message: Exit point


'''
== Comments And Links
(visible only on this page)

=== on 30 Mar 2016, 16:46:31 Ann Campbell wrote:
\[~massimo.paladin] I've expanded the description slightly with a 'why'.


Speaking of which, why downgrade this from Blocker to Critical?

=== on 31 Mar 2016, 13:11:53 Ann Campbell wrote:
\[~massimo.paladin] I've moved the Cert C reference back to the main task. All references go on every language-variation of a rule.

=== on 31 Mar 2016, 13:15:08 Massimo PALADIN wrote:
\[~ann.campbell.2] what about ``++Exceptions++`` section which is present on the main task but is not applicable to the language variation?

=== on 31 Mar 2016, 13:29:56 Ann Campbell wrote:
\[~massimo.paladin] I've moved that into a language-specific subtask

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
