== Why is this an issue?

The Cyclomatic Complexity is measured by the number of ``++&&++`` and ``++||++`` operators and ``++if++``, ``++while++``, ``++do++``, ``++for++``, ``++?:++``, ``++catch++``, ``++switch++``, ``++case++``, ``++return++`` and ``++throw++`` statements in the body of a class plus one for each constructor, method, static initializer, or instance initializer in the class. The last return statement in method, if exists, is not taken into account.

Even when the Cyclomatic Complexity of a class is very high, this complexity might be well distributed among all methods. Nevertheless, most of the time, a very complex class is a class which breaks the Single Responsibility Principle and which should be re-factored to be split in several classes.

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

include::../parameters.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
