== Why is this an issue?

Initializing a variable to `undefined` is unnecessary and should be avoided. A variable will automatically be set to `undefined` if you declare it without initialization, so the initialization code is redundant in this case.

[source,javascript]
----
var foo = undefined; // Non-compliant, replace with var foo;
let bar = undefined; // Non-compliant, replace with let foo;
----

Special care must be taken if the variable is declared inside a loop using the `var` keyword. The `var` declaration is not block-scoped, so it will retain it's value between the loop cycles. In this case, the code that includes initialization to `undefined` will reset the value of the variable in each cycle, but if the initialization is removed, the value of the variable will be preserved and may be different if there is another assignment later in the cycle.

[source,javascript]
----
for(i=0; i<max; i++){
    var foo = undefined; // Non-compliant
    bar(foo, i);
    foo = 123;
}
----

To fix the code move the declaration out of the loop and decide if you really need to reset the value to `undefined` in each cycle. This way it is much clearer how the code is actually executed and should not cause any confusion.

[source,javascript]
----
var foo; // move declaration out of the loop
for(i=0; i<max; i++){
    foo = undefined; // if you remove this line, foo = 123 from cycle 2 and after
    bar(foo, i);
    foo = 123;
}
----

== Resources

=== Documentation

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined[MDN - undefined]
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let[MDN - let]
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var[MDN - var]
* https://developer.mozilla.org/en-US/docs/Glossary/Hoisting[MDN - hoisting]