=== What is the potential impact?

A web application redirects users to specific URLs based on user-controllable data. An attacker is able to manipulate a user to perform an HTTP request to the vulnerable web application. The HTTP request contains maliciously injected data that would result in the user being redirected to an attacker's controlled evil domain.

Manipulating the user into performing the HTTP request is usually the main task of exploiting an open redirection as, more often than not, requires an attacker to build a credible pretext to prevent any suspicions arising from the victim. Threat actors commonly use open redirect exploits in mass phishing campaigns. These campaigns commonly occur when threat actors are in posession of leaked customer details for a specific entity which allows them to craft efficient and credible email templates. Banks and e-commerces are highly targeted. 

Below are some real-world scenarios that illustrate the various effects of an attacker exploiting the vulnerability.

==== Domain Mirroring

Redirection to an attacker's controlled website mirroring the interface of a web application trusted by the user. Due to the similarity in the application appearance and the apparently trustable clicked hyperlink, the user struggles to identify that is browsing on a malicious domain. Credentials can be leaked, MFAs can be bypassed and any authenticated data or action can be reached by the attacker.

==== Malware Distribution

User redirection to an attackers' controlled website which serves malicious files. On the same basis as the domain mirroring exploitation, the attacker develops a spearphishing or phishing campaign with a carefully crafted pretext that would result in the download and potential execution of a hosted malicious file. On the worst could result in full system compromise.