== Why is this an issue?

A macro is a textual replacement, which means that it's not respecting the type system, it's not respecting scoping rules... There is no reason not to use a constant instead.


Most of the time, a macro can be replaced by a ``++constexpr++`` declaration (a constant that is guaranteed to be computed during compilation). If your compiler is too old to properly handle ``++constexpr++``, you may use ``++const++`` instead.


If you have a series of related integer macros, you might also consider replacing them by an ``++enum++``.


=== Noncompliant code example

[source,cpp]
----
#define MAX_MEMORY 640 // Noncompliant

#define LEFT   0 // Noncompliant
#define RIGHT  1 // Noncompliant
#define JUMP   2 // Noncompliant
#define SHOOT  3 // Noncompliant
----


=== Compliant solution

[source,cpp]
----
constexpr size_t MAX_MEMORY = 640;
enum class Actions {Left, Right, Jump, Shoot};
----


== Resources

* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#es31-dont-use-macros-for-constants-or-functions[{cpp} Core Guidelines - ES.31] - Don’t use macros for constants or “functions”
* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#enum1-prefer-enumerations-over-macros[{cpp} Core Guidelines - Enum.1] - Prefer enumerations over macros

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::message.adoc[]

endif::env-github,rspecator-view[]
