=== is related to: S3491

=== on 24 Mar 2015, 18:51:43 Evgeny Mandrikov wrote:
\[~ann.campbell.2] regarding title - I think that would be better to narrow it down to "unary prefix operators".


Regarding example - it won't compile, because

{noformat}

---i;

{plus}{plus}+i;

{noformat}

is the same as

{noformat}

--(-i);

{plus}{plus}(+i);

{noformat}

and both ``++-i++`` and ``{plus}i`` are not assignable r-values, thus can't be used for unary ``++--++`` and ``{plus}{plus}``. And seems that description also should be adjusted taking this into account.

=== on 25 Mar 2015, 20:19:25 Evgeny Mandrikov wrote:
\[~ann.campbell.2] I don't think that we should exclude prefix increment and decrement, because so far I don't see good reasons to write ``{plus}{plus}({plus}{plus}i)`` instead of ``++i += 2++``.

=== on 26 Mar 2015, 16:27:45 Ann Campbell wrote:
your turn

=== on 26 Mar 2015, 18:34:35 Evgeny Mandrikov wrote:
\[~ann.campbell.2] LGTM, thanks!

=== on 26 Mar 2015, 18:36:34 Evgeny Mandrikov wrote:
\[~ann.campbell.2] just one question - why targeting only C, {cpp}, Objective-C ?

=== on 26 Mar 2015, 18:38:01 Evgeny Mandrikov wrote:
\[~ann.campbell.2] and ouch - just noticed that there is parameter to ignore two bangs, which is first of all seems to be relevant only for C-Family and second - I believe that we discussed to go without it and see feedback.

=== on 27 Mar 2015, 11:51:06 Ann Campbell wrote:
I've moved the parameter to the C-Family subtask. I suppose the comment thread (now deleted) on the bootstrap document was ambiguous. I thought you were okay to give a try with. We can delete it altogether if you like.

Re langauges, good question. Corrected

=== on 27 Mar 2015, 12:13:38 Evgeny Mandrikov wrote:
\[~ann.campbell.2] my point was - let's remove parameter at all. After first implementation always easier to add than to remove.

=== on 27 Mar 2015, 15:12:07 Ann Campbell wrote:
done

=== on 22 Jul 2015, 12:27:14 Tamas Vajk wrote:
\[~ann.campbell.2] I've added a third message.

=== on 22 Jul 2015, 12:56:55 Tamas Vajk wrote:
\[~ann.campbell.2] I've updated the rule title according to our discussion with [~dinesh.bolkensteyn] and [~freddy.mallet]. I've left the C family exception intact, but we shouldn't implement that for other languages as it raises many question.

* Does this rule recognizes typos? ``{plus}{plus}{plus}{plus}i`` is hardly a typo.
* Why don't we handle ``{plus}\-{plus}\-6`` as well? Why are we restricting the rule to consecutively repeated unary prefix operators? ``+++-+-++`` is also repeated.
* Why don't we handle all useless prefix operators? Such as ``+++6++``.
* Should we handle ``++!(!expression)++`` as well? No we shouldn't, because that is not a typo.

=== on 27 Jul 2015, 10:49:21 Dinesh Bolkensteyn wrote:
Discussed with [~evgeny.mandrikov] [~ann.campbell.2] [~freddy.mallet] and myself

=== on 27 Jul 2015, 12:21:58 Ann Campbell wrote:
I've made a few edits [~dinesh.bolkensteyn]

=== on 27 Jul 2015, 14:25:53 Ann Campbell wrote:
\[~dinesh.bolkensteyn] with this upgraded to Critical/bug, is Maintainability still the appropriate SQALE char?

=== on 27 Jul 2015, 14:32:52 Dinesh Bolkensteyn wrote:
\[~ann.campbell.2] good point - I've update the RSPEC.

=== on 16 Feb 2018, 17:37:19 Alban Auzeill wrote:
Irrelevant for Swift, error: unary operators may not be juxtaposed; parenthesize inner expression

