=== is related to: S1144

=== on 7 Jul 2015, 14:13:53 Ann Campbell wrote:
\[~tamas.vajk] I've left this out of the default profiles on the assumption that it will be controversial. Feel free to change that if you're confident about it.


Also, I was a little shaky on the terminology. I was tempted to use "DLL" instead of scope, but not confident enough to do it.


And finally, I didn't try to write any code samples because I think this is the kind of thing (like "Files should not be too long") that is difficult to illustrate with brevity. Jump in if you disagree. :-)

=== on 8 Jul 2015, 08:46:39 Tamas Vajk wrote:
\[~ann.campbell.2] It looks good. I've added it to the SonarQube Way profile. It won't generate too much noise because of the restriction on the visibility.


A sidenote: whenever you want to write DLL, you should write assembly, because that covers DLLs and EXEs as well. But in this case the scope is better, because for an ``++internal++`` the scope will be the assembly, for a ``++private++`` one it will be the class.  

=== on 8 Jul 2015, 20:44:30 Freddy Mallet wrote:
@Ann, I would associate this rule to the SQALE characteristic Maintainability > Understandability and I tend to agree with @Tamas : according to the limited scope of this rule, it should not trigger some false-positives. I would even make this RSPEC targeting Java and {cpp}.  

=== on 9 Jul 2015, 12:00:16 Ann Campbell wrote:
sqale updated. targeting had already been done.

