== Why is this an issue?

`null`-aware operators allow to safely access nested properties or methods of an object without having to check for the existence of each intermediate property manually. It provides a concise and safe way to access nested properties or methods without having to write complex and error-prone `null` checks.

This rule flags logical operations that can be safely replaced with the `?.` `null`-aware operator.

== How to fix it

Replace with `?.` `null`-aware operator the logical expression that checks for `null` before accessing the property of an object, the element of an array, or calling a function.

=== Code examples

==== Noncompliant code example

[source,dart,diff-id=1,diff-type=noncompliant]
----
void foo(Bar? bar) {
    var x = bar == null ? null : bar.value; // Noncompliant
}
----

[source,dart,diff-id=2,diff-type=noncompliant]
----
void foo(Function? function) {
    if (function != null) function!(); // Noncompliant
}
----


==== Compliant solution

[source,dart,diff-id=1,diff-type=compliant]
----
void foo(Bar? bar) {
    var x = bar?.value;
}
----

[source,dart,diff-id=2,diff-type=compliant]
----
void foo(Function? function) {
    function?.call();
}
----

== Resources

* Dart Docs - https://dart.dev/tools/linter-rules/prefer_null_aware_operators[Dart Linter rule -  prefer_null_aware_operators]
* Dart Docs - https://dart.dev/tools/linter-rules/prefer_null_aware_method_calls[Dart Linter rule -  prefer_null_aware_method_calls]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

* "Use the '??' operator rather than '?:' when testing for 'null'."
* Use a null-aware invocation of the 'call' method rather than explicitly testing for 'null'.

=== Highlighting

The whole ternary operator or if-statement

'''

endif::env-github,rspecator-view[]
