== Why is this an issue?

Having two ``++when++``s in a ``++switch++`` statement or two branches in an ``++if++`` chain  with the same implementation is at best duplicate code, and at worst a coding error. If the same logic is truly needed for both instances, then in an ``++if++`` chain they should be combined, or for a ``++switch++``, one should fall through to the other. 

=== Noncompliant code example

[source,apex]
----
switch on i {
  when 1 {
    doFirstThing();
    doSomething();
  }
  when 2 {
    doSomethingDifferent();
  }
  when 3 {  // Noncompliant; duplicates when 1's implementation
    doFirstThing();
    doSomething(); 
  }
  when else {
    doTheRest();
  }
}

if (a >= 0 && a < 10) {
  doFirstThing();
  doTheThing();
}
else if (a >= 10 && a < 20) {
  doTheOtherThing();
}
else if (a >= 20 && a < 50) {
  doFirstThing();
  doTheThing();  // Noncompliant; duplicates first condition
}
else {
  doTheRest(); 
}
----

=== Exceptions

Blocks in an ``++if++`` chain that contain a single line of code are ignored, as are blocks in a ``++switch++`` statement that contain a single line of code with or without a following ``++break++``.


[source,apex]
----
if(a == 1) {
  doSomething();  //no issue, usually this is done on purpose to increase the readability
} else if (a == 2) {
  doSomethingElse();
} else {
  doSomething();
}
----

But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++switch++``-es without default clauses when all branches have the same single line of code. In case of ``++if++`` chains with ``++else++``-s, or of ``++switch++``-es with default clauses, rule S3923 raises a bug. 

[source,apex]
----
if(a == 1) {
  doSomething();  //Noncompliant, this might have been done on purpose but probably not
} else if (a == 2) {
  doSomething();
}
----

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

include::../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
