=== Duplicate: RSPEC-2751

=== Relates: RSPEC-1862

=== On 2015-04-24T08:15:30Z Tamas Vajk Wrote:
\[~ann.campbell.2] This rule gives false positives on the following pattern:

----
if (a == null) {
    a = tryToGetA();
}
if (a == null) {
    throw new Exception();
}
...
----

Should we add an exception to this rule to check if the condition of the ``++if++`` is comparing an expression, and inside the ``++if++`` some value is assigned to the same expression? Or should this pattern be avoided?

=== On 2015-04-27T07:57:37Z Ann Campbell Wrote:
\[~tamas.vajk] see what you think

=== On 2015-04-27T08:28:29Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] as I already told to [~tamas.vajk] : I don't agree with such exception, IMO provided example doesn't show really readable code - why one wouldn't combine first two if-statements ?

=== On 2015-04-27T15:40:32Z Ann Campbell Wrote:
Exception reverted

=== On 2015-06-03T07:34:05Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] maybe we should add a little explanation why this is irrelevant for JavaScript? to prevent confusion during further reviews?

=== On 2015-06-03T14:29:46Z Ann Campbell Wrote:
Irrelevant for JavaScript because this is a very common pattern, which raised hundreds of FP's

----
if ( ! isItOkay(a)) {
  doSomethingTo(a);
}
if ( ! isItOkay(a)) {
  // try again? raise error? ...
}
----
cc [~elena.vilchik]

=== On 2015-06-03T14:35:48Z Evgeny Mandrikov Wrote:
\[~elena.vilchik], [~ann.campbell.2], same question as for example from C# - why one wouldn't combine those two if-statements into single one?

----
if ( ! isItOkay(a)) {
  doSomethingTo(a);
  if ( ! isItOkay(a)) {
    // try again? raise error? ...
  }
}
----

=== On 2015-06-04T13:09:44Z Tamas Vajk Wrote:
\[~evgeny.mandrikov] we had the same in C# as we discussed it earlier. Since then, I added an exception for the following:

----
if (condition)
{
  statement
}
if (condition)
{
 //...
}
----

where ``++statement++`` is in any of the following three formats:

----
x = anything; //any kind of assignment (-=, +=, ...)
x++; //any postfix unary
++x; //any prefix unary
----
and ``++x++`` can be any symbol in ``++condition++``.


With this simple exception, I could get rid of all the false positives that we had in the C# ruling.



=== On 2015-06-04T14:07:55Z Evgeny Mandrikov Wrote:
\[~tamas.vajk] I see the issue here - implementation not aligned with RSPEC. /CC [~dinesh.bolkensteyn] [~ann.campbell.2] [~freddy.mallet]

=== On 2015-06-04T15:31:13Z Dinesh Bolkensteyn Wrote:
As the RSPEC is assigned to you [~evgeny.mandrikov] , I understand that you take care to come up with a solution to this issue.

=== On 2015-06-05T12:09:48Z Evgeny Mandrikov Wrote:
\[~dinesh.bolkensteyn] no, I don't, I don't know why Ann assigned it back to me.

=== On 2015-06-05T12:50:22Z Ann Campbell Wrote:
Absentmindedness [~evgeny.mandrikov]. I thought it was _still_ assigned to me, not _reassigned_ to me.

=== On 2015-06-05T23:24:19Z Evgeny Mandrikov Wrote:
\[~tamas.vajk] if I correctly understand your exclusion, then this case will be excluded:

{noformat}

if (c > 5)

  {cpp};

if (c > 5) // copy-paste error

  c--;

{noformat}

I don't see an excuse for successive if-statements with identical conditions - they are error-prone and IMO make code less unreadable.



=== On 2015-06-08T07:59:28Z Tamas Vajk Wrote:
\[~evgeny.mandrikov] Yes, you see it correctly, this won't report an issue in the current implementation.

=== On 2015-06-08T08:04:06Z Dinesh Bolkensteyn Wrote:
my 2 cents: This is a maintainability rule, not a bug detection one - there should be another rule that targets the discovery of copy&paste errors


----
if (foo == null)
{
  foo = GetFoo1();
}

if (foo == null)
{
  foo = GetFoo2();
}
----

this could be refactored into:


----
if (foo == null)
{
  foo = GetFoo1();
  if (foo == null)
  {
    foo = GetFoo2();
  }
}
----

but there clearly is no bug here...

=== On 2015-06-08T08:43:28Z Dinesh Bolkensteyn Wrote:
Let's discuss IRL

=== On 2015-06-24T19:07:24Z Ann Campbell Wrote:
\[~tamas.vajk], [~evgeny.mandrikov], [~dinesh.bolkensteyn] where do we stand on this rule? FYI, I've just upgraded severity to Critical since I'm pretty sure we want to keep the 'bug' tag.

=== On 2015-06-25T13:01:35Z Tamas Vajk Wrote:
\[~ann.campbell.2], I've added an exception to this rule in the C# substask.

=== On 2015-09-03T13:51:39Z Ann Campbell Wrote:
Downgraded from Critical/bug/Reliability to Major/suspicious/Maintainability and exception added after discussion with [~freddy.mallet], [~tamas.vajk], [~ann.campbell.2]

