=== On 2013-08-01T13:21:52Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-264

=== On 2013-08-01T23:28:32Z Ann Campbell Wrote:
The description says that the lower-level finalize won't be called, but that's not what my reading indicates...?

=== On 2013-08-02T06:26:50Z Dinesh Bolkensteyn Wrote:
How many rules do we need on Object.finalize()?


We already have 3, and I think that having 5 is really too much to cover a feature that in practice is never used...


It probably would be better to see how those 2 new rules could be fit into the existing 3 rules use cases

=== On 2013-08-02T07:38:10Z Dinesh Bolkensteyn Wrote:
Methods should not be named 'finalize'

=== On 2013-08-02T08:25:35Z Freddy Mallet Wrote:
Just to make it clear, in such case we're really talking about overloading and not about overriding.

=== On 2015-02-02T20:57:10Z Sébastien Gioria Wrote:
CERT Secure Coding MET12-J

=== On 2015-02-03T20:39:26Z Ann Campbell Wrote:
I see this as a different issue [~sebastien.gioria].

=== On 2015-06-16T11:47:56Z Ann Campbell Wrote:
CodePro: Finalize Method Definition

