== Why is this an issue?

Procedures with a long parameter list are difficult to use, as maintainers must figure out the role of each parameter and keep track of their position.

[source,vbnet]
----
Function SetCoordinates(ByVal x1 As Integer, ByVal y1 As Integer, ByVal z1 As Integer, ByVal x2 As Integer, ByVal y2 As Integer, ByVal z2 As Integer) ' Noncompliant
    ' ...
End Function
----

The solution can be to:

* Split the procedure into smaller ones

[source,vbnet]
----
' Each function does a part of what the original setCoordinates function was doing, so confusion risks are lower
Function SetOrigin(ByVal x As Integer, ByVal y As Integer, ByVal z As Integer)
   ' ...
End Function

Function SetSize(ByVal width As Integer, ByVal height As Integer, ByVal depth As Integer)
   ' ...
End Function
----

* Find a better data structure for the parameters

[source,vbnet]
----
Private Structure Point ' Point is a concept example that logically groups data'
    Public x As Integer
    Public y As Integer
    Public z As Integer
End Structure

Function SetCoordinates(ByVal p1 As Point, ByVal p2 As Point)
    ' ...
End Function
----

This rule raises an issue when a procedure has more parameters than the maximum authorized number of parameters.

=== Exceptions

The rule does not count the parameters intended for a base class constructor.

With a maximum number of 4 parameters:

[source,vbnet]
----
Public Class BaseClass
    Public Sub New(Param1 As Integer)
        ' ...
    End Sub
End Class

Public Class DerivedClass
    Inherits BaseClass

    Public Sub New(Param1 As Integer, Param2 As Integer, Param3 As Integer, Param4 As Integer, Param5 As Long)
        MyBase.New(Param1) ' Compliant by exception
        ' ...
    End Sub

End Class
----

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

 [Constructor|Function|Sub|Delegate|Lambda] has {0} parameters, which is greater than the {1} authorized.


include::../parameters.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
