=== Duplicate: RSPEC-2117

=== Relates: RSPEC-1829

=== On 2013-06-05T13:18:55Z Fabrice Bellingard Wrote:
The strings that should be detected are any kind of absolute or OS-specific URI - but not relative ones. For instance:

* should be detected:
** Strings starting with an http://en.wikipedia.org/wiki/URI_scheme[URI scheme]:
*** \http://www.mywebsite.com
*** ftp://myserver.com
*** file:/my/folder
*** ...etc
** //my-network-drive
** C:/my/folder
** /my/other/folder
** ~/my/local/folder
* should NOT be detected: 
** my/folder
** ./my/folder
** ../my/folder

=== On 2015-02-02T20:47:46Z Sébastien Gioria Wrote:
CERT MSC03-J

=== On 2015-02-03T20:34:01Z Ann Campbell Wrote:
thanks [~sebastien.gioria]

=== On 2015-04-10T18:32:39Z Ann Campbell Wrote:
I'm assigning this rule update to you for verification [~elena.vilchik], since you're the only one to have implemented it so far.


Note that I've already entered SWIFT-108 to update Swift implementation.



=== On 2017-06-30T11:09:23Z Amaury Levé Wrote:
There is no link to FxCop, could you add it?

=== On 2017-06-30T13:55:21Z Jean-Christophe Collet Wrote:
Done

=== On 2018-08-28T17:11:04Z Elena Vilchik Wrote:
I've set JS and TS as irrelevant for this rule, as it's common practice to hardcode urls (e.g. for API endpoints). Even if sometimes the rule might be relevant, still ROI is low (rule has low value and implementation is not super trivial)

