=== Duplicate: RSPEC-915

=== Duplicate: RSPEC-918

=== Related: RSPEC-3458

=== Related: RSPEC-3532

=== Related: RSPEC-3562

=== On 2013-05-08T10:53:53Z Freddy Mallet Wrote:
when there is a default clause but this one is not the last clause, the following message must be displayed:

* "default" clause should be the last one.

=== On 2013-07-10T11:43:59Z Dinesh Bolkensteyn Wrote:
Implemented by \http://jira.codehaus.org/browse/SONARJAVA-200

=== On 2013-11-22T09:23:49Z Freddy Mallet Wrote:
Is implemented by \http://jira.sonarsource.com/browse/RSPEC-131 for Flex

=== On 2014-02-12T22:04:27Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3472 for PHP

=== On 2014-12-09T22:20:33Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] MISRA C:2012 has rule 16.5 (A default label shall appear as either the first or the last switch label of a switch statement), which I can't find in RSPEC. Question is - should we simply reference it from this spec, thus increasing coverage of MISRA for free? or we should create dedicated implementation?

=== On 2014-12-10T13:01:22Z Ann Campbell Wrote:
\[~evgeny.mandrikov] my vote would be to add the references here. 


Surely 2012 isn't the only year to have such a rule...?

=== On 2014-12-10T13:15:33Z Ann Campbell Wrote:
\[~evgeny.mandrikov] in fact, this is the rule. It appears that references were mistyped initially. 

