== Why is this an issue?

In JavaScript, we can use the ``++/++`` (backslash) character to escape special characters inside a string, a template literal, or a regular expression. It indicates that the next character should be treated as a literal character rather than as a special character or string delimiter.
For instance, it is common to escape single quotes inside a string literal using the single quote delimiter.

[source,javascript]
----
'It\'s a beautiful day'
----

Or escaping special regular expression characters to be able to match them, e.g. here '.' has to be escaped as it's a special character in regular expressions.
[source,javascript]
----
const regexForDate = /\d{2}\.\d{2}\.\d{4}/;
----

Escaping is only meaningful for special characters. Escaping non-special characters doesn't affect their value. Therefore, useless escapes impact code readability and could even denote a bug in the code if the developer left it by mistake or intended to escape another special character instead.

We can safely remove a useless character escape without changing the original behaviour.

[source,javascript]
----
const regex = /[\[]/;    // Noncompliant: '[' does not need to be escaped when inside a character class '[]'
const regexOK = /[[]/;

const octal = '\8';      // Noncompliant: '\8' and '\9' are a legacy feature
const octalOK = '8';

const hello = 'Hello, world\!'; // Noncompliant: '!' is not a special character
const helloOK = 'Hello, world!';

const path  = `\/${some}\/${dir}`; // Noncompliant: '/' is not a special character
const pathOK  = `/${some}/${dir}`;
----

== Resources

=== Documentation

- https://www.w3schools.com/js/js_strings.asp[W3 schools - JavaScript strings]
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions#using_special_characters[MDN special characters in Regular expressions]