== Why is this an issue?

In JavaScript, the ``++\++`` (backslash) character indicates that the next character should be treated as a literal character rather than as a special character or string delimiter.
For instance, it is common to escape single quotes inside a string literal using the single quote delimiter like ``++'It\'s a beautiful day'++``. Escaping is only meaningful for special characters.
Escaping non-special characters in strings, template literals, and regular expressions doesn't affect their value.
Therefore, useless escapes impact code readability and could even denote a bug in the code if the developer left it by mistake or intended to escape another special character instead.

You should check if the escape character was not misplaced. Useless character escapes can safely be removed without changing the original behavior.

The following code snippet shows some cases where there is no need to escape:

[source,javascript,diff-id=1,diff-type=noncompliant]
----
const regex = /[\[]/;    // Noncompliant: '[' does not need to be escaped when inside a character class '[]'
const octal = '\8';      // Noncompliant: '\8' and '\9' are a legacy feature
const hello = 'Hello, world\!'; // Noncompliant: '!' is not a special character
const path  = `\/${some}\/${dir}`; // Noncompliant: '/' is not a special character
----

Instead, the following can be safely used:

[source,javascript,diff-id=1,diff-type=compliant]
----
const regex = /[[]/;
const octal = '8';
const hello = 'Hello, world!';
const path  = `/${some}/${dir}`;
----

== Resources

=== Documentation

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions#escaping[MDN Escaping in Regular expressions]
- https://www.w3schools.com/js/js_strings.asp[W3 schools - JavaScript strings]