== Why is this an issue?

include::../description.adoc[]

include::../noncompliant.adoc[]

include::../compliant.adoc[]

== Resources

* MISRA C:2004, 12.1 - Limited dependence should be placed on the C operator precedence rules in expressions.
* MISRA C:2004, 12.13 - The increment ({plus}{plus}) and decrement (--) operators should not be mixed with other operators in an expression.
* MISRA {cpp}:2008, 5-2-10 - The increment ({plus}{plus}) and decrement (--) operator should not be mixed with other operators in an expression.
* MISRA C:2012, 12.1 - The precedence of operators within expressions should be made explicit
* MISRA C:2012, 13.3 - A full expression containing an increment ({plus}{plus}) or decrement (--) operator should have no other potential side effects other than that cause by the increment or decrement operator
* https://wiki.sei.cmu.edu/confluence/x/StYxBQ[CERT, EXP30-C.] - Do not depend on the order of evaluation for side effects
* https://wiki.sei.cmu.edu/confluence/x/IXw-BQ[CERT, EXP50-CPP.] - Do not depend on the order of evaluation for side effects
* https://wiki.sei.cmu.edu/confluence/x/NDdGBQ[CERT, EXP05-J.] - Do not follow a write by a subsequent write or read of the same object within an expression

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

include::../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
