include::../description.adoc[]

include::../noncompliant.adoc[]

include::../compliant.adoc[]

== See

* MISRA C:2004, 12.1 - Limited dependence should be placed on the C operator precedence rules in expressions.
* MISRA C:2004, 12.13 - The increment (++) and decrement (--) operators should not be mixed with other operators in an expression.
* MISRA C++:2008, 5-2-10 - The increment (++) and decrement (--) operator should not be mixed with other operators in an expression.
* MISRA C:2012, 12.1 - The precedence of operators within expressions should be made explicit
* MISRA C:2012, 13.3 - A full expression containing an increment (++) or decrement (--) operator should have no other potential side effects other than that cause by the increment or decrement operator
* https://www.securecoding.cert.org/confluence/x/ZwE[CERT, EXP30-C.] - Do not depend on the order of evaluation for side effects
* https://www.securecoding.cert.org/confluence/x/fYAyAQ[CERT, EXP50-CPP.] - Do not depend on the order of evaluation for side effects
* https://www.securecoding.cert.org/confluence/x/yQC7AQ[CERT, EXP05-J.] - Do not follow a write by a subsequent write or read of the same object within an expression
