=== Deprecate: RSPEC-3223

=== Related: RSPEC-3633

=== Related: RSPEC-3651

=== Supercedes: RSPEC-1145

=== Supercedes: RSPEC-1768

=== Supercedes: RSPEC-2815

=== On 2015-02-12T09:58:22Z Pierre-Yves Nicolas Wrote:
We target more advanced cases for the COBOL implementation of that rule where a complex condition is always true or false. In those cases, the solution is not to remove the whole condition but to either remove a sub-condition or change it. We would therefore need a dedicated description for COBOL.

=== On 2015-02-12T13:38:40Z Ann Campbell Wrote:
Can you rough something out for me [~pierre-yves.nicolas]?

=== On 2016-07-14T18:04:09Z Ann Campbell Wrote:
\[~nicolas.peru] is this case covered:

https://github.com/google/error-prone/blob/master/docs/bugpattern/EqualsIncompatibleType.md ?

=== On 2016-07-14T18:08:10Z Nicolas Peru Wrote:
\[~ann.campbell.2] not covered but let's say that : " almost certainly false in most configurations" is not really an incentive to go cover it ;) 

=== On 2016-07-14T19:25:26Z Ann Campbell Wrote:
\[~nicolas.peru] 

* \https://github.com/google/error-prone/blob/master/docs/bugpattern/IsInstanceOfClass.md 
* \https://github.com/google/error-prone/blob/master/docs/bugpattern/SelfComparison.md
* \https://github.com/google/error-prone/blob/master/docs/bugpattern/SelfEquals.md
?

=== On 2016-07-19T15:54:55Z Nicolas Peru Wrote:
https://github.com/google/error-prone/blob/master/docs/bugpattern/IsInstanceOfClass.md -> for me this one should have its own dedicated rule.


https://github.com/google/error-prone/blob/master/docs/bugpattern/SelfComparison.md -> this one should indeed probably be supported by SE engine in conjunction with the support of zero (cc [~michael.gumowski]


Last one should be already supported in fact.

=== On 2019-05-02T17:14:00Z Andrei Epure Wrote:
The message should be improved, as it is misleading. For example when the boolean expression is part of a chain of ``++OR++`` expressions, the subsequent code will be executed. Therefore _some subsequent code is never executed_ is misleading. (cc [~nicolas.harraudeau])


Example for csharp (which came in https://github.com/SonarSource/sonar-dotnet/issues/2411[issue #2411]). Although this specific example is rather an occurence of https://rules.sonarsource.com/csharp/RSPEC-2589[RSPEC-2589] _Boolean expressions should not be gratuitous..._

----
    public void DoTest(Guid guid)
    {
        if (guid == null || guid == Guid.Empty)
            guid = Guid.NewGuid();
    }
----

