== Why is this an issue?

If any of the arguments act like preprocessor directives, the behaviour when macro substitution is made can be unpredictable.


=== Noncompliant code example

[source,cpp]
----
#define M(A) printf ( #A )
void main ( )
{
  M(  // Could print "Message 2", could print '#ifdef SW "Message 1" #else "Message 2" #endif'
#ifdef SW  // Noncompliant
  "Message 1"
#else  // Noncompliant
  "Message 2"
#endif  // Noncompliant
  );
}
----


=== Compliant solution

[source,cpp]
----
#define M(A) printf ( #A )
#ifdef SW
#define MSG "Message 1"
#else
#define MSG "Message 2"
#endif

void main ( )
{
  M( MSG );
}
----


== Resources

* MISRA C:2004, 19.9
* MISRA {cpp}:2008, 16-0-5


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Remove "#xxx" from this macro expansion.


'''
== Comments And Links
(visible only on this page)

=== relates to: S960

=== relates to: S967

=== on 21 Oct 2014, 19:28:47 Ann Campbell wrote:
\[~samuel.mercier], 

* Please incorporate the text under the code headings either into the code samples as comments or into the description. 
* The message makes it sound like only one issue will be logged per macro no matter how many preprocessing directives there are in it? If so, I disagree & would prefer to see a message like 'Remove "#xxx" from this macro.'
* Also, "unpredictable" sounds like Reliability to me, rather than Maintainability.
* And finally, this is likely a "bug".

endif::env-github,rspecator-view[]
