=== on 10 Feb 2015, 13:48:04 Samuel Mercier wrote:
\[~evgeny.mandrikov] I rewrote the rule to prevent usage of ``++sizeof++`` on a variable with pointer type

\[~ann.campbell.2] Could you verify?

=== on 10 Feb 2015, 13:55:58 Ann Campbell wrote:
I've made some updates [~samuel.mercier] that you probably want to check. Since this is not a MISRA rule, then we should use the standard format for the title: "X should [not] y", rather than using "shall".


Also, I'm not wild about the message. I'd either go with "Remove this use of..." or '"x" is a pointer'.

=== on 13 Feb 2015, 08:44:14 Samuel Mercier wrote:
\[~ann.campbell.2] ok for title. For the message, in past, we already had this discussion :) '"x" is a pointer' doesn't say anything about neither the problem nor the resolution, so it should be avoided. I also don't really like the "remove" form because there are really two cases covered by this rule:

1) sizeof is used on a function parameter with type array. in that case sizeof should effectively be removed and an additional size argument must be provided

2) sizeof is probably badly used on a pointer, so there is probably a missing * : sizeof(p) -> sizeof(*p)

so among the three I would stick with the current one.

=== on 13 Feb 2015, 12:20:36 Ann Campbell wrote:
Okay [~samuel.mercier]

