== Why is this an issue?

include::../description.adoc[]

=== Noncompliant code example

For https://docs.aws.amazon.com/opensearch-service/index.html[Amazon OpenSearch domains]:

[source,yaml]
----
AWSTemplateFormatVersion: 2010-09-09
Resources:
  Example:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: example
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: "Policy-Min-TLS-1-0-2019-07"  # Noncompliant
----

For https://aws.amazon.com/api-gateway/[Amazon API Gateway]:

[source,yaml]
----
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CustomApi:
    Type: AWS::ApiGateway::DomainName
    Properties:
      SecurityPolicy: "TLS_1_0"  # Noncompliant
----

[source,yaml]
----
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CustomApi: # Noncompliant
    Type: AWS::ApiGatewayV2::DomainName
----

=== Compliant solution

For https://docs.aws.amazon.com/opensearch-service/index.html[Amazon OpenSearch domains]:

[source,yaml]
----
AWSTemplateFormatVersion: 2010-09-09
Resources:
  Example:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: example
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: "Policy-Min-TLS-1-2-2019-07"
----

For https://aws.amazon.com/api-gateway/[Amazon API Gateway]:

[source,yaml]
----
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CustomApi:
    Type: AWS::ApiGateway::DomainName
    Properties:
      SecurityPolicy: "TLS_1_2"
----

[source,yaml]
----
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CustomApi:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainNameConfigurations:
        - SecurityPolicy: "TLS_1_2"
----

include::../see.adoc[]
* https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-custom-domain-tls-version.html[Amazon API Gateway] - Choosing a minimum TLS version



ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

For `AWS::Elasticsearch::Domain` and `AWS::OpenSearchService::Domain`:

* If `TLSSecurityPolicy` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
* If `DomainEndpointOptions` is specified but does not contain `TLSSecurityPolicy`
** Set "TLSSecurityPolicy" to disable support of older TLS versions.
* If `DomainEndpointOptions` is not specified at all
** Set "DomainEndpointOptions.TLSSecurityPolicy" to disable support of older TLS versions.

For `AWS::ApiGateway::DomainName`:

 * If `SecurityPolicy` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
 * If `SecurityPolicy` is not specified at all
 ** Set "SecurityPolicy" to disable support of older TLS versions.

For `AWS::ApiGatewayV2::DomainName`:

 * If `SecurityPolicy` is specified but has the wrong value
 ** Change this code to disable support of older TLS versions.
 * If `DomainNameConfigurations` exists but `SecurityPolicy` is not specified
** Set "SecurityPolicy" to disable support of older TLS versions.
 * If `DomainNameConfigurations` does not exist
** Set "DomainNameConfigurations.SecurityPolicy" to disable support of older TLS versions.


=== Highlighting


For `AWS::Elasticsearch::Domain` and `AWS::OpenSearchService::Domain`:

* Highlight `TLSSecurityPolicy` if it is specified but has the wrong value
* Highlight `DomainEndpointOptions` if it is specified but does not contain `TLSSecurityPolicy`
* Highlight resource if `DomainEndpointOptions` is not specified at all

For `AWS::ApiGateway::DomainName`:

 * Highlight `SecurityPolicy` if it is specified but has the wrong value
 * Highlight resource if `SecurityPolicy` is not specified at all

For `AWS::ApiGatewayV2::DomainName`:

 * Highlight `SecurityPolicy` if it is specified but has the wrong value
 * Highlight `DomainNameConfigurations` if it exists but `SecurityPolicy` is not specified
 * Highlight resource if `DomainNameConfigurations` does not exist


'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
