== Why is this an issue?

``++std::auto_ptr++`` was a pre-{cpp}11 attempt to do what ``++std::unique_ptr++`` now does. Unfortunately, the move semantics needed to make it work properly weren't in place, so copying a ``++std::auto_ptr++`` has the very surprising behavior of invalidating the source of the copy.


That problem has been fixed with ``++std::unique_ptr++``, so ``++std::auto_ptr++`` has been deprecated in {cpp}11 and removed in {cpp}17.


If your compiler allows it, you should replace all use of ``++std::auto_ptr++`` with ``++std::unique_ptr++``. Otherwise, define your own (non-copyable) smart pointer.


=== Noncompliant code example

[source,cpp]
----
using namespace std;

void draw(auto_ptr<Shape> p) { cout << s->x() << ", " << s.y() << endl;} // Noncompliant

void f()
{
    std::auto_ptr<Shape> s = createShape(); // Noncompliant
    draw(s); // This call invalidates s
    draw(s); // This call will crash, because s is null
}
----


=== Compliant solution

[source,cpp]
----
using namespace std;

void draw(unique_ptr<Shape> p) { cout << s->x() << ", " << s.y() << endl;} // Compliant

void f()
{
    std::unique_ptr<Shape> s = createShape();
    // draw(s); // Would not compile
    draw(move(s)); // Will compile, and the user knows s has been invalidated
}
----



ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Replace this use of "std::auto_ptr" with "std::unique_ptr"


'''
== Comments And Links
(visible only on this page)

=== on 6 Nov 2018, 18:23:37 Ann Campbell wrote:
I've reworded [~loic.joly]. Please double-check that I haven't changed the meaning.

endif::env-github,rspecator-view[]
