=== Relates: RSPEC-2201

=== Relates: RSPEC-2677

=== On 2014-11-13T22:55:27Z Evgeny Mandrikov Wrote:
There is some exclusions in CERT.

=== On 2014-11-17T16:16:15Z Ann Campbell Wrote:
\[~evgeny.mandrikov] do you want to add a whitelist to this rule?

=== On 2015-02-02T20:34:28Z Sébastien Gioria Wrote:
This could fall into OWASP Top10 2013 -A6


it's CERT EXP00-J

=== On 2015-02-03T20:26:49Z Ann Campbell Wrote:
I've added the CERT reference [~sebastien.gioria], but don't understand the OWASP tie.

=== On 2015-02-03T20:28:47Z Ann Campbell Wrote:
\[~freddy.mallet] the history on this ticket shows that you deleted the description on the 1st of December. How come?

=== On 2015-02-04T09:45:11Z Freddy Mallet Wrote:
\[~ann.campbell.2] I guess my main goal was to remove the Compliant and NonCompliant sections that were suitable only for C/{cpp}. But indeed the first sentence should remain in the global description. I let you revert this change @Ann ?

=== On 2016-07-29T09:59:15Z Freddy Mallet Wrote:
\[~ann.campbell.2], I tend to think that the impact should be "Low" on this vulnerability.

