This rule raises an issue when calls to `tuple()`, `list()`, `set()`, or `dict()` 
are done with an argument that is already a literal of the target type, a literal of a compatible type that could be expressed more directly, or a comprehension that directly produces the target type. 

== Why is this an issue?

Python provides direct ways to create common data structures like tuples, lists, and dictionaries using literals (e.g., `()`, `(1,2)`, `[]`, `[1,2]`, `{}`, `{'a':1}`) 
and comprehensions (e.g., `[x for x in y]`, `{k:v for k,v in y}`).
Wrapping these direct forms in their corresponding type constructors (e.g., `tuple((1,2))`, `list([1,2])`, `list([x for x in y])`, `dict({'a':1})`, `dict({k:v for k,v in y})`) is unnecessary. 
Such constructs add verbosity without providing any additional functionality and can slightly mislead readers or imply a more complex operation than what is actually occurring.

== How to fix it

To fix this remove the redundant `tuple()`, `list()`, `set()` or `dict()` calls and use the direct literal or comprehension syntax.

[source,python,diff-id=1,diff-type=noncompliant]
----
t1 = tuple([1, 2]) # Noncompliant: the tuple creation can be done directly
----

[source,python,diff-id=1,diff-type=compliant]
----
t1 = (1, 2) # Compliant
----

[source,python,diff-id=2,diff-type=noncompliant]
----
def foo(x):
    return x * 2

l1 = list([foo(x) for x in [1,2,3]]) # Noncompliant: list is redundant.
----

[source,python,diff-id=2,diff-type=compliant]
----
def foo(x):
    return x * 2
l1 = [foo(x) for x in [1,2,3]] # Compliant
----

== Resources

=== Documentation
* Python Documentation - https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions[List Comprehensions]
* Python Documentation - https://docs.python.org/3/tutorial/datastructures.html#dictionaries[Dictionaries]
* Python Documentation - https://docs.python.org/3/tutorial/datastructures.html#sets[Sets]
* Python Documentation - https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences[Tuples and Sequences]

ifdef::env-github,rspecator-view[]
== Implementation Specification

=== Message

Remove the redundant {tuple|list|set|dict} constructor call.

Exception for `tuple([1,2])`: Replace this tuple constructor call by a tuple literal.

=== Highlighting
The list/set/dict/tuple constructor call.
endif::env-github,rspecator-view[]
