Array overruns and buffer overflows happen when memory access accidentally goes beyond the boundary of the allocated array or buffer. These overreaching accesses cause some of the most damaging, and hard to track defects.

When the buffer overflow happens while reading a buffer, it can expose sensitive data that happens to be located next to the buffer in memory. When it happens while writing a buffer, it can be used to inject code or to wipe out sensitive memory.

This rule detects when a POSIX function takes one argument that is a buffer and another one that represents the size of the buffer, but the two arguments do not match.


== Noncompliant Code Example

----
char array[10];
initialize(array);
void *pos = memchr(array, '@', 42); // Noncompliant, buffer overflow that could expose sensitive data 
----


== Compliant Solution

----
char array[10];
initialize(array);
void *pos = memchr(array, '@', 10);
----


== See

* https://cwe.mitre.org/data/definitions/119.html[MITRE, CWE-119] - Improper Restriction of Operations within the Bounds of a Memory Buffer
* http://cwe.mitre.org/data/definitions/131[MITRE, CWE-131] - Incorrect Calculation of Buffer Size
* https://cwe.mitre.org/data/definitions/788.html[MITRE, CWE-788] - Access of Memory Location After End of Buffer
* https://www.securecoding.cert.org/confluence/x/DYDXAg[CERT, ARR30-C.] - Do not form or use out-of-bounds pointers or array subscripts
* https://www.securecoding.cert.org/confluence/x/P4EyAQ[CERT, STR50-CPP.] - Guarantee that storage for strings has sufficient space for character data and the null terminator

