== Why is this an issue?

Clear and communicative error messages help people understand what went wrong and how to correct the problem. However, care must be taken with ``++Servlet++`` error messages because they could expose sensitive information to an attacker. Even sending the user's own data back to him in an error message could be risky; you never know who might catch a glimpse of the screen.


This rule checks that the strings used in servlet responses made from ``++catch++`` blocks don't change from call to call. Ideally, such strings would be ``++private static final++``, but that is not enforced by this rule. Logging messages are ignored by this rule.


=== Noncompliant code example

[source,java]
----
public class MyServlet extends HttpServlet {
  protected void doPost(HttpServletRequest request, HttpServletResponse response) 
        throws ServletException, IOException {
    String login = null;
    String pword
    try {
      login =  login = request.getParameter("login");
      pword = request.getParameter("password");
      // ...
    }
    catch (LoginFailureException ex) {
      LOGGER.log(Level.INFO, "Login failure for " + 
              login + ", " + pword);  // Compliant, but not a good idea
      request.setAttribute("error", 
              "Login failed for " + login + // Noncompliant; attacker now knows valid or nearly-valid login
                      " with password " + pword);  // Noncompliant; attacker now knows valid or nearly-valid password
      request.setAttribute("message", ex.getMessage()); // Noncompliant; could contain sensitive data
      getServletContext().getRequestDispatcher("/ErrorPage.jsp")
              .forward(request, response);
----


=== Compliant solution

[source,java]
----
public class MyServlet extends HttpServlet {
  protected void doPost(HttpServletRequest request, HttpServletResponse response) 
        throws ServletException, IOException {
    String login = null;
    String pword
    try {
      login =  login = request.getParameter("login");
      pword = request.getParameter("password");
      // ...
    }
    catch (LoginFailureException ex) {
      LOGGER.log(Level.INFO, "Login failure for " + login);  // Much better
      request.setAttribute("error", "Login failed");
      getServletContext().getRequestDispatcher("/ErrorPage.jsp")
              .forward(request, response);

----


== Resources

* https://www.owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure[OWASP Top 10 2017 Category A3] - Sensitive Data Exposure
* https://cwe.mitre.org/data/definitions/537[MITRE, CWE-537] - Information Exposure Through Java Runtime Error Message



ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

This message should not vary by circumstance.


'''
== Comments And Links
(visible only on this page)

=== on 20 Jul 2015, 07:48:10 Ann Campbell wrote:
Tagged java-top by Ann

endif::env-github,rspecator-view[]
