Using unsafe code can lead to unintended security or stability risks.

Unsafe code blocks allow developers to use features such as pointers, fixed buffers, function calls through pointers and manual memory management. Unsafe code may be used for interop with native libraries, as they often require pointers. It may also increase performance in some critical areas, as certain bounds checks are not executed in an unsafe context.

Although unsafe contexts aren't necessarily dangerous, the code in these contexts cannot be verified by the Common Language Runtime. Therefore, it can be prone to bugs that lead to memory corruption vulnerabilies such as stack overflows. Because of this, unsafe code should be used with caution. It can easily introduce security or stability risks.

If an unsafe context is introduced to increase performance, the https://learn.microsoft.com/en-us/dotnet/standard/memory-and-spans/[Span and Memory APIs] may serve a similar purpose in a safe context. If it is used to call native functions with pointers, then the unsafe context should be kept as small as possible. Doing so reduces risk, as there is less code that can potentially introduce new bugs.


== Ask Yourself Whether

* There are any pointers or fixed buffers declared within the unsafe code block.

There is a risk if you answered yes to the question.


== Recommended Secure Coding Practices

* Do not use unsafe code blocks.


== Sensitive Code Example

[source,csharp,diff-id=1,diff-type=noncompliant]
----
public unsafe int subarraySum(int[] array, int start, int end)  // Sensitive
{
    var sum = 0;

    // Skip array bound checks for extra performance
    fixed (int* firstNumber = array)
    {
        for (int i = start; i < end; i++)
            sum += *(firstNumber + i);
    }

    return sum;
}
----

== Compliant Solution

[source,csharp,diff-id=1,diff-type=compliant]
----
public int subarraySum(int[] array, int start, int end)
{
    var sum = 0;

    Span<int> span = array.AsSpan();
    for (int i = start; i < end; i++)
        sum += span[i];

    return sum;
}
----

== See

* https://cwe.mitre.org/data/definitions/787.html[MITRE, CWE-787] - Out-of-bounds Write
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/unsafe-code[Microsoft Learn] - Unsafe code, pointer types, and function pointers


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

== Message

* Make sure that declaring unsafe code is safe here.

== Highlighting

Highlight the unsafe keyword.

'''

endif::env-github,rspecator-view[]
