name: 'Install common dependencies'
description: 'Install common dependencies for the project'

runs:
  using: 'composite'
  steps:
    - uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
      env:
        MISE_PYTHON_DEFAULT_PACKAGES_FILE: ${{ github.workspace }}/ci/mise-default-python-packages
      with:
        version: 2025.11.3
    - name: Setup asciidoctor
      shell: bash
      run: |
        sudo gem install asciidoctor
        asciidoctor --version
