== Why is this an issue?

When you do not use the return value of a method that does not have any side effects it is an indication that something is wrong. Either this method is not really needed or the source code does not behave as expected and it could lead to defects in the code.

This rule raises an issue when the results of the following methods are ignored:
* LINQ methods,
* `[Pure]` methods,
* any method on returning a build-in type (for example, string, int etc) or an Immutable collection (for example, `ImmutableArray`, `ImmutableDictionary` etc).

Special cases:

* Although `string.Intern` has a side effect, ignoring its return value is still suspicious as it is the only reference ensured to point to the intern pool.
* LINQ methods can have side effects if they are misused. For example:
----
data.All(x =>
{
    x.Property = "foo";
    return true;
});
----
Such code should be rewritten as a loop, because `Enumerable.All<TSource>` method should be used to determine if all elements satisfy a condition and not to change their state.

=== Exceptions

This rule doesn't report issues on invocations with `out` or `ref` arguments.

=== Noncompliant code example

[source,csharp,diff-id=1,diff-type=noncompliant]
----
data.Where(x => x > 5).Select(x => x * x); // Noncompliant
"this string".Equals("other string"); // Noncompliant

data.All(x =>  // Noncompliant
{
    x.Property = "foo";
    return true;
});

----

=== Compliant solution

[source,csharp,diff-id=1,diff-type=compliant]
----
var res = data.Where(x => x > 5).Select(x => x * x); 
var isEqual = "this string".Equals("other string");

foreach( var x in data)
{
    x.Property = "foo";
}
----


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Use the return value of method "[method name]".


'''
== Comments And Links
(visible only on this page)

=== on 14 Mar 2016, 09:53:02 Dinesh Bolkensteyn wrote:
perhaps we can add some methods on the ``++String++`` class such as ``++ToUpper++``, ``++Substring++``

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
