

include::../noncompliant.adoc[]

include::../compliant.adoc[]

== Exceptions

This rule doesn't raise an exception when the ``return`` statement for a ``void`` function, is itself a ``void`` expression.

----
void foo() {
  // Do stuff ...
}

void bar() {
  return foo();
}
----

== See

* MISRA C:2004, 16.8 - All exit paths from a function with non-void return type shall have an explicit return statement with an expression
* MISRA C++:2008, 8-4-3 - All exit paths from a function with non-void return type shall have an explicit return statement with an expression
* MISRA C:2012, 17.4 - All exit paths from a function with non-void return type shall have an explicit return statement with an expression
* http://cwe.mitre.org/data/definitions/394.html[MITRE, CWE-394] - Unexpected Status Code or Return Value
* https://wiki.sei.cmu.edu/confluence/x/m9YxBQ[CERT, MSC37-C.] - Ensure that control never reaches the end of a non-void function
* https://wiki.sei.cmu.edu/confluence/x/EXs-BQ[CERT, MSC52-CPP.] - Value-returning functions must return a value from all exit paths
* https://wiki.sei.cmu.edu/confluence/x/Cns-BQ[CERT, MSC53-CPP.] - Do not return from a function declared [[noreturn]]
