include::../../summary.adoc[]

== Why is this an issue?

include::../../rationale.adoc[]

include::../../impact.adoc[]

include::../../threats.adoc[]

== How to fix it?

[cols="a,a"]
|===
[source,csharp]
----
using System.Web;
using System.Web.Mvc;

public class Constructor : Controller
{
    [HttpGet]
    public ActionResult Hello(string name, HttpResponse response)
    {
        response.Write(thirdPartyString); // Noncompliant
    }
}
----
|

|===

=== HTML Encoding in .Net Framework 4.8

Several options are available to prevent cross-site scripting injections with
the "System.Web" dll:

* `System.Web.HttpServerUtility.HtmlEncode`
* `System.Web.HttpUtility.HtmlEncode`
* `System.Web.Security.AntiXss.AntiXssEncoder` class methods

You can use the AntiXssEncoder class to override the HttpEncoder class, which
is used by default to encode and decode strings in methods of classes such as
HttpUtility, HttpServerUtility, and HttpResponseHeader.

The difference between the two is negligible because AntiXssEncoder allows you
to switch between named HTML 4.0 entities and numeric entities. For example,
the character `>` ("greater than") would be either `&#62;` or `&gt;`.




[source,csharp]
----
using System.Web;
using System.Web.Mvc;

//Alternative
using System.Web.Security.AntiXss;

public class Constructor : Controller
{
    protected static string doGet(string thirdPartyString, HttpResponse response)
    {
        string cleanThirdPartyString    = HttpUtility.HtmlEncode(thirdPartyString);

        // Alternative
        string altCleanThirdPartyString = AntiXssEncoder.HtmlEncode(thirdPartyString, true);

        response.Write(cleanThirdPartyString);
    }
}
----

=== How does this work?

=== Pitfalls

include::../../common/pitfalls/deny-lists.adoc[]

=== Going the extra mile

include::../../common/extra-mile/csp.adoc[]

== Resources

include::../../common/resources/docs.adoc[]

* https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-6.0[Microsoft, Prevent Cross-Site Scripting (XSS) in ASP.NET Core]

include::../../common/resources/articles.adoc[]

include::../../common/resources/presentations.adoc[]

* https://vcsjones.dev/content-security-policy-nonces-in-asp-net-and-owin/[vcsjones.dev, Content-Security-Policy Nonces in ASP.NET and OWIN]
* http://owin.org/[owin.org, OWIN - Open Web Interface for .NET]

include::../../common/resources/standards.adoc[]


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../../message.adoc[]

include::../../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
