== Why is this an issue?

Outside of the context of an array, explicitly calculating a pointer value will almost never yield the intended result. Even variables declared in the same statement should not be assumed to inhabit sequential memory addresses.


Using an explicitly calculated pointer will have unexpected runtime results as you either read or modify the wrong memory addresses.


Within limits, array indexes are an acceptable form of pointer math _when_ the pointer in question is an array pointer _and_ the array does not hold polymorphic objects/structs. 


=== Noncompliant code example

[source,cpp]
----
void f(char *c) {
  int i = 0;
  int j = 0;
  int *p1 = &i + 1; // Noncompliant: arithmetic not allowed
  int *p2 = &i;
  p2++; // Noncompliant. Presumably intended to point to j. No guarantee that it does.

  char c2 = c[1];  // Noncompliant; not an array context
  char *c3 = c + 1; // Noncompliant: arithmetic not allowed
}
----


=== Exceptions

Because it can be convenient to treat an array as a contiguous set of memory addresses, the increment operator (``{plus}{plus}``) is allowed in an array context.


----
char message[] = "Hello world";  // implicitly null-terminated
char *p;

for (p = message; *p; p++) {  // Compliant
  // do something;
}
----


== Resources

* MISRA C:2004, 17.1
* MISRA C:2004, 17.2
* MISRA C:2004, 17.4
* MISRA {cpp}:2008, 5-0-15
* MISRA {cpp}:2008, 5-0-16
* MISRA {cpp}:2008, 5-0-17
* MISRA C:2012, 18.1
* MISRA C:2012, 18.2
* MISRA C:2012, 18.4
* https://wiki.sei.cmu.edu/confluence/x/1dUxBQ[CERT, ARR37-C.] - Do not add or subtract an integer to a pointer to a non-array object
* https://wiki.sei.cmu.edu/confluence/x/ytYxBQ[CERT, ARR39-C.] - Do not add or subtract a scaled integer to a pointer
* https://wiki.sei.cmu.edu/confluence/x/o3w-BQ[CERT, CTR56-CPP.] - Do not use pointer arithmetic on polymorphic objects



ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::message.adoc[]

'''
== Comments And Links
(visible only on this page)

include::comments-and-links.adoc[]
endif::env-github,rspecator-view[]
