== Why is this an issue?

Having two ``++cases++`` in the same ``++switch++`` statement or branches in the same ``++if++`` structure  with the same implementation is at best duplicate code, and at worst a coding error. If the same logic is truly needed for both instances, then they should be combined.

=== Noncompliant code example

[source,swift]
----
switch i {
  case 1: 
    doFirstThing()
    doSomething()
  case 2: 
    doSomethingDifferent()
  case 3:  // Noncompliant; duplicates case 1's implementation
    doFirstThing()
    doSomething() 
  default: 
    doTheRest()
}

if a >= 0 && a < 10 {
  doFirstThing()
  doTheThing()
} else if a >= 10 && a < 20 {
  doTheOtherThing()
} else if a >= 20 && a < 50 {
  doFirstThing()     // Noncompliant; duplicates first condition
  doTheThing() 
} else {
  doTheRest()
}
----

=== Exceptions

``++case++`` labels that declare variables cannot have multiple patterns. Therefore this situation is ignored.

[source,swift]
----
switch a {
    case .STR_CASE(let x):
        print(x)
    case .INT_CASE(let x):
        print(x)
    default:
        print("default")
}
----

Blocks in an ``++if++`` chain that contain a single line of code are ignored, as are blocks in a ``++switch++`` statement that contain a single line of code with or without a following ``++break++``.


[source,swift]
----
if a >= 0 && a < 10 {    //no issue, usually this is done on purpose to increase the readability
  doTheThing()
} else if a >= 10 && a < 20 {
  doTheThing()
} else if a >= 20 && a < 50 {
  doFirstThing()
} 
----

But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++switch++``-es without default clauses when all branches have the same single line of code. In case of ``++if++`` chains with ``++else++``-s, or of ``++switch++``-es with default clauses, rule S3923 raises a bug. 

[source,swift]
----
if a >= 0 && a < 10 {     //Noncompliant, this might have been done on purpose but probably not
  doTheThing()
} else if a >= 10 && a < 20 {
  doTheThing()
}
----

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

include::../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
