=== relates to: S2095

=== is related to: S2952

=== on 13 May 2015, 19:22:06 Ann Campbell wrote:
\[~tamas.vajk] if this rule comes from R#, please provide the R# rule key.

Also, there is the question of classes that ``++Dispose++`` of their ``++IDisposable++`` members, but not from their own ``++Dispose++`` methods. I.e. they call ``++Dispose++`` from some other, randomly-named method. Does this case merit coverage under this rule? A separate rule?

=== on 13 May 2015, 19:22:15 Ann Campbell wrote:
consulted: \http://stackoverflow.com/questions/10956140/does-a-class-need-to-implement-idisposable-when-all-members-are-explicitly-dispo

=== on 18 May 2015, 08:20:57 Tamas Vajk wrote:
\[~ann.campbell.2] I think the separate rule for "implementing IDisposable" (\http://jira.sonarsource.com/browse/RSPEC-2931) is a good idea. Let's keep it this way, we'll see if it generates loads of duplicate issues or not.


This rule is not in Resharper.




=== on 22 May 2015, 09:48:19 Tamas Vajk wrote:
LGTM

=== on 8 Jun 2015, 13:51:45 Ann Campbell wrote:
updated per SONARCSANA-129. See what you think [~tamas.vajk]

=== on 12 Jun 2015, 12:28:01 Tamas Vajk wrote:
\[~ann.campbell.2] it looks good. I added the exceptions part, could you run through it?

=== on 12 Jun 2015, 18:02:36 Ann Campbell wrote:
This begins to feel like a game of tennis. :-)


I edited "block" to "method". Double-check me, please.

=== on 15 Jun 2015, 06:28:58 Tamas Vajk wrote:
\[~ann.campbell.2] It looks good.

=== on 5 Feb 2021, 17:35:39 Čaba Šagi wrote:
Beside the types covered in the description, all types implementing IDisposable should be covered as well. See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000[CA2000]

