== Why is this an issue?

If a private member of the class is declared but not used in the program, it can be considered dead code and should therefore be removed. This will improve maintainability because developers will not wonder what the variable is used for.

The private class members were introduced in ES2022 and use `#` hash symbol prefix. It is possible to declare private fields, methods, getters and setters as well as their static counterparts.

[source,javascript,diff-id=1,diff-type=noncompliant]
----
class MyClass {
    #privateField; // Noncompliant, #privateField is unused
    #privateMethod(){} // Noncompliant, #privateMethod is unused
    // ...
}
----

To fix the code remove unused private member of the class.

[source,javascript,diff-id=1,diff-type=compliant]
----
class MyClass {
    // ...
}
----

== Resources
=== Documentation
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields[MDN - private class members]
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes[MDN - classes overview]


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
