== Why is this an issue?
XSLT Injection is a security vulnerability that occurs when an application uses
untrusted user input to construct an XSLT (Extensible Stylesheet Language
Transformations) stylesheet. XSLT engines are powerful templating tools
designed to transform XML documents

=== What is the potential impact?

An attacker can provide malicious XSLT code that the application's XML processor
will then execute, such as references to other files, embedded scripts, or
special objects.

Below are some real-world scenarios that illustrate some impacts of an attacker
exploiting the vulnerability.

==== Reading Sensitive Files
The most common impact of XSLT Injection is the ability to read files from the
server's file system. XSLT has built-in functions that can access local or
remote XML files. An attacker can use this function to read sensitive
information.

==== Attacking Other Systems
Attackers can use XSLT Injection to force the server to make network requests
to other systems on the internal network that are not accessible from the
internet.

This could allow an attacker to:
* Scan the internal network for open ports and active services.
* Access internal, unprotected administrative panels.
* Interact with cloud provider metadata services to steal access credentials.

==== Denial of Service
A malicious stylesheet can also be designed to consume a large amount of server
resources, such as memory or CPU time. This can cause the application to slow
down or crash, making it unavailable for legitimate users. +
An attacker could create a recursive stylesheet that never finishes, causing
the processor to enter an infinite loop and exhaust all available CPU
resources.

== How to fix it

=== Code examples

==== Noncompliant code example

[source,csharp]
----
[ApiController]
[Route("Example")]
public class ExampleController : ControllerBase
{
    [HttpGet("example")]
    public IActionResult Process([FromQuery] string xslt)
    {
        var transform = new XslCompiledTransform();
        const string inputXml = "<root><msg>Hello</msg></root>";

        using (var xsltReader = XmlReader.Create(new StringReader(xslt)))
        {
            transform.Load(xsltReader); // Noncompliant
        }

        using var stringWriter = new StringWriter();
        using (var xmlReader = XmlReader.Create(new StringReader(inputXml)))
        {
            transform.Transform(xmlReader, null, stringWriter);
        }

        return Content(stringWriter.ToString(), "application/xml");
    }
}
----

==== Compliant solution

These security issues can be mitigated by not accepting XslTransform objects,
XSLT style sheets, or XML source data from untrusted sources.

== Resources
=== Standards

* OWASP - https://owasp.org/Top10/A03_2021-Injection/[Top 10 2021 Category A3 - Injection]
* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[Top 10 2017 Category A1 - Injection]
* OWASP - https://owasp.org/www-project-mobile-top-10/2023-risks/m4-insufficient-input-output-validation[Mobile Top 10 2024 Category M4 - Insufficient Input/Output Validation]
* CWE - https://cwe.mitre.org/data/definitions/20[CWE-20 - Improper Input Validation]
* STIG Viewer - https://stigviewer.com/stigs/application_security_and_development/2024-12-06/finding/V-222609[Application Security and Development: V-222609] - The application must not be subject to input handling vulnerabilities.

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Change this code to not construct XSLT Transforms directly from user-controlled data.

=== Highlighting

"[varname]" is tainted (assignments and parameters)

this argument is tainted (method invocations)

the returned value is tainted (returns & method invocations results)

'''

endif::env-github,rspecator-view[]
