In Kubernetes, using a fixed tag or the SHA of a container image is important rather than floating tags like  `latest`, `head`, or `canary`. This practice ensures that your deployments are predictable and consistent, reducing the risk of unexpected behavior in the application.

== Why is this an issue?

Using floating tags in Kubernetes container images can lead to issues. These tags do not refer to a fixed version of an image, which means that different deployments might use different versions of the image, leading to inconsistencies and unpredictability. This lack of control and traceability can compromise an application's stability, reliability, and security.


=== What is the potential impact?

**Unpredictable Behavior:** Floating tags point to different image versions at different times. This means that different image versions could get pulled at different times, leading to unpredictable behavior in the application. For instance, a feature that worked yesterday might suddenly stop working today because the 'latest' tag now points to a new version of the image.

**Lack of Traceability:** When a floating tag is used, it becomes challenging to trace which version of the image is running in the environment at any given time. This lack of traceability can make debugging and troubleshooting issues more difficult.

**Security Risks:** Floating tags can also expose an application to security risks. If a vulnerability is discovered in the image version that the floating tag points to, the application becomes vulnerable, too. Using a fixed tag or SHA allows control of when and how images are updated, allowing reviewing and addressing potential security issues.

**Inconsistent Environments:** If different team members pull the image at different times, they could end up with different image versions due to the floating tag. This inconsistency can lead to "it works on my machine" scenarios, making it harder to collaborate and debug issues.

== How to fix it
Fixed tags or the SHA of the image should always be used in a Kubernetes container image to avoid the issues associated with floating tags. Here's how you can do it:

* Fixed Tags: When pulling an image, specify a fixed tag pointing to a specific image version. This ensures that the same version of the image is always pulled, regardless of when it is done.

* SHA of the Image: SHA of the image can be used for even more control and traceability. This unique identifier corresponds to a specific build of the image.

=== Code examples

==== Noncompliant code example
[source,text,diff-id=1,diff-type=noncompliant]
----
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: firstConatiner
      image: nginx # Noncompliant

    - name: secondContainer
      image: nginx:latest # Noncompliant
----

==== Compliant solution

[source,text,diff-id=1,diff-type=compliant]
----
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
    - name: compliantContainer
      image: nginx:1.14.2 # Compliant, fixed tag

    - name: secondCompliantContainer
      image: nginx@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2 # Compliant, SHA of the image
----

== Resources
=== Documentation
* https://helm.sh/docs/chart_best_practices/pods/#images[Helm chart best practices - Images]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Use a specific version tag for the container image.


=== Highlighting

* Highlight the container image without tag or highlight the image with one of the floating tags.


endif::env-github,rspecator-view[]
