include::../../summary.adoc[]

== Why is this an issue?

include::../../rationale.adoc[]

include::../../impact.adoc[]

include::../../threat.adoc[]

== How to fix it?

In case the response consists of HTML code, it is highly recommended to use a template engine like https://laravel.com/docs/9.x/blade[Blade] to generate it.
A proper template engine does not only separate the view from the business logic and thus results in a more maintainable application.
It also automatically encodes variable output and thus drastically decreases the chance of introducing Cross-Site Scripting vulnerabilities.

If you do not intend to send HTML code to the clients, the vulnerability can be resolved by telling them what data they are receiving.
For example, you can use the `json` method of the `Response` class to safely return JSON messages.
The method automatically sets the content-type to `application/json`.
This tells the browser that the response does not contain HTML code and should not be parsed and interpreted as HTML.
Thus, the response is not vulnerable to reflected Cross-Site Scripting.

[source,php]
----
$response = response()->json(['data' => $input]);
----

It is also possible to set the content-type manually using the `header` method of the `Response` class.
For example, setting the content-type to `text/plain` allows to safely reflect user input since browsers will not try to parse and execute the response.

[source,php]
----
$response = response($input, 200)->header('Content-Type', 'text/plain');
----

== How does this work?

=== Pitfalls

=== Going the extra mile

include::../../resources.adoc[]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../../message.adoc[]

include::../../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../../comments-and-links.adoc[]
endif::env-github,rspecator-view[]
