=== On 2014-11-21T12:28:29Z Freddy Mallet Wrote:
Two questions/remarks:

* Are we talking about private methods or about non-public methods ? If my feeling is correct this rule should only target private methods
* I would tag the rule with the label "spring"
* As this rule is associated to the Reliability characteristic, I think the default severity should be "Critical"

=== On 2014-11-21T13:28:08Z Ann Campbell Wrote:
The Spring docs are pretty clear that only ``++public++`` method can actually be ``++@Transactional++``

=== On 2014-11-21T14:14:44Z Freddy Mallet Wrote:
Ok Ann, so I would replace :


"Therefore marking a private method"


by 


"Therefore marking for instance a private method"


to prevent any misunderstanding

=== On 2018-11-27T13:06:43Z Semyon Danilov Wrote:
\[~ann.campbell.2] Actually, any method can be Transactional if you're using AspectJ compiler, it's stated in the docs https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/transaction.html[here]. The excerpt:


----
Method visibility and @Transactional

When using proxies, you should apply the @Transactional annotation only to methods with public visibility. If you do annotate protected, private or package-visible methods with the @Transactional annotation, no error is raised, but the annotated method does not exhibit the configured transactional settings. Consider the use of AspectJ (see below) if you need to annotate non-public methods.
----

=== On 2018-11-27T13:33:30Z Ann Campbell Wrote:
FYI [~alexandre.gigleux] ^

