In C, a string is just a buffer of characters, usually using the <code>null</code> character as a sentinel for the end of the string. Which mean that the developer has to be aware of low level details such as buffer sizes, having an extra character to store the final null character... Doing that correctly and consistently is notoriously difficult, and any error can lead to a security vulnerability, for instance giving access to sensitive data, or allowing arbitrary code execution.

The function <code>char *strncpy(char * restrict dest, const char * restrict src, size_t count);</code> copies the first <code>count</code> characters from <code>src</code> to <code>dest</code>, stopping at the first null character, and filling extra space with 0. The <code>wcsncpy</code> does the same for wide characters, and should be used with the same guidelines.

Both of those functions are designed to work with fixed length strings, and might result in a non null-terminated string.


== Ask Yourself Whether

* There is a possibility that either the source or the destination pointers is null
* The security of your system can be compromised if <code>dest</code> is a truncated version of <code>source</code>
* The <code>source</code> buffer can be both non null-terminated and smaller than count
* The <code>destination</code> buffer can be smaller than count
* You expect <code>dest</code> to be a null-terminated string
* There is an overlap between source and destination

There is a risk if you answered yes to any of those questions.


== Recommended Secure Coding Practices

* C11 provides, in its annex K, the <code>strncpy_s</code> and the <code>wcsncpy_s</code> that were designed as safer alternative to <code>strcpy</code> and <code>wcscpy</code>. It's not recommended to use them in all circumstances, because they introduce a runtime overhead and require to write more code for error handling, but they perform checks that will limit the consequences of calling the function with bad arguments.
* Even if your compiler does not exactly support annex K, you probably have access to similar functions
* If you are using <code>strncpy</code> and <code>wsncpy</code> as a safer version of <code>strcpy</code> and <code>wcscpy</code>, you should instead consider <code>strcpy_s</code> and <code>wcscpy_s</code>, because these functions have several shortcomings:
** It's not easy to detect truncation
** Too much work is done to fill the buffer with 0, leading to non optimal performances
** Unless manually corrected, the <code>dest</code> string might not be null-terminated

* If you want to use <code>strcpy</code> and <code>wcscpy</code> functions and detect if the string was truncated, the pattern is the following:
** Set the last character of the buffer to null
** Call the function
** Check if the last character of the buffer is still null

* If you are writing C++ code, using <code>std::string</code> to manipulate strings is much simpler and less error-prone


== Sensitive Code Example

----
int f(char *src) {
  char dest[256];
  strncpy(dest, src, sizeof(dest)); // Sensitive: might silently truncate
  return doSomethingWith(dest);
}
----


== Compliant Solution

----
int f(char *src) {
  char dest[256];
  dest[sizeof dest - 1] = 0;
  strncpy(dest, src, sizeof(dest)); // Compliant
  if (dest[sizeof dest - 1] != 0) {
    // Handle error
  }
  return doSomethingWith(dest);
}
----


== See

* http://cwe.mitre.org/data/definitions/120[MITRE, CWE-120] - Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')
* https://www.securecoding.cert.org/confluence/x/QwY[CERT, STR07-C.] - Use the bounds-checking interfaces for string manipulation


