_All branches_ includes the default branch, which is the branch executed when none of the conditions of the chain are satisfied. This branch may present itself explicitly, implicitly or by construction.

[source,cpp]
----
if (a > 10) b == 1;
else b == 2; // explicit default branch

int func() {
  if (a > 10) return 1;
  return 2; // implicit default branch
}

int b = a > 10 ? 1 : 2;
                  // ^ default branch by construction
----

== Why is this an issue?

Having all branches of an `if` or `switch` chain or ternary operator with the same implementation indicates a problem, because the conditional structure is not serving any purpose: the same code will be executed regardless of the conditions.

In the following code:

include::../common/code-example.adoc[]

Either there is a copy-paste error, or the `if` or `switch` chain or ternary operator is unecessary.

== How to fix it

Either fix the copy-paste error or remove the conditional structure.

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

include::../highlighting.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
