=== Highlight

For https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ec2/Instance.html[aws_cdk.aws_ec2.Instances]:

* Highlight the `vpc_subnets` property (or dict entry) when set to a selection of public subnets.

For https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_ec2/CfnInstance.html[aws_cdk.aws_ec2.CfnInstance]

* Highlight the `associate_public_ip_address` property when set to `True`

For https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_dms/CfnReplicationInstance.html[aws_cdk.aws_dms.CfnReplicationInstance]

* Highlight the `publicly_accessible` property when set to `True`
* Highlight the constructor code when the `publicly_accessible` property is
    not set

For https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/DatabaseInstance.html[aws_cdk.aws_rds.DatabaseInstance]

* If the `vpc_subnets` attribute contains a public subnet, highlight the 
    `publicly_accessible` property if set to `True`
* Highlight the `vpc_subnets` attribute if it contains a public subnet, and
    the `publicly_accessible` property if not set
* If the `vpc_subnets` public / private state can not be decided,       
    highlight the `publicly_accessible` property if set to `True`

For https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_rds/CfnDBInstance.html[aws_cdk.aws_rds.CfnDBInstance]

* If the `db_subnet_group_name` points to a public subnet, highlight the 
    `publicly_accessible` property if set to `True`
* If the `db_subnet_group_name` public / private state can not be
    decided, highlight the `publicly_accessible` property if set to `True`