The <code>for</code> statement provides a general-purpose looping facility. Using a restricted form of loop makes code easier to review and to analyse.

The three clauses of a for statement are the:
* First clause which should
** be empty, or
** assign a value to the loop counter, or
** define and initialize the loop counter (C99).
* Second clause which should
** be an expression that has no persistent side effects, and
** not use objects that are modified in the for loop body.
* Third clause which should
** be an expression whose only persistent side effect is to modify the value of the loop counter, and
** not use objects that are modified in the for loop body.


== Noncompliant Code Example

----
for( int i = 0 ; i++ < 10 ; i += 1 ) { // Noncompliant, loop counter is updated in the condition
}

for( int i = 0 ; ; ) { // Noncompliant, initialized variable i is not used in the condition
}

for( int i = 0 , j = 0 ; i < 10 ; i += j) { // Noncompliant, j is modified in the body
  j = i + 1;
}
----


== See

* MISRA C:2004, 13.5 - The three expressions of a for statement shall be concerned only with loop control.
* MISRA C++:2008, 6-5-5 - A _loop-control-variable_ other than the _loop-counter_ shall not be modified within _condition_ or _expression_.
* MISRA C:2012, 14.2 - A for loop shall be well-formed

