ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Remove this "virtual" modifier of "xxx".

'''
== Comments And Links
(visible only on this page)

=== on 11 May 2015, 14:49:23 Dinesh Bolkensteyn wrote:
The description sounds like chinese and the compliant solution still includes a ``++// Noncompliant++`` flag

=== on 11 May 2015, 15:31:30 Dinesh Bolkensteyn wrote:
In fact this is quite complex, I've managed to understand the issue only after carefully reading the following article in full:

http://blogs.msdn.com/b/samng/archive/2007/11/26/virtual-events-in-c.aspx

=== on 12 May 2015, 12:23:49 Ann Campbell wrote:
\[~dinesh.bolkensteyn] can you be more specific about what in the description you find unhelpful and/or suggest or make some edits, please?

=== on 12 May 2015, 14:35:46 Dinesh Bolkensteyn wrote:
What is the initial source for this rule [~ann.campbell.2]?

=== on 12 May 2015, 15:45:18 Dinesh Bolkensteyn wrote:
I've tried to give a bit more context and a full example.

=== on 14 May 2015, 12:47:13 Ann Campbell wrote:
I've made some edits [~dinesh.bolkensteyn]. See what you think. 

In particular, I'm not sure about the correct order of the words ``++private++`` and ``++delegate++``. You had ``++delegate++`` ``++private++``, which sounds odd to me in English, so I swapped them. But please swap back if that's the particular order they should appear in.

=== on 18 May 2015, 06:05:30 Dinesh Bolkensteyn wrote:
LGTM!

endif::env-github,rspecator-view[]