=== Duplicate: RSPEC-3045

=== Related: RSPEC-907

=== Related: RSPEC-1439

=== Related: RSPEC-1219

=== On 2013-07-10T09:48:32Z Dinesh Bolkensteyn Wrote:
Implemented by \http://jira.codehaus.org/browse/SONARJAVA-199

=== On 2015-06-16T13:42:28Z Ann Campbell Wrote:
CodePro: Break with Label

=== On 2016-07-19T13:11:44Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] shouldn't we promote "targeted" languages from RSPEC-3045, which was marked as duplicating this one?

=== On 2016-07-20T12:09:03Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] For C#, C, {cpp} and Objective-C we already have RSPEC-907 and for these languages (plus Python) the only way to use labels - is to use "goto", because in contrast with Java, JavaScript, Swift, Groovy and Flex only "goto" statement (not "break" and "continue") can transfer control to a label. From here I'm wondering what we should do with those RSPECs ? Don't know and didn't checked situation in VB.Net, PHP and others.

=== On 2016-07-20T20:30:33Z Ann Campbell Wrote:
\[~evgeny.mandrikov] I've adjusted the languages of both rules, but beyond that I'm not sure there's anything to do with either of them...? I suspect you want to see one deprecated or superceded by the other, but for instance Java and Swift don't have ``++goto++`` and you say C-family languages + C# (I just learned) don't have labels without ``++goto++`` so I think this is a case of different rules for different language mechanisms.

=== On 2016-07-21T10:38:32Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] I wasn't expecting something particular - simply pointed out on this fact and asked your opinion about it ;) I agree with your conclusion and changes.

=== On 2020-01-20T15:09:02Z Tibor Blenessy Wrote:
I removed exception about loops because the exception made the rule equivalent to RSPEC-1439. I also removed it from built-in profiles in JS

