=== On 2015-03-31T15:12:32Z Ann Campbell Wrote:
reassigning to you [~nicolas.peru] because I've updated the formatting in the code samples & I'd like you to double-check me, please.

=== On 2015-04-08T14:59:27Z Nicolas Peru Wrote:
seems ok.

=== On 2016-04-14T10:13:49Z Freddy Mallet Wrote:
I would add the tag 'slf4j' [~ann.campbell.2]

=== On 2016-04-14T15:41:19Z Ann Campbell Wrote:
I disagree [~freddy.mallet]. If this rule were specifically for and only about slf4j then I would, but this covers multiple frameworks.

=== On 2016-11-17T15:41:41Z Tibor Blenessy Wrote:
\[~ann.campbell.2] if we want to support multiple frameworks, how should they be detected? i.e. should every string concatenation in arguments be flagged, or should the method name be used as a heuristic to find out that string concatenation will infer penalty? Other option could be to blacklist well known method signatures? If yes, what are the signatures? 

=== On 2016-11-17T16:17:58Z Ann Campbell Wrote:
\[~tibor.blenessy] that's probably a discussion that's better to have with [~nicolas.peru] or [~michael.gumowski].

