=== On 2015-05-11T12:06:21Z Tamas Vajk Wrote:
I modified the noncompliant-compliant comment in the code. Apart from this, this rule is now implemented for C#

=== On 2015-05-11T13:53:01Z Ann Campbell Wrote:
FYI [~tamas.vajk] there's no need to explicitly mark anything Compliant in the Compliant Solution (updated). 

Thanks for the corrections.

=== On 2015-05-20T15:23:21Z Ann Campbell Wrote:
updated per \http://jira.codehaus.org/browse/SONARCSANA-66

=== On 2015-05-22T09:33:57Z Tamas Vajk Wrote:
Changed the ``++String++`` to ``++string++`` in the samples, but otherwise it LGTM.

=== On 2015-05-29T08:46:38Z Massimo PALADIN Wrote:
\[~tamas.vajk] assigning to you so you remember to change the C# implementation to skip public methods.

=== On 2015-06-03T20:06:41Z Ann Campbell Wrote:
\[~tamas.vajk] I originally wrote this rule for C# & the description included performance reasons. Were those also not appropriate in C#?

=== On 2015-06-04T12:51:45Z Tamas Vajk Wrote:
\[~massimo.paladin] thanks. I checked in the C# implementation that we are filtering out ``++virtual++`` methods.

=== On 2015-06-04T12:57:17Z Tamas Vajk Wrote:
\[~ann.campbell.2] Calling a ``++static++`` method is slightly more performant than calling a non-``++static++`` one, because there is no need to pass the ``++this++`` reference. But the performance difference is tiny if any.


I found this on the topic:

http://stackoverflow.com/questions/12279438/performance-of-static-methods-vs-instance-methods

