include::../description.adoc[]

include::ask-yourself.adoc[]

include::recommended.adoc[]

== Sensitive Code Example

For `Microsoft.Web/sites`:

[source,json,diff-id=1,diff-type=noncompliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Web/sites",
      "apiVersion": "2022-09-01",
      "properties": {
        "httpsOnly": false
      }
    }
  ]
}
----

For `Microsoft.Web/sites/config`:

[source,json,diff-id=2,diff-type=noncompliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Web/sites/config",
      "apiVersion": "2022-09-01",
      "properties": {
        "ftpsState": "AllAllowed"
      }
    }
  ]
}
----

For `Microsoft.Storage/storageAccounts`:

[source,json,diff-id=3,diff-type=noncompliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts",
      "apiVersion": "2022-09-01",
      "properties": {
        "supportsHttpsTrafficOnly": false
      }
    }
  ]
}
----

For `Microsoft.ApiManagement/service/apis`:

[source,json,diff-id=4,diff-type=noncompliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.ApiManagement/service/apis",
      "apiVersion": "2022-08-01",
      "properties": {
        "protocols": ["http"]
      }
    }
  ]
}
----

For `Microsoft.Cdn/profiles/endpoints`:

[source,json,diff-id=5,diff-type=noncompliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Cdn/profiles/endpoints",
      "apiVersion": "2021-06-01",
      "properties": {
        "isHttpAllowed": true
      }
    }
  ]
}
----

For `Microsoft.Cache/redisEnterprise/databases`:

[source,json,diff-id=6,diff-type=noncompliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Cache/redisEnterprise/databases",
      "apiVersion": "2022-01-01",
      "properties": {
        "clientProtocol": "Plaintext"
      }
    }
  ]
}
----

For `Microsoft.DBforMySQL/servers`, `Microsoft.DBforMariaDB/servers`, and `Microsoft.DBforPostgreSQL/servers`:

[source,json,diff-id=7,diff-type=noncompliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.DBforMySQL/servers",
      "apiVersion": "2017-12-01",
      "properties": {
        "sslEnforcement": "Disabled"
      }
    }
  ]
}
----


== Compliant Solution

[source,json,diff-id=1,diff-type=compliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Web/sites",
      "apiVersion": "2022-09-01",
      "properties": {
        "httpsOnly": true
      }
    }
  ]
}
----

For `Microsoft.Web/sites/config`:

[source,json,diff-id=2,diff-type=compliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Web/sites/config",
      "apiVersion": "2022-09-01",
      "properties": {
        "ftpsState": "FtpsOnly"
      }
    }
  ]
}
----

For `Microsoft.Storage/storageAccounts`:

[source,json,diff-id=3,diff-type=compliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts",
      "apiVersion": "2022-09-01",
      "properties": {
        "supportsHttpsTrafficOnly": true
      }
    }
  ]
}
----

For `Microsoft.ApiManagement/service/apis`:

[source,json,diff-id=4,diff-type=compliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.ApiManagement/service/apis",
      "apiVersion": "2022-08-01",
      "properties": {
        "protocols": ["https"]
      }
    }
  ]
}
----

For `Microsoft.Cdn/profiles/endpoints`:

[source,json,diff-id=5,diff-type=compliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Cdn/profiles/endpoints",
      "apiVersion": "2021-06-01",
      "properties": {
        "isHttpAllowed": false
      }
    }
  ]
}
----

For `Microsoft.Cache/redisEnterprise/databases`:

[source,json,diff-id=6,diff-type=compliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Cache/redisEnterprise/databases",
      "apiVersion": "2022-01-01",
      "properties": {
        "clientProtocol": "Encrypted"
      }
    }
  ]
}
----

For `Microsoft.DBforMySQL/servers`, `Microsoft.DBforMariaDB/servers`, and `Microsoft.DBforPostgreSQL/servers`:

[source,json,diff-id=7,diff-type=compliant]
----
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.DBforMySQL/servers",
      "apiVersion": "2017-12-01",
      "properties": {
        "sslEnforcement": "Enabled"
      }
    }
  ]
}
----


include::see.adoc[]
ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

== Message

* Make sure that using clear-text protocols is safe here.

== Highlighting

Highlight the property if available, otherwise the resource.

'''

endif::env-github,rspecator-view[]
