
include::../../../shared_content/secrets/description.adoc[]

== Why is this an issue?

include::../../../shared_content/secrets/rationale.adoc[]

=== What is the potential impact?

Application keys and secrets allow applications to authenticate with Huawei
Cloud services. If an application secret is disclosed, an attacker will be able
to call Huawei Cloud resources with the same privileges as the application.

Below are some real-world scenarios that illustrate some impacts of an attacker
exploiting the secret.

==== Push notification spam

Huawei Push Kit can be used to send push notifications to client applications.
An attacker could use the disclosed application secret to send large numbers of
push notifications to these client applications. This will cause an annoyance
for users of these applications.

If the attacker is able to control the message shown to the user, they may
choose to display messages that the user finds disturbing.

==== Exploiting business logic flaws

Huawei Cloud API Gateway can provide a request authentication mechanism for
server applications. An attacker can use the disclosed application secret to
validly sign requests so that they are able to traverse the API gateway and
reach the server application.

This application may assume that only trusted clients are able to send requests
through the API gateway. For example, the server may assume that all request
data has been validated by the client. An attacker may be able to send requests
that the server does not expect, which may allow them to trigger flaws in the
business logic and put the server application into an unexpected state.

==== Financial loss

Cloud providers charge for their services based on their usage. This may be
based on the number of API calls made, bandwidth, or how many server instances
are running.

An attacker can use a disclosed secret to send large numbers of requests to the
cloud provider. This can lead to a large and unexpected increase in cloud
provider costs.

==== Denial of service

For server applications running on Huawei Cloud, an attacker may be able to send
more requests than the application is able to handle. This can result in a
denial of service for all users of that application.

The cloud provider may also monitor requests to identify unusual usage activity.
If an attacker is able to send enough requests, the cloud provider may flag your
account and take action against it. This could lead to the suspension or
termination of your account, thus causing significant inconvenience and
disruption for your customers or partners.

== How to fix it

include::../../../shared_content/secrets/fix/revoke.adoc[]

include::../../../shared_content/secrets/fix/vault.adoc[]

=== Code examples

:example_secret: 2bcd82072fdd4d396eadd7095a27c0f2f93d527618605a631107fb75026b59cb
:example_name: huawei-cloud.app-secret
:example_env: HUAWEI_CLOUD_APP_SECRET

include::../../../shared_content/secrets/examples.adoc[]

//=== How does this work?

//=== Pitfalls

//=== Going the extra mile

== Resources

=== Documentation

* Huawei Developer Documentation - https://developer.huawei.com/consumer/en/doc/HMSCore-Guides/oauth2-0000001212610981[OAuth 2.0-based Authentication]
* Huawei Cloud Documentation - API Gateway: https://support.huaweicloud.com/intl/en-us/usermanual-apig/apig-ug-180307049.html[Creating an App and Obtaining Authorization]

include::../../../shared_content/secrets/resources/standards.adoc[]

//=== Benchmarks
