
include::../../../shared_content/secrets/description.adoc[]

== Why is this an issue?

include::../../../shared_content/secrets/rationale.adoc[]

=== What is the potential impact?

Application keys and secrets allow applications to authenticate with the Huawei
Cloud application gateway. The application secret is used to calculate a
signature on every request which is then verified by the gateway. Only requests
with a valid signature are passed to the application server.

If an application secret is disclosed, an attacker will be able to create valid
request signatures and send requests through the application gateway. Below are
some real-world scenarios that illustrate some impacts of an attacker exploiting
the application secret.

==== Exploiting assumptions made during development

The developers of the server-side application may expect that only requests from
trusted client applications can be received. They may make assumptions about
the data that is received, for example, that all of the data has been validated.

An attacker can exploit these assumptions to identify and exploit flaws in the
application code. For example, the attacker may send a combination of inputs
that are not allowed by the client application. The attacker may be able to
bypass business logic for personal gain or may be able to put the server into
an inconsistent state.

==== Denial of service

An attacker will be able to send large numbers of requests through the
application gateway. This can cause excessive resource usage on the server,
possibly resulting in a denial of service.

==== Financial loss

If the server is configured to automatically scale based on traffic, large
numbers or requests may cause additional server instances to be started.
Financial losses can occur due to the cost of these additional server instances.

== How to fix it

include::../../../shared_content/secrets/fix/revoke.adoc[]

include::../../../shared_content/secrets/fix/vault.adoc[]

=== Code examples

:example_secret: 2bcd82072fdd4d396eadd7095a27c0f2f93d527618605a631107fb75026b59cb
:example_name: huawei-cloud.app-secret
:example_env: HUAWEI_CLOUD_APP_SECRET

include::../../../shared_content/secrets/examples.adoc[]

//=== How does this work?

//=== Pitfalls

//=== Going the extra mile

== Resources

=== Documentation

* Huawei Cloud Documentation - https://support.huaweicloud.com/intl/en-us/usermanual-apig/apig-ug-180307049.html[Creating an App and Obtaining Authorization]

include::../../../shared_content/secrets/resources/standards.adoc[]

//=== Benchmarks
