=== deprecates: S1950

=== is related to: S1763

=== is related to: S901

=== is related to: S2760

=== on 12 Feb 2015, 07:23:25 Nicolas Peru wrote:
\[~ann.campbell.2]I am updating example and message for Java as a switch with twice the same case won't compile cf \http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.11 

"No two of the case constants associated with the switch statement have the same value."

=== on 12 Feb 2015, 13:48:06 Ann Campbell wrote:
\[~nicolas.peru] I've updated the title for Java as well

=== on 6 Apr 2015, 13:26:06 Evgeny Mandrikov wrote:
\[~ann.campbell.2] same for C-Family as for Java, in fact I suppose that majority of languages forbids duplicate "cases" and minority allows, so might be better to do opposite - generalize "if" and specialize "switch"

=== on 9 Apr 2015, 16:16:33 Ann Campbell wrote:
\[~evgeny.mandrikov] laborious cleanup done to make sure each language has the right title and right description details for the language features.


| |if|switch w/dup cond|break|

|Java|x|-||

|C-Family|x|-||

|JavaScript|x|x|x|

|PHP'|x|x|x|

|PL/SQL|x|x|-|

|Cobol|x|x|-|

|Swift|x|x|-|

|Python|x|-||

|C#|x|-|

=== on 10 Apr 2015, 07:52:36 Evgeny Mandrikov wrote:
Thanks [~ann.campbell.2]!

=== on 9 Mar 2018, 11:27:19 Tibor Blenessy wrote:
Just a note: for Go compiler may disallow some trivial duplicated conditions in ``++case++`` clauses, but it is possible in general. \https://golang.org/ref/spec#Switch_statements 

