=== Deprecate: RSPEC-1950

=== Related: RSPEC-1763

=== Relates: RSPEC-901

=== Relates: RSPEC-2760

=== On 2015-02-12T07:23:25Z Nicolas Peru Wrote:
\[~ann.campbell.2]I am updating example and message for Java as a switch with twice the same case won't compile cf \http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.11 

"No two of the case constants associated with the switch statement have the same value."

=== On 2015-02-12T13:48:06Z Ann Campbell Wrote:
\[~nicolas.peru] I've updated the title for Java as well

=== On 2015-04-06T13:26:06Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] same for C-Family as for Java, in fact I suppose that majority of languages forbids duplicate "cases" and minority allows, so might be better to do opposite - generalize "if" and specialize "switch"

=== On 2015-04-09T16:16:33Z Ann Campbell Wrote:
\[~evgeny.mandrikov] laborious cleanup done to make sure each language has the right title and right description details for the language features.


| |if|switch w/dup cond|break|

|Java|x|-||

|C-Family|x|-||

|JavaScript|x|x|x|

|PHP'|x|x|x|

|PL/SQL|x|x|-|

|Cobol|x|x|-|

|Swift|x|x|-|

|Python|x|-||

|C#|x|-|

=== On 2015-04-10T07:52:36Z Evgeny Mandrikov Wrote:
Thanks [~ann.campbell.2]!

=== On 2018-03-09T11:27:19Z Tibor Blenessy Wrote:
Just a note: for Go compiler may disallow some trivial duplicated conditions in ``++case++`` clauses, but it is possible in general. \https://golang.org/ref/spec#Switch_statements 

