=== Related: RSPEC-6233

=== On 2019-08-28T22:11:53Z Loïc Joly Wrote:
\[~geoffray.adde] Could you please review my changes?

=== On 2019-09-09T20:33:40Z Ann Campbell Wrote:
\[~geoffray.adde], [~loic.joly] this seems remarkably similar to RSPEC-1902 to me. And related to RSPEC-997. I suggest this be made a subtask of RSPEC-1902. 


Also Geoffray, the Exceptions section should come after the code samples, and the text of an exception should describe (only) when and issue would normally be expected but will not be raised. This exception text is broader than that. The second sentence should be relocated into the description and the first should probably be sharpened from "are fine to use" to "will be ignored".




=== On 2019-09-10T10:27:26Z Loïc Joly Wrote:
I'm not sure the issues with global variables are the same in {cpp} and in RPG... Could you please tell what would be the advantage of handling this as a subtask that has nothing in common with the main task? I know so disadvantages (for instances, RulesAPI has some issues when it comes to handling those sub-tasks), and since the rule ID is hidden from the user, I don't see the point...


As for RSPEC-997, it's not really related, since a namespace can also hold global variables.


I removed the exception section (there will be nothing specific in the rule about those, since issues would be raised in system headers, and those are systematically ignored.

=== On 2019-09-10T18:51:45Z Ann Campbell Wrote:
\[~loic.joly] if it truly "has nothing in common with the main task" then there is no advantage. But I don't think that's the case. In this instance, what I see is two currently-independent rules that deal with "global variables Bad!" and it makes sense to me to centralize that theme under one RSpec. In terms of the rule id, it should always be that of the top-level spec, so I don't understand how anything would be hidden. I also don't understand what disadvantages you see from the RuleAPI side. 

=== On 2019-09-10T20:07:24Z Loïc Joly Wrote:
When I said the rule ID is hidden, I meant it's not displayed in rules.sonarsource.com, and is not displayed visibly in the UI for sonarqube. From a user perspective, the only element that links the rule for {cpp} and the rule for RPG is the ruleId that we don't want out users to use. This is why I don't understand the benefits of this added complexity.


On RuleAPI: Reading the ``++See++`` section to fill standards and put labels automatically does not work with subtasks.


And if someone adds a section for one language in the main rules, it may silently appear for other languages too...




=== On 2019-10-10T15:44:17Z Geoffray Adde Wrote:
\[~loic.joly], I like your version. I tend to be a bit more on your side about creating subtasks or not but I do think that it would be good to have common good practice about it.

