It is common for code to have unnecessary variable assignments.

== Why is this an issue?

Unnecessary variable assignments create extra lines of code that can make code harder to read and maintain. By avoiding these redundant assignments, your code will be more efficient and easier to understand. 

== How to fix it
//== How to fix it in FRAMEWORK NAME

=== Code examples

==== Noncompliant code example

In this example, i is declared and assigned a value of 0. The value of i is immediately replaced with a value of 1 and then again with a value of 2.

[source,kotlin]
----
var i = 0 // Noncompliant, useless initializer, will be overwritten in the next line
i = 1 // Noncompliant, the value will be overwritten in the next line
i = 2 
----

==== Compliant solution

The code can be simplified by assigning i the value of 2 when it is declared.

[source,kotlin]
----
var i = 2 
----

==== Noncompliant code example

To expand on the previous example, we have added in a read-only variable j, which is assigned the value of i++. Since i++ is the post-increment operator, the value of i is first used for the assignment, and then incremented by 1. Thus the value of j is 2.

[source,kotlin]
----
var i = 2 
...
val j = i++ // Noncompliant, result of 'i++' increment is never used

println(j)
----

==== Compliant solution

By removing the use of the redundant post-increment operator the code is nor easier to read and avoid unnecessary operations.

[source,kotlin]
----
var i = 2 
...
val j = 2

println(j)

----

== Resources

=== Documentation
* https://kotlinlang.org/docs/basic-syntax.html[Basic syntax in Kotlin]
* https://kotlinlang.org/docs/operator-overloading.html#increments-and-decrements[Increment and decrement operators]
