The functions "tmpnam", "tmpnam_s" and "tmpnam_r" are all used to return a file name that does not match an existing file, in order for the application to create a temporary file. However, even if the file did not exist at the time those functions were called, it might exist by the time the application tries to use the file name to create the files. This has been used by hackers to gain access to files that the application believed were trustworthy.


There are alternative functions that, in addition to creating a suitable file name, create and open the file and return the file handler. Such functions are protected from this attack vector and should be preferred. About the only reason to use these functions would be to create a temporary folder, not a temporary file.


Additionally, these functions might not be thread-safe, and if you don't provide them buffers of sufficient size, you will have a buffer overflow.


== Ask Yourself Whether

* There is a possibility that several threads call any of these functions simultaneously
* There is a possibility that the resulting file is opened without forcing its creation, meaning that it might have unexpected access rights
* The buffers passed to these functions are respectively smaller than
** ``++L_tmpnam++`` for ``++tmpnam++``
** ``++L_tmpnam_s++`` for ``++tmpnam_s++``
** ``++L_tmpnam++`` for ``++tmpnam_r++``

There is a risk if you answered yes to any of those questions.


== Recommended Secure Coding Practices

* Use a function that directly opens the temporary file, such a ``++tmpfile++``, ``++tmpfile_s++``, ``++mkstemp++`` or ``++mkstemps++`` (the last two allow more accurate control of the file name).
* If you can't get rid of these functions, when using the generated name to open the file, use a function that forces the creation of the file and fails if the file already exists.


== Sensitive Code Example

----
int f(char *tempData) {
  char *path = tmpnam(NULL); // Sensitive
  FILE* f = fopen(tmpnam, "w");
  fputs(tempData, f);
  fclose(f);
}
----


== Compliant Solution

[source,cpp]
----
int f(char *tempData) {
  // The file will be opened in "wb+" mode, and will be automatically removed on normal program exit
  FILE* f = tmpfile(); // Compliant
  fputs(tempData, f);
  fclose(f);
}
----


== See

* https://owasp.org/Top10/A01_2021-Broken_Access_Control/[OWASP Top 10 2021 Category A1] - Broken Access Control
* https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/[OWASP Top 10 2021 Category A6] - Vulnerable and Outdated Components
* https://owasp.org/www-project-top-ten/2017/A9_2017-Using_Components_with_Known_Vulnerabilities[OWASP Top 10 2017 Category A9] - Using Components with Known Vulnerabilities
* https://cwe.mitre.org/data/definitions/377[MITRE, CWE-377] - Insecure Temporary File
* https://wiki.sei.cmu.edu/confluence/display/c/CON33-C.+Avoid+race+conditions+when+using+library+functions[CERT, CON33-C.] - Avoid race conditions when using library functions
* https://wiki.sei.cmu.edu/confluence/display/c/FIO21-C.+Do+not+create+temporary+files+in+shared+directories[CERT, FIO21-C.] - Do not create temporary files in shared directories



ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Make sure use of "strncat" is safe here.


'''
== Comments And Links
(visible only on this page)

=== is related to: S5814

endif::env-github,rspecator-view[]
