== Why is this an issue?

When using a regular expression, a capturing group provides extra information about the matched pattern. Named groups will store the matched contents on the `groups` property of the returned matches.

This rule raises issues every time named groups are:

* defined but never called anywhere in the code through their name;
* defined but called elsewhere in the code by their number instead;
* referenced while not defined.


=== Noncompliant code example

[source,java]
----
String date = "01/02";

Pattern datePattern = Pattern.compile("(?<month>[0-9]{2})/(?<year>[0-9]{2})"); 
Matcher dateMatcher = datePattern.matcher(date);

if (dateMatcher.matches()) {
  checkValidity(dateMatcher.group(1), dateMatcher.group(2));  // Noncompliant - numbers instead of names of groups are used
  checkValidity(dateMatcher.group("day")); // Noncompliant - there is no group called "day"
}

// ...

String score = "14:1";

Pattern scorePattern = Pattern.compile("(?<player1>[0-9]+):(?<player2>[0-9]+)"); // Noncompliant - named groups are never used
Matcher scoreMatcher = scorePattern.matcher(score);

if (scoreMatcher.matches()) {
  checkScore(score);
}
----


=== Compliant solution

[source,java]
----
String date = "01/02";

Pattern datePattern = Pattern.compile("(?<month>[0-9]{2})/(?<year>[0-9]{2})");
Matcher dateMatcher = datePattern.matcher(date);

if (dateMatcher.matches()) {
  checkValidity(dateMatcher.group("month"), dateMatcher.group("year"));
}

// ...

String score = "14:1";

Pattern scorePattern = Pattern.compile("(?<player1>[0-9]+):(?<player2>[0-9]+)");
Matcher scoreMatcher = scorePattern.matcher(score);

if (scoreMatcher.matches()) {
  checkScore(scoreMatcher.group("player1"));
  checkScore(scoreMatcher.group("player2"));
}
----
Or, using dedicated variables instead of group names:

[source,java]
----
String score = "14:1";

String player = "([0-9]+)";
String gameScore = player + ":" + player;

Pattern scorePattern = Pattern.compile(gameScore);
Matcher scoreMatcher = scorePattern.matcher(score);

if (scoreMatcher.matches()) {
  checkScore(score);
}
----

== Resources

=== Documentation

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions[MDN - Regular expressions]
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences[MDN - Groups and backreferences]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

* not used: Use the named groups of this regex or remove the names
* numbers are used: Directly use 'name' instead of its number


=== Highlighting

* not used: the regex
* numbers are used: 
** primary: the number
** secondary: the corresponding group in the regex


endif::env-github,rspecator-view[]
