This vulnerability exposes the system to various operation overloads, either
leading to technical denial of service, and/or business disruptions.

== Why is this an issue?

In the context of an application vulnerable to loop boundary injection: +
After discovering the injection point, attackers insert data into the
vulnerable field to either make the affected component inaccessible, to
attempt functional disruptions, or to read from an artifact beyond the
developper's intended bounds.

In low-level languages, this vulnerability might result in over-reads or
over-writes and could have worse consequences.

=== What is the potential impact?

==== Self Denial of service

If the component jeopardized by this vulnerability is not a bottleneck that
acts as a single point of failure (SPOF) within the application, the denial of
service might only affect the attacker who initiated it.

Such benign denial of service can also occur in architectures that rely heavily
on containers and container orchestrators. Replication systems would detect the
failure of a container and automatically replace it.

include::../../../shared_content/appsec/high_impact_dos.adoc[]

== How to fix it

=== Code examples

==== Noncompliant code example

[source,csharp,diff-id=1,diff-type=noncompliant]
----
public class ExampleController : Controller
{
    public IActionResult Compute(int data)
    {
        for (int i = 0; i < data; i++) // Noncompliant
        {
            Console.WriteLine("Hello");
        }

        return Ok();
    }
}
----

==== Compliant solution

[source,csharp,diff-id=1,diff-type=compliant]
----
public class ExampleController : Controller
{
    public static int MAX_BOUNDARY = 1337;
    public static int MIN_BOUNDARY = 1;

    public IActionResult Compute(int data)
    {
        
        if (MIN_BOUNDARY > data)
        {
            data = MIN_BOUNDARY;
        }
        else if (data > MAX_BOUNDARY)
        {
            data = MAX_BOUNDARY;
        }

        for (int i = 0; i < data; i++)
        {
            Console.WriteLine("Hello");
        }

        return Ok();
    }
}
----

=== How does this work?

//=== Pitfalls

//=== Going the extra mile

//== Resources
//=== Documentation
//=== Articles & blog posts
//=== Conference presentations
//=== Standards
//=== External coding guidelines
//=== Benchmarks
