== Why is this an issue?

`printf` format strings contain placeholders, represented by special characters such as "%s". These placeholders are replaced at runtime with values.

Because `printf` format strings are interpreted at runtime rather than validated by the compiler, they can contain errors that result in the wrong string being created. This rule checks whether the format string specifiers of `printf` can be correctly matched with one of the corresponding arguments.

Starting with {cpp}20, `std::format` should be preferred, as it is more readable and validated at compile-time, making it more secure. Rule S6494 covers that.

This rule is about errors that produce an unexpected string. For errors that will create undefined behavior, see the related rule S2275.

Detected problems are:

* Unused arguments
+
[source,cpp]
----
printf("Numbers: %d", 1, 2); // Noncompliant: the second argument "2" is unused
----

* Ignored flags
+
[source,cpp]
----
printf("Formatted number: %0-f", 1.2); // Noncompliant: flag "0" is ignored because of "-"
----

This rule considers only format strings provided as string literals.

== How to fix it

A `printf` format string contains placeholders, replaced by values when the string is printed or logged. Mismatch in the format specifiers and the arguments provided can create incorrect strings.

To avoid issues, developers should ensure that the provided arguments match format specifiers. If possible, `std::format` from {cpp}20 should be preferred.

=== Code examples

==== Noncompliant code example

[source,cpp,diff-id=1,diff-type=noncompliant]
----
printf("Numbers: %d", 1, 2); // Noncompliant: the second argument "2" is unused
printf("Formatted number: %0-f", 1.2); // Noncompliant: flag "0" is ignored because of "-"
----

==== Compliant solution

With `std::format` and `std::print`:

[source,cpp,diff-id=1,diff-type=compliant]
----
std::cout << std::format("Numbers: {} {}", 1, 2);
std::print("Formatted number: {:f}", 1.2);
----

With `printf`:

[source,cpp,diff-id=1,diff-type=compliant]
----
printf("Numbers: %d %d", 1, 2);
printf("Formatted number: %-f", 1.2);
----

== Resources

=== Documentation

* {cpp} reference - https://en.cppreference.com/w/cpp/io/c/fprintf[`printf`]
* {cpp} reference - https://en.cppreference.com/w/cpp/utility/format/format[`std::format` from {cpp}20]
* {cpp} reference - https://en.cppreference.com/w/cpp/io/print[`std::print` from {cpp}23]

=== Standards

* https://wiki.sei.cmu.edu/confluence/x/J9YxBQ[CERT, FIO47-C.] - Use valid format strings

=== Related rules

* S6494 - {cpp} formatting functions should be used instead of C printf-like functions

* S2275 - Printf-style format strings should not lead to unexpected behavior at runtime

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
