This rule raises an issue when a class implements the interface `java.lang.Cloneable`,
but does not override the `Object.clone()` method.

== Why is this an issue?

`Cloneable` is a _marker interface_ that asserts that the `Object.clone` method can be called
on an instance of a class to create a consistent copy of that instance.
Note that the `Cloneable` interface does not define the `Object.clone` method,
but it is defined by class `Object`.
The interface just creates a contract about the class' behavior.

As is the general problem with marker interfaces, this contract without API cannot be enforced by the compiler.
However, when a class does not override `Object.clone`, it is highly likely
that it violates that contract for the `Cloneable` interface.
Therefore, the convention is to override the `Object.clone` method in classes
that implement the `Cloneable` interface.

== How to fix it

Consider the following example:

[source,java,diff-id=1,diff-type=noncompliant]
----
class Foo implements Cloneable { // Noncompliant, override `clone` method
  public int value;
}
----

Override the `clone` method in class `Foo`.
By convention, it must call `super.clone()`.
Because at this point, we know that:

- By behavioral contract, `Object.clone` will not throw a `CloneNotSupportedException`, because `Foo` implements `Cloneable`.
- The returned object is an instance of class `Foo`

We can narrow down the return type of `clone` to `Foo` and handle the `CloneNotSupportedException` inside the function instead of throwing it:

[source,java,diff-id=1,diff-type=compliant]
----
class Foo implements Cloneable { // Compliant

  public int value;

  @Override
  public Foo clone() {
    try {
      return (Foo) super.clone();
    } catch (CloneNotSupportedException e) {
      throw new AssertionError();
    }
  }
}
----

Be aware that `super.clone()` returns a one-by-one copy of the fields of the original instance.
This means that in our example, the `Foo.value` field is not required to be explicitly copied
in the overridden function.
If this is not wanted, for example, because some fields are unique per instance,
or you want to have a deep-copy behavior for some fields,
these fields must be patched after `clone`:

[source,java]
----
class Entity implements Cloneable {

  public int id; // unique per instance
  public List<Entity> children; // deep copy wanted

  @Override
  public Entity clone() {
    try {
      Entity copy = (Entity) super.clone();
      copy.id = System.identityHashCode(this);
      copy.children = children.stream().map(Entity::clone).toList();
      return copy;
    } catch (CloneNotSupportedException e) {
      throw new AssertionError();
    }
  }
}
----

Be aware that the `Cloneable` / `Object.clone` approach has several drawbacks:

- `Cloneable` is a marker interface without API but with a contract about class behavior that the compiler cannot enforce.
- `Object.clone` throws a `CloneNotSupportedException`, which must either be handled or rethrown by your class' `clone` implementation.
- The implementation of `clone` requires a call to `super.clone()` with a type cast for the target type (`return (Foo) super.clone()`

You might, therefore, also consider resorting to other solutions,
such as a custom `copy` method or a copy constructor:

[source,java]
----
class Entity implements Cloneable {

  public int id; // unique per instance
  public List<Entity> children; // deep copy wanted

  Entity(Entity template) {
    id = System.identityHashCode(this);
    children = template.children.stream().map(Entity::new).toList();
  }
}
----

== Resources

=== Documentation

* https://docs.oracle.com/javase/8/docs/api/java/lang/Cloneable.html[Interface Cloneable - Java™ Platform, Standard Edition 8 API Specification]
* https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#clone--[Object.clone - Java™ Platform, Standard Edition 8 API Specification]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Add a "clone()" method to this class.

'''
== Comments And Links
(visible only on this page)

=== is related to: S2975

endif::env-github,rspecator-view[]
