Using host operating system namespaces can lead to compromise of the host system. +
Opening network services of the local host system to the container creates a new attack surface for attackers.

Host network sharing could provide a significant performance advantage for
workloads that require critical network performance. However, the successful
exploitation of this attack vector could have a catastrophic impact on
confidentiality within the host.

include::./ask-yourself.adoc[]

include::../recommended.adoc[]

== Sensitive Code Example

[source,docker]
----
# syntax=docker/dockerfile:1.3
FROM example
# Sensitive
RUN --network=host wget -O /home/sessions http://127.0.0.1:9000/sessions
----

== Compliant Solution

[source,docker]
----
# syntax=docker/dockerfile:1.3
FROM example
RUN --network=none wget -O /home/sessions http://127.0.0.1:9000/sessions
----

include::./see.adoc[]

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Make sure it is safe to use the host operating system namespace here.

=== Highlighting

Highlight `--network=host`.

endif::env-github,rspecator-view[]

