To fix the vulnerability of disabled hostname validation, it is strongly
recommended to first re-enable the default validation.

To avoid running into problems with invalid hostnames, consider the following
sections.

==== Use valid certificates

If hostname validation failure prevents connection to the target server, keep
in mind that **one system's code should not work around another system's problems**,
as this creates unnecessary dependencies and can lead to reliability issues. +
Therefore, the first solution is to change the remote host's certificate to
match its identity. If the remote host is not under your control, replicate its
service to a server whose certificate you can change yourself.

If the remote hostname is dynamic, setting up on-the-fly certificate creation
thanks to scripting is a solution. +
If the remote hostname can only be distributed with an private DNS, unreachable
from outside, an alternative could be an intermediary reverse proxy located in
the internal network, with firewall protections that would set up a TLS proxy
thanks to the DNS access, while itself setting up a TLS certificate to fully
protect messages.

In case the contacted host is located on a development machine, this quick
solution is recommended:

* Create a self-signed certificate for that machine.
* Add this self-signed certificate to the system's trust store.
* Set the correct host name in the `/etc/hosts` file.
