== Why is this an issue?

Deprecated language features are those that have been retained temporarily for backward compatibility, but which will eventually be removed from the language. In effect, deprecation announces a grace period to allow the smooth transition from the old features to the new ones. In that period, no use of the deprecated features should be added to the code, and all existing uses should be gradually removed.


This rule raises an issue for uses of the following functions, which were deprecated in PHP 5.4:


||Deprecated||Use Instead||

|``++mcrypt_generic_end()++``||

|``++mysql_list_dbs()++``||



ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

* Remove this "xxx" call. 
* Replace this "xxx" call with a call to "yyy".


'''
== Comments And Links
(visible only on this page)

=== on 27 Jul 2015, 15:26:42 Ann Campbell wrote:
Ref: \http://php.net/manual/en/migration54.deprecated.php



=== on 12 Nov 2015, 18:05:43 Linda Martin wrote:
LGTM!

endif::env-github,rspecator-view[]
