== Why is this an issue?

Most built-in bitwise operators (``++~++``, ``++>>++``, ``++>>=++``, ``++&++``, ``++&=++``, ``++^++``, ``++^=++``, ``++|++``, and ``++|=++``) have implementation-dependent results when performed on signed operands, and bitwise left shift (``++<<++`` and ``++<<=++``) has unspecified or undefined behavior when performed on negative operands.

Therefore bitwise operations should not be performed on signed operands.

Starting with C++20, the behaviors have been defined more accurately (negative values have to be represented using two's complement), and therefore this rule will only report an issue when the second operand of a shift operator is signed (shifting by a negative value is still undefined behavior).

=== Noncompliant code example

[source,cpp]
----
if ( ( uint16_a & int16_b ) == 0x1234U ) // Noncompliant until C++20
if ( ~int16_a == 0x1234U ) // Noncompliant until C++20

auto f(int i) {
    return 1 << i; // Noncompliant
}
----


=== Compliant solution

[source,cpp]
----
if ( ( uint16_a | uint16_b ) == 0x1234U ) 
if ( ~uint16_a == 0x1234U )

auto f(unsigned int i) {
    return 1 << i;
}
----


=== Exceptions

When used as bit flags, it is acceptable to use preprocessor macros as arguments to the & and | operators even if the value is not explicitly declared as unsigned.

----
fd = open(file_name, UO_WRONLY | UO_CREAT | UO_EXCL | UO_TRUNC, 0600);
----

If the right-side operand to a shift operator is known at compile time, it is acceptable for the value to be represented with a signed type provided it is positive.

----
#define SHIFT 24
foo = 15u >> SHIFT;
----

When combining several bitwise operations, even if all leaf operands are unsigned, if they are smaller than an `int`, some intermediate results will be of type `signed int`, due to integral promotion. However, this situation is usually not an issue, and is an exception for this rule:

----
unsigned int f(unsigned short src) {
  return (src >> 3) & 0x1F; // (src >> 3) is of type signed int
}
----

== Resources

* MISRA C:2004, 12.7 - Bitwise operators shall not be applied to operands whose underlying type is signed
* MISRA {cpp}:2008, 5-0-21 - Bitwise operators shall only be applied to operands of unsigned underlying type
* MISRA C:2012, 10.1 - Operands shall not be of an inappropriate essential type
* https://wiki.sei.cmu.edu/confluence/x/9tYxBQ[CERT, INT13-C.] - Use bitwise operators only on unsigned operands
* https://cwe.mitre.org/data/definitions/682[MITRE, CWE-682] - Incorrect Calculation


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Do not apply "X" bitwise operator to a signed operand.


'''
== Comments And Links
(visible only on this page)

=== relates to: S5354

=== on 3 Nov 2014, 12:21:39 Evgeny Mandrikov wrote:
Both https://www.securecoding.cert.org/confluence/x/BoAD[CERT, INT13-C] and https://www.securecoding.cert.org/confluence/x/vIAyAQ[CERT, INT13-CPP] describe exclusions for this rule.

=== on 26 May 2015, 13:51:59 Freddy Mallet wrote:
This rule was generating too much noise on Nemo, so :

* The severity has been decreased from Blocker to Critical
* The rule is no more part of the default "Sonar Way" quality profile

endif::env-github,rspecator-view[]
