WordPress makes it possible to install and update themes and plugins in the Administration Screens.
This is a convenient feature but it's also risky.
If an attacker manages to get access to WordPress admin, this person can 
then take advantage of the theme/plugin management feature to upload PHP code on the server
and to execute that code.
Defining the `DISALLOW_FILE_MODS` option to `true` in `wp-config.php` disables this risky feature.
The default value is `false`.

== Ask Yourself Whether

* You really need to manage themes and plugins inside WordPress Administration Screens.
* Theme or plugin management features are available to users who cannot be fully trusted.
* There's a chance that the accounts of authorized users get compromised.

There is a risk if you answered yes to any of those questions.


== Recommended Secure Coding Practices

* Manage themes and plugins without WordPress Administration Screens. Using wp-cli is a possible option. 
* Make sure that `DISALLOW_FILE_MODS` is defined in `wp-config.php`.
* Make sure that `DISALLOW_FILE_MODS` is set to `true`.

== Sensitive Code Example

----
define( 'DISALLOW_FILE_MODS', false ); // Sensitive
----


== Compliant Solution

----
define( 'DISALLOW_FILE_MODS', true );
----
