=== Rule replacement: RSPEC-3255

=== On 2015-07-08T18:14:20Z Ann Campbell Wrote:
\[~elena.vilchik] note that I've converted this to a subtask of a rule with a more widely-applicable name. Since it's not implemented yet in Swift, I don't anticipate problems with that, but let me know if there are.

=== On 2015-07-27T06:57:13Z Elena Vilchik Wrote:
\[~ann.campbell.2] Unfortunately, it was already implemented. So it's wrong rule key in release (S2963 instead of S3255). WDYT should be done to fix this inconsistency? 

=== On 2015-07-27T13:51:01Z Ann Campbell Wrote:
After discussion with [~elena.vilchik]:

Because Swift version had already been coded and released, this task became the parent, to preserve the rule key, and its contents swapped to the more generic ``++this++``. A new Swift subtask was created, preserving the original contents of this RSpec.

=== On 2015-07-27T13:51:59Z Ann Campbell Wrote:
Do you want to look this over [~elena.vilchik] & make sure I didn't miss anything?

=== On 2015-07-27T13:56:44Z Elena Vilchik Wrote:
\[~ann.campbell.2] i removed swift-specific message from parent. Otherwise looks good!

=== On 2015-11-16T15:41:37Z Tamas Vajk Wrote:
This rule was untargeted for C#, because Visual Studio 2015 reports this to the user in the IDE by default. (The rule ID is IDE0003)

