There is no good reason to silence errors, decrease performance, or block index creation in a procedure, but that's the result of disabling these options.

This rule raises an issue when "ANSI_WARNINGS" and/or "ARITHABORT" are disabled in a procedure.

``++SET ANSI_WARNINGS OFF++``

* CREATE, UPDATE, INSERT, and DELETE statements on tables with indexes on computed columns or indexed views will fail
* No warning issued if null values appear in aggregate functions, such as SUM, AVG, MAX, MIN, STDEV, STDEVP, VAR, VARP, or COUNT
* The divide-by-zero and arithmetic overflow errors cause null values to be returned, no roll-back
* ...

``++SET ARITHABORT OFF++``

* It can negatively impact query optimization, leading to performance issues
* An arithmetic, overflow, divide-by-zero, or domain error, during INSERT, UPDATE, or DELETE statement will cause SQL Server to insert or update a NULL value.
* ...



== Noncompliant Code Example

[source,sql]
----
CREATE PROCEDURE myProc
AS
BEGIN
SET ANSI_WARNINGS OFF; // Noncompliant
// ...
END

CREATE PROCEDURE myProc
AS
BEGIN
SET ARITHABORT OFF; // Noncompliant
// ...
END
----

== Compliant Solution

[source,sql]
----
// OK
CREATE PROCEDURE myProc
AS
BEGIN
END

// OK
CREATE PROCEDURE myProc
AS
BEGIN
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
END
----

:link-with-uscores1: https://learn.microsoft.com/en-us/sql/t-sql/statements/set-arithabort-transact-sql
:link-with-uscores2: https://learn.microsoft.com/en-us/sql/t-sql/statements/set-ansi-warnings-transact-sql
:link-with-uscores3: https://community.sonarsource.com/t/set-ansi-warnings-off-should-not-used-in-stored-procedures-or-indexed-views/3756/6

== See

* {link-with-uscores1}[Microsoft Documentation: SET ARITHABORT (Transact-SQL)]
* {link-with-uscores2}[Microsoft Documentation: SET ANSI_WARNINGS (Transact-SQL)]
* {link-with-uscores3}[Sonar Community thread]
