=== On 2020-09-04T17:14:44.370Z Nicolas Harraudeau Wrote:
Note that this is a low priority rule as tests would fail if this bug is present. It can however be useful for SonarLint users as they will be able to see their mistake more rapidly. It won't add much value for SonarQube/SonarCloud users.

=== On 2021-03-15T23:23:53.651Z Nicolas Coquelet Wrote:
Hi,


This rule throw a false positive on test class annotated with @MockitoSettings.


The official documentation describe that if we use @MockitoSettings annotation to configure Mockito behaviour, we can avoid @ExtendWith(MockitoExtension.class) annotation


Here the official documentation link

https://www.javadoc.io/static/org.mockito/mockito-junit-jupiter/3.8.0/org/mockito/junit/jupiter/MockitoExtension.html

  

=== On 2021-03-17T12:05:23.499Z Quentin Jaquier Wrote:
Hello [~ncoquelet]


First, let me just warn you that commenting on a closed ticket (SONARJAVA-3606) or directly in the RSPEC description is not the best way to get attention as nobody is actively monitoring these places, it is too easy to get unnoticed. The recommended way to go is the https://community.sonarsource.com/[community forum].


As long as I am here, let me answer your question here anyway: 

 What you suggest makes sense to me, and in fact, we recently created SONARJAVA-3734. Since the annotation you are talking about is itself a meta-annotation annotated with ``++@ExtendWith(value=MockitoExtension.class)++``, this ticket should solve your concern as well. I added a point in the description to make sure we test this.


Have a great day,

 Quentin

