== Why is this an issue?

Deprecated language features have been retained temporarily for backward compatibility but will eventually be removed from the language. Deprecation announces a grace period to allow a smooth transition from the old features to the new ones. In that period, no use of the deprecated features should be added to the code, and all existing usages should be gradually removed.

The following features are deprecated in Oracle 18:

[frame=all]
[cols="^1,^1,^1"]
|===
|Deprecated |Replacement| Documentation

|DBMS_LOCK.SLEEP |DBMS_SESSION.SLEEP | https://docs.oracle.com/en/database/oracle/oracle-database/18/arpls/release-changes.html#GUID-EDBEC906-B269-4C5B-A9FE-D5AADA61532B[Docs]
|DBMS_XMLSAVE |DBMS_XMLSTORE | https://docs.oracle.com/en/database/oracle/oracle-database/18/upgrd/deprecated-features-oracle-database-18c.html#GUID-8C087BF4-8E46-4C5D-8456-868D1ED7089A[Docs]
|DBMS_XMLQUERY |DBMS_XMLGEN| https://docs.oracle.com/en/database/oracle/oracle-database/18/upgrd/deprecated-features-oracle-database-18c.html#GUID-7F691CE6-4756-436C-B28E-E6E9215C4C84[Docs]
|===
ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Remove this use of "x"; it is deprecated starting from Oracle 18c and will be removed in the future. Use "y" instead.


=== Highlighting

The deprecated function.


endif::env-github,rspecator-view[]
