== Why is this an issue?

The purpose of the Java Collections API is to provide a well defined hierarchy of interfaces in order to hide implementation details.


Implementing classes must be used to instantiate new collections, but the result of an instantiation should ideally be stored in a variable whose type is a Java Collection interface.


This rule raises an issue when an implementation class:

* is returned from a ``++public++`` method.
* is accepted as an argument to a ``++public++`` method.
* is exposed as a ``++public++`` member.


=== Noncompliant code example

[source,java]
----
public class Employees {
  private HashSet<Employee> employees = new HashSet<Employee>();  // Noncompliant - "employees" should have type "Set" rather than "HashSet"

  public HashSet<Employee> getEmployees() {                       // Noncompliant
    return employees;
  }
}
----


=== Compliant solution

[source,java]
----
public class Employees {
  private Set<Employee> employees = new HashSet<Employee>();      // Compliant

  public Set<Employee> getEmployees() {                           // Compliant
    return employees;
  }
}
----



ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

"XXX" should be an interface such as "YYY" rather than the implementation "ZZZ".

The return type of this method should be an interface such as "YYYY" rather than the implementation "ZZZ".


'''
== Comments And Links
(visible only on this page)

=== on 15 Oct 2013, 09:28:56 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-360

=== on 10 Apr 2017, 00:26:42 ron190 wrote:
I changed LinkedList to List in my project but after 4 levels of changes that I applied successively to return types and parameter types, I encountered list.getLast() and list.removeLast() but those methods do not exist in interface List.


Is it right to use list.get(list.size()-1) instead of list.getLast() in term of performances and complexity ? 


LinkedList keeps references to both head and tail and offers a complexity of O(1), is it the same with list.get(list.size()-1) ?


Posted to Groups (thank you Ann)

https://groups.google.com/forum/#!topic/sonarqube/jc0WU-8RE94

=== on 10 Apr 2017, 15:53:31 Ann Campbell wrote:
\[~ron190] this isn't the best place to initiate a discussion. You'll reach a broader audience if you go to the https://groups.google.com/forum/#!forum/sonarqube[SonarQube Google Group]

endif::env-github,rspecator-view[]
