=== on 6 Aug 2013, 12:13:09 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-268

=== on 6 Aug 2013, 23:14:47 Ann Campbell wrote:
The previous message was a bit contradictory (parenthetical bits are mine): "Merge this condition with the previous (parent), nesting (child) one"


Hope I picked the right direction. 

=== on 29 Oct 2013, 13:25:08 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3211 for Flex

=== on 12 Feb 2014, 16:54:54 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3452 for PHP

=== on 17 Apr 2014, 12:51:26 Ann Campbell wrote:
Note that this rule is not appropriate for VB6; there is no other way to do short-circuit logic.

=== on 28 Jul 2015, 11:56:34 Elena Vilchik wrote:
I think code samples could be removed, as they are not used. [~ann.campbell.2] WDYT?

=== on 28 Jul 2015, 12:42:36 Ann Campbell wrote:
\[~elena.vilchik] I don't think it hurts anything to have them here as an immediate demonstration of what's intended.

=== on 26 Nov 2015, 17:25:28 Elena Vilchik wrote:
\[~ann.campbell.2] Please, validate highlighting. Thanks!

=== on 30 Nov 2015, 18:52:38 Ann Campbell wrote:
Looks good. Thanks [~elena.vilchik]

=== on 8 Nov 2018, 15:16:59 Elena Vilchik wrote:
https://github.com/SonarSource/eslint-plugin-sonarjs/issues/87

