=== Relates: RSPEC-2223

=== On 2014-11-25T11:00:13Z Freddy Mallet Wrote:
\[~ann.campbell.2] If you want I can take care to fully rewrite the rule in something like "Servlet should not have misleading non-static fields"

=== On 2014-11-25T12:28:16Z Ann Campbell Wrote:
\[~freddy.mallet] the original requester was specific that the rule shouldn't be limited to just ``++Servlet++`` classes, but I'm happy to go along if you feel that would make a better rule. 


BTW, he's also asking for an ignoreClasses parameter.

=== On 2019-03-07T23:27:30Z Victor Matskiv Wrote:
The issue is not aligned with servlet semantics. Specifically: 


A servlet can be legitimately initialized from ServletContext using ``++init(ServletContext)++`` method. This makes it impossible to qualify servlet fields as final. 


Another suggestion to make servlet fields static introduces rather misleading semantics and contradicts the referenced document: \https://wiki.sei.cmu.edu/confluence/display/java/MSC11-J.+Do+not+let+session+information+leak+within+a+servlet

