=== On 2015-03-28T22:27:24Z Evgeny Mandrikov Wrote:
\[~freddy.mallet] [~ann.campbell.2] Words "evaluate a 'void' type" doesn't sound good/correct for me, might be better to change on "operand of a void type".

=== On 2015-03-30T13:11:23Z Ann Campbell Wrote:
\[~evgeny.mandrikov] how about 'should not be used on "void"' ?

=== On 2015-03-30T13:19:51Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] fine. But in any case I don't see how second example connected with description, which relates to RSPEC-2215.

=== On 2015-03-31T13:14:15Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] I suspect that [~freddy.mallet] misunderstood Cppcheck rule, so that correct example looks like:

{noformat}

void test() {

  void* p;

  sizeof(*p);

}

{noformat}

and in this case there is indeed no intersection with RSPEC-2215.

=== On 2015-03-31T14:30:56Z Ann Campbell Wrote:
updated

=== On 2015-03-31T14:37:20Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] Title wasn't changed, so I did change and now spec LGTM.

=== On 2015-03-31T16:07:26Z Ann Campbell Wrote:
\[~evgeny.mandrikov] title was changed as I thought you'd agreed. But okay.

=== On 2015-03-31T16:24:04Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] I wasn't agree with word "evaluate", which remained in "used to evaluate 'void'", but I was agree with "used on 'void'" :) and finally took a decision to go ahead with my own proposal :)

=== On 2015-04-09T08:25:07Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] In fact I didn't found that C standard forbids this, whereas {cpp} standard indeed forbids. Also GCC warns about this in {cpp} mode and still compiles, and doesn't warn in C mode. This *GNU extension* is indeed most probably originated from GCC compiler, but exists in some others for compatibility reasons - for example behavior of ICC (Intel Compiler) is the same as GCC, whereas Clang rejects this in {cpp} mode, but accepts in C without any warnings. Also statement "gcc is not a conforming C compiler by default" sounds a bit strong and aggressive. Based on this I think that we should adjust description.

=== On 2015-04-09T09:15:10Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] however most probably I'm wrong about C standard, so taking ticket back to provide more details.

=== On 2015-04-09T13:22:26Z Evgeny Mandrikov Wrote:
C11 6.5.3.4p1:

____
The sizeof operator shall not be applied to an expression that has function type or an incomplete type, to the parenthesized name of such a type, or to an expression that designates a bit-field member. The _Alignof operator shall not be applied to a function type or an incomplete type.

____
and C11 6.2.5p19:

____
The void type comprises an empty set of values; it is an incomplete object type that cannot be completed.

____
from where I conclude that indeed usage of "void" is not allowed by C11 standard.

And indeed - GCC 4.8.4 and Clang 3.6.0 would warn about this in "pedantic" C mode, but not ICC 15.0.2.


CPP11 5.3.3p1:

____
The sizeof operator shall not be applied to an expression that has function or incomplete type, ...

____
CPP11 5.3.6p1:

____
An alignof expression yields the alignment requirement of its operand type. The operand shall be a type-id representing a complete object type or an array thereof or a reference to a complete object type.

____
CPP11 3.9.1p9:

____
The void type is an incomplete type that cannot be completed.

____
So that not allowed by CPP11 too.

As was stated before - Clang will reject with error, GCC and ICC will show warning.


I hope this is enough to clarify description.

Also scope can be extended to cover "alignof" for which compilers behave in the same way as for "sizeof".

=== On 2015-04-13T20:25:02Z Evgeny Mandrikov Wrote:
LGTM.

