== Why is this an issue?

External requests initiated by a WordPress server should be considered as security-sensitive. They may contain sensitive data which is stored in the files or in the database of the server. It's important for the administrator of a WordPress server to understand what they contain and to which server they are sent.

WordPress makes it possible to block external requests by setting the `WP_HTTP_BLOCK_EXTERNAL` option to `true`. It's then possible to authorize requests to only a few servers using another option named `WP_ACCESSIBLE_HOSTS`.

If `WP_HTTP_BLOCK_EXTERNAL` is not defined or set to `false`, any plugin or theme installed on the WordPress server may send requests to any server on the internet. This may lead to data leaks or Server-Side Request Forgery (SSRF) attacks.

== How to fix it

* Uninstall WordPress plugins which send requests to servers you don't know.
* Make sure that `WP_HTTP_BLOCK_EXTERNAL` is defined in `wp-config.php`.
* Make sure that `WP_HTTP_BLOCK_EXTERNAL` is set to `true`.
* Make sure that `WP_ACCESSIBLE_HOSTS` is configured to authorize requests to the servers you trust.

=== Code examples

==== Noncompliant code example

[source,php,diff-id=1,diff-type=noncompliant]
----
define( 'WP_HTTP_BLOCK_EXTERNAL', false ); // Noncompliant
----


==== Compliant solution

[source,php,diff-id=1,diff-type=compliant]
----
define( 'WP_HTTP_BLOCK_EXTERNAL', true );
define( 'WP_ACCESSIBLE_HOSTS', 'api.wordpress.org' );
----

== Resources

* OWASP - https://owasp.org/Top10/A05_2021-Security_Misconfiguration/[Top 10 2021 Category A5 - Security Misconfiguration]
* OWASP - https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/[Top 10 2021 Category A10 - Server-Side Request Forgery (SSRF)]
* https://wordpress.org/support/article/editing-wp-config-php/#block-external-url-requestsl[wordpress.org] - Block External URL Requests
* OWASP - https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration[Top 10 2017 Category A6 - Security Misconfiguration]
* https://owasp.org/www-community/attacks/Server_Side_Request_Forgery[OWASP Attack Category] - Server Side Request Forgery
* CWE - https://cwe.mitre.org/data/definitions/918[CWE-918 - Server-Side Request Forgery (SSRF)]
