=== Related: RSPEC-3358

=== Relates: RSPEC-1684

=== Relates: RSPEC-1821

=== On 2013-08-06T12:11:22Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-267

=== On 2013-08-14T08:16:58Z Dinesh Bolkensteyn Wrote:
I think that 'Non-Compliant' should really be reserved to illustrate that the rule *WILL* produce an issue on that line.

It should not be used for exceptions - else the meaning of Compliant / Non-Compliant becomes hard to understand.

=== On 2013-10-31T16:14:06Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3229 for Flex

=== On 2013-12-12T16:42:18Z Freddy Mallet Wrote:
Flex and {cpp} implementations should be updated to take into account "try" statement

=== On 2014-02-12T22:07:52Z Freddy Mallet Wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3472 for PHP

=== On 2018-02-07T10:50:27Z Tibor Blenessy Wrote:
\[~freddy.mallet] [~alban.auzeill] shouldn't this rule be deprecated in favor of Cognitive Complexity RSPEC-3776? 

=== On 2018-02-07T16:33:01Z Alban Auzeill Wrote:
This rule addresses a specific need. A lot of linters provide this feature, so for users not yet ready to embrace cognitive complexity, we also would like to provide it. For more details, ask [~freddy.mallet]

