=== is related to: S3358

=== is related to: S1684

=== is related to: S1821

=== on 6 Aug 2013, 12:11:22 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARJAVA-267

=== on 14 Aug 2013, 08:16:58 Dinesh Bolkensteyn wrote:
I think that 'Non-Compliant' should really be reserved to illustrate that the rule *WILL* produce an issue on that line.

It should not be used for exceptions - else the meaning of Compliant / Non-Compliant becomes hard to understand.

=== on 31 Oct 2013, 16:14:06 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3229 for Flex

=== on 12 Dec 2013, 16:42:18 Freddy Mallet wrote:
Flex and {cpp} implementations should be updated to take into account "try" statement

=== on 12 Feb 2014, 22:07:52 Freddy Mallet wrote:
Is implemented by \http://jira.codehaus.org/browse/SONARPLUGINS-3472 for PHP

=== on 7 Feb 2018, 10:50:27 Tibor Blenessy wrote:
\[~freddy.mallet] [~alban.auzeill] shouldn't this rule be deprecated in favor of Cognitive Complexity RSPEC-3776? 

=== on 7 Feb 2018, 16:33:01 Alban Auzeill wrote:
This rule addresses a specific need. A lot of linters provide this feature, so for users not yet ready to embrace cognitive complexity, we also would like to provide it. For more details, ask [~freddy.mallet]

