=== Related: RSPEC-5945

=== On 2014-10-15T20:43:16Z Ann Campbell Wrote:
\[~samuel.mercier] please:

* fill in the appropriate reference field(s).
* provide a See section.
* take another stab at the message; I'm not able to follow it.

=== On 2019-10-30T16:06:26Z Nicolas Harraudeau Wrote:
\[~amelie.renard] There is a mismatch between the Noncompliant code, i.e. the function call, and what is fixed in the compliant code, i.e. the called function's signature. It looks like developers won't be able to fix these issues when functions are defined in a third-party library.

=== On 2019-11-04T18:23:39Z Loïc Joly Wrote:
Hello [~nicolas.harraudeau],


I hear your argument, and I think that this issue is not a coding issue, but more a design issue. We are currently thinking about the possibility to report the error on the called function declaration, not at the call site (even if, in some situations, the error can go away by changing the call site...). I'm updating the example accordingly, just to see what it looks like. We might however have some technical issues with this solution, to be checked...


From a strict MISRA point of view (I think we should fork this rule), the error would still be reported at the call site, there is no other way to make sure we report all usages, and MISRA does not really have the notion of "unchangeable third party library": If a library is not safe to use, it should not be used, unless there is a deviation...

=== On 2019-11-04T18:31:46Z Loïc Joly Wrote:
\[~amelie.renard]: Can you please review my proposed changes?

