=== On 2018-11-06T19:59:55Z Ann Campbell Wrote:
I've reworded slightly [~loic.joly]. Double-check me, please. 


Also, it would be useful to give a "such as" here:


____
objects that are not handled by a ``++unique_ptr++``
____


Or to expand a little on the topic in general

=== On 2018-11-07T09:27:50Z Loïc Joly Wrote:
\[~ann.campbell.2] I partially reverted your changes, could you review please (maybe we need to talk about it if you disagree)?

=== On 2018-11-07T20:11:41Z Ann Campbell Wrote:
\[~loic.joly] it's not clear to me how "will not be able to impact the lifetime of the pointed-to object" is a summary/grouping/superset of the two bullet points that follow it, which is why in my edit I struggled, and then combined the three into a single list.

=== On 2018-11-08T09:56:13Z Loïc Joly Wrote:
\[~ann.campbell.2] Lifetime and ownership are deeply linked subject: If A has ownership of B, it means that A is responsible for killing B at some time (at the very least, before its own lifetime ends).

Is the new version clearer?



