=== On 2015-07-02T13:43:04Z Ann Campbell Wrote:
Rule created [~evgeny.mandrikov], but I Google didn't give me much guidance on what the default regex should be (discussions were about content not casing) so I went with all upper case.

=== On 2015-07-02T15:47:42Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] LGTM.

=== On 2015-07-03T13:11:48Z Massimo PALADIN Wrote:
\[~ann.campbell.2] why sqale is 10min when RSPEC-2343 has 5min?

=== On 2015-07-06T14:16:46Z Ann Campbell Wrote:
\[~massimo.paladin] my assumption was that IDE's are sophisticated enough to auto-handle renaming things like vars, enums, &etc, but that label renaming would likely have to be done manually.

=== On 2015-07-07T09:13:39Z Massimo PALADIN Wrote:
\[~ann.campbell.2] changing it to 5min as IDE supports renaming of labels (at least Clion does).

=== On 2015-07-07T11:43:45Z Ann Campbell Wrote:
\[~evgeny.mandrikov] why did you remove the default regex from the description? I've got a ticket in my backlog to add them to such tickets, and as was made clear on the mailing list, if the rule is activated with a different regex, it's not really clear to users what standard the Noncompliant Example is held to.

=== On 2015-07-07T15:43:51Z Evgeny Mandrikov Wrote:
\[~ann.campbell.2] I did this for consistency with RSPEC, which I was implementing at the same time - RSPEC-3084.

