== Why is this an issue?

include::../description.adoc[]

=== Code examples

==== Noncompliant code example

[source,csharp,diff-id=1,diff-type=noncompliant]
----
void DoSomething() 
{
    ; // Noncompliant - was used as a kind of TODO marker
}

void DoSomethingElse() 
{
    Console.WriteLine("Hello, world!");;  // Noncompliant - double ;
    // ...
    // Rarely, they are used on purpose as the body of a loop. It is a bad practice to 
    // have side-effects outside of the loop:
    for (int i = 0; i < 3; Console.WriteLine(i), i++); // Noncompliant
    // ...
}
----

==== Compliant solution

[source,csharp,diff-id=1,diff-type=compliant]
----
void DoSomething() 
{
}

void DoSomethingElse() 
{
    Console.WriteLine("Hello, world!");
    // ...
    for (int i = 0; i < 3; i++)
    {
        Console.WriteLine(i);
     }
    // ...
}
----

== Exceptions

Loops with side effects in their condition or incrementor expressions are excluded from this rule. These loops are intentionally empty because the work is performed in the loop's condition or incrementor.

Examples of side effects that exclude a loop from this rule:

* Increment/decrement operators: `while (++counter < 10);`
* Assignment operators: `while ((value = ReadNext()) != null);`
* Compound assignment operators: `while ((sum += value) < 100);`
* Method calls that may have side effects: `while (reader.Read() != -1);`

For loops with side effects in their incrementors are also excluded:

[source,csharp]
----
for (int i = 0; i < 10; ProcessItem(ref i));
----


ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

'''
== Comments And Links
(visible only on this page)

include::../comments-and-links.adoc[]

endif::env-github,rspecator-view[]
