=== On 2015-11-24T15:03:53Z Ann Campbell Wrote:
\[~tamas.vajk] I noted "Project type for tests project?" as a possible rule. It does look like there is a https://msdn.microsoft.com/en-us/library/ms182413%28v=vs.90%29.aspx[specific project type for tests]. I'm wondering if that shouldn't be covered by this rule so that what this rule would check is not whether a test class is in a project with non-tests (meaning that a helper class would cause issues to be raised on all test classes?) but merely whether a test class is in a non-test-project project. WDYT?

=== On 2015-11-24T15:15:48Z Tamas Vajk Wrote:
\[~ann.campbell.2] This test project type is only used if you want to use the Microsoft test framework. If you are using NUnit, then a normal DLL project is sufficient. So I don't think we can do anything about the test project type.


Thinking a bit about this rule I don't know how we could identify test assemblies and non-test ones. Currently we do two things to find out if a project is a test project or not:


* if the project name contains test, then it's a test
* if the project references a known test library, then it's a test.

However this won't help in identifying if you included a test accidentally in a non test assembly, because we would assume that the library is a test one as it has the necessary references. We could count the number of test and non-test classes and make a decision based on that. WDYT? 


cc [~dinesh.bolkensteyn]

=== On 2015-11-24T16:21:45Z Freddy Mallet Wrote:
Don't know for C# but for Java, if the title would be "Tests should be contained in a dedicated source directory" instead of "Tests should be contained in a separate project" that would be perfect. cc [~ann.campbell.2] and [~tamas.vajk]

=== On 2015-11-24T21:20:47Z Ann Campbell Wrote:
\[~freddy.mallet] Java targeted & subtask added.

