name: Create New RSPEC

# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      languages:
        description: 'Comma-separated list of targeted languages'
        required: true
      number_of_rspecs:
        description: 'Number of RSPECs to create'
        required: true

jobs:
  create_new_rule:
    runs-on: ubuntu-latest-large
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
        ref: master
        path: 'rspec'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 'Install Pipenv'
      run: |
        pip install pipenv

    - name: 'Install rspec-tools'
      working-directory: 'rspec/rspec-tools'
      run: pipenv install

    - name: 'Create Rule'
      working-directory: 'rspec/rspec-tools'
      run: pipenv run rspec-tools create-rule --user ${{ github.actor }} --languages "${{ github.event.inputs.languages }} --count ${{ github.event.inputs.number_of_rspecs }}"
