name: Build and Deploy
on:
  push:
    branches:
      - godin

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: read # Get the list and metadata of open new-rule PRs
      contents: write # Get the contents of open new-rule PRs, the 'master'; write to 'gh-pages' branch
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # If you're using actions/checkout you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          ref: 'godin'

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        working-directory: frontend
        run: |
          sudo apt-get update
          sudo apt-get install libkrb5-dev -y
          npm install
