name: Update quick fix status

on: 
  workflow_dispatch:
    inputs:
      rule:
        description: 'ID of an existing rule (e.g., S1234).'
        required: true
        type: string
      language:
        description: 'Language to be updated for the given rule, (e.g., cfamily)'
        required: true
        type: string
      status:
        description: 'The new status for quick fix (e.g., covered)'
        required: true
        type: choice
        options:
          - covered
          - partial
          - targeted
          - infeasible
          - unknown

jobs:
  update_quickfix_status:
    name: Update quick fix status
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
        ref: master
        path: 'rspec'

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: 'Install Pipenv'
      run: |
        pip install pipenv

    - name: 'Install rspec-tools'
      working-directory: 'rspec/rspec-tools'
      run: pipenv install

    - name: 'Update quickfix status'
      working-directory: 'rspec/rspec-tools'
      run: pipenv run rspec-tools update-quickfix-status --user ${{ github.actor }} --rule "${{ github.event.inputs.rule }}" --language "${{ github.event.inputs.language }}" --status "${{ github.event.inputs.status }}"
