== Why is this an issue?

It is rarely useful to declare a function at block scope. Such a function will not get special access to any name in its enclosing scope, and therefore, it is equivalent but clearer to declare it instead in the enclosing namespace.

Additionally, when a function is declared at block scope, the intent is often not to declare a function but instead to declare and initialize a variable. This problem is nicknamed the _most vexing parse_ and stems from the fact that some syntaxes can be ambiguous, and that in that case the language unintuitively favors function declaration:

[source,cpp,diff-id=1,diff-type=noncompliant]
----
void f() {
  int a;
  string b();
  short c(short (a));
}
----

* `b` could be interpreted as:

** A variable of type `string` with empty initialization or
** A function with no argument and returning a `string`. 

+
The second interpretation is selected.

* Similarly, `c` could be interpreted as:

** A variable of type `short` initialized with the value `a` converted to `short` or 
** A function that takes a parameter named `a` (with extra parentheses) of type `short` and returning a `short`

+
Here again, the second interpretation is selected.

There are several ways to write the code differently so that `b` and `c` can only be interpreted as variables. For instance:

[source,cpp,diff-id=1,diff-type=compliant]
----
void f() {
  int a;
  string b {};
  auto c = short (a);
}
----

By raising issues on local function declaration, this rule helps detect when a function is inadvertently declared.


== How to fix it
=== Noncompliant code example

[source,cpp,diff-id=2,diff-type=noncompliant]
----
class A {
};

void fun() {
  void nestedFun();  // Noncompliant; declares a function in block scope

  A a();      // Noncompliant; declares a function at block scope, not an object
}
----

=== Compliant solution
[source,cpp,diff-id=2,diff-type=compliant]
----
class A {
};

void nestedFun(); // Compliant, function declaration moved outside of fun

void fun() {
  A a;      // Compliant; declares an object
}
----
== Resources
=== External coding guidelines

* MISRA {cpp}:2023, 6.0.1 - Block scope declarations shall not be visually ambiguous
* MISRA {cpp}:2008, 3-1-2 - Functions shall not be declared at block scope
* MISRA C:2004, 8.6 - Functions shall be declared at file scope

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

=== Message

Move this function declaration outside of this block scope.


'''
== Comments And Links
(visible only on this page)

=== on 28 Aug 2013, 13:06:38 Dinesh Bolkensteyn wrote:
----
#include <stdio.h>

void foo() {
  printf("go go go \n"); 
}

int main(int argc, char* argv[]) {
  int foo = 42;

  printf("foo = %d\n", foo);

  {
    void foo(); // Enables the function to be found again, over the variable
    foo();
    printf("running!\n");
  }

  return 0;  
}
----

endif::env-github,rspecator-view[]
